### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MBoretto** [akalongman/php-telegram-bot#1]
Hello! Very nice work!
I manage to install it becouse the method:
$telegram->setWebHook('https://yourdomain/yourpath_to_hook.php');
does not exist!
I tryed to add it like this
public function setWebHook($url_hook){
                return Request::send('setWebhook',array('url'=>urlencode($url_hook)));
        }

but i get a bad request from telegram api

finally i set up the web hook simply with:
https://api.telegram.org/bot{token}/setWebhook?url=https://yourdomain.org/yourpath/hook.php

Seems to me that telegram api don't accept escaped slash like:
https:\/\/yourdomain.org\/yourpath\/hook.php

**Comment by akalongman** [comment]
My bad. Will be fixed in next release. Thanks for report

**Comment by akalongman** [comment]
Fixed
