### ISSUE TITLE
send message to all our bot members

### ISSUE THREAD

**Issue by alirajabi** [akalongman/php-telegram-bot#10]
i wanna to send 10 or more message in one action to all my bot members

telegram permit us to this action. i mean, can i send a message for all my bot members with out any theirs request?

**Comment by MBoretto** [comment]
The bot can reply one or more message to a users message.
You want to send messages without user interaction?

**Comment by alirajabi** [comment]
yes , i wanna to send messages without user interaction

**Comment by MBoretto** [comment]
With the new release you can send message to all the users
