### ISSUE TITLE
Using an "abstract class" into "$commands_path" dir

### ISSUE THREAD

**Issue by vlauciani** [akalongman/php-telegram-bot#109]
Hi

Can I use an "abstract class" into "$commands_path" dir?

For example, I’d like to create:
- myCommands/FirstCommand.php
- myCommands/SecondCommand.php

but these commands inheritance a common “function” then I'd create:
- myCommands/AbstractClass.php
- myCommands/FirstCommand.php
- myCommands/SecondCommand.php

where FirstCommand.php and SecondCommand.php “extend” AbstractClass.php? Is this possible?

How I can set up “namespace” into the Class?

**Comment by MBoretto** [comment]
Hello! yes you can, use this configuration:
```
<?php                                                                                                                                                                                                                
namespace Longman\TelegramBot\Commands;

use Longman\TelegramBot\Request;
use namespace\YourAbstractCommand;
class OkCommand extends YourAbstractCommand
{
    public function execute() {
         ...
         return ...  
      }
}
```
With the new version 0.28 (coming soon) namespace will change a bit. 
Let me know if works, would be great to add a working example in the wiki of this repo!

**Comment by vlauciani** [comment]
Hi

Thank you for your answer.

I don't know if it is the correct approach.

Defining, into the ```hook.php```, file the variable:
```
// My Commands
$commands_path = __DIR__ . '/myCommands/';
```

I'd to create the "abstract class" into ```__DIR__ . '/myCommands/MyAbstractClass.php'``` that extend the "command class":
```
<?php
namespace Longman\TelegramBot\Commands;

use Longman\TelegramBot\Request;
use Longman\TelegramBot\Command;
use Longman\TelegramBot\Entities\Update;

abstract class MyAbstractClass extends Command
{
    protected $name = 'Abstract - name';
    protected $description = 'Abstract - description';
    protected $usage = 'Abstract - usage';
    protected $version = 'Abstract - version';
    protected $enabled = false;
    protected $public = false;

    protected function setParamsUrl() { }

    protected function execute() { }
}
```

then, my "FirstCommand" should extend my "abstract class":
```
<?php
namespace \myCommand;

use EarthquakeAbstract;

class FirstCommand extends MyAbstractClass
{
    protected $name = 'FirstCommand';
    protected $description = 'FirstCommand descritpion';
    protected $usage = '/firstCommand';
    protected $version = '1.0.0';
    protected $enabled = true;
    protected $public = true;

    protected function setParamsUrl() 
    {
        ... 
    }

    public function execute()
    {
        ...
    }
```
is this correct?

**Comment by MBoretto** [comment]
Yes the concept is right but i suggest you to move your abstract class away from  the command path dir.
