### ISSUE TITLE
New commands not work

### ISSUE THREAD

**Issue by paranoiasystem** [akalongman/php-telegram-bot#11]
I have wrote a new command based on help command

```php
<?php
namespace Longman\TelegramBot\Commands;

use Longman\TelegramBot\Request;
use Longman\TelegramBot\Command;
use Longman\TelegramBot\Entities\Update;

class NicoCommand extends Command
{
	public function execute() {
		$update = $this->getUpdate();
		$message = $this->getMessage();

		$chat_id = $message->getChat()->getId();
		$text = $message->getText(true);

  		$data = array();
  		$data['chat_id'] = $chat_id;
  		$data['text'] = "Sorry, ........";

		$result = Request::sendMessage($data);
	}
}
```

But when I write /nico it not work :cry:

What's wrong ?

(Sorry for my bad english :grin: )

**Comment by MBoretto** [comment]
What is the name of the file? It have to be NicoCommand.php

**Comment by paranoiasystem** [comment]
yes, the name is NicoCommand.php

![screen](http://s10.postimg.org/smonglf15/Immagine.png)

http://s10.postimg.org/smonglf15/Immagine.png

**Comment by paranoiasystem** [comment]
ops I don't want close  this :confused:

**Comment by paranoiasystem** [comment]
ops I don't want close this :confused:

**Comment by MBoretto** [comment]
Wich version of the bot you're using? this is not the last one 0.0.8 right?

**Comment by paranoiasystem** [comment]
I have update the bot, but now when I set webhook I recive this error: 

var_dump(self::$telegram->getApiKey()); 

help me :cry:

**Comment by MBoretto** [comment]
Try to do he request manually with this: 
https://api.telegram.org/bot{yourbottoken}/setWebhook?url={yourhttpsurl}

**Comment by paranoiasystem** [comment]
it work. Thanks
