### ISSUE TITLE
How to update DB?

### ISSUE THREAD

**Issue by vavoluk** [akalongman/php-telegram-bot#110]
Is it possible to update my existing DB with php-telegram-bot 0.17.0 to latest version?

**Comment by MBoretto** [comment]
In 0.17 (https://github.com/akalongman/php-telegram-bot/blob/0.17.0/structure.sql) User and chat were already divided. So the update to the new table schema is not an impossible task. 
You should add all missing table and column if any. 
I also suggest you to add constraints to the tables

**Comment by noplanman** [comment]
Hopefully in the not too distant future, we will be able to provide update scripts which will help automate the process and prevent any mistakes :smiley: 

I've created an issue for it here: #112
