### ISSUE TITLE
Problem importing schema.sql

### ISSUE THREAD

**Issue by d8vjork** [akalongman/php-telegram-bot#114]
I'm trying to import schema.sql but...

`#1171 - All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead `

![captura](https://cloud.githubusercontent.com/assets/2331052/13473627/707d3b04-e0ba-11e5-9f61-9719c8aca04d.JPG)

**Comment by MBoretto** [comment]
Hello, thanks for reporting
Are you using mysql 5.7.3 ? Seems a breaking change in the last version..
http://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-3.html#mysqld-5-7-3-bug

**Comment by d8vjork** [comment]
@MBoretto  I'm using 5.7.11 but I've seen a fix in schema.db

Replacing all NULL in Primary Keys.
