### ISSUE TITLE
Recent version cause apache errors

### ISSUE THREAD

**Issue by joseh55** [akalongman/php-telegram-bot#117]
Hi, my 1st error : 

the command **"composer require longman/telegram-bot"** install a OLDER version that have many compatibility issues compared to actual version.

2nd Error.

Actual version cause a apache 500 errors:

curl_setopt_array(): Array keys must be CURLOPT constants or equivalent integer values in /home/hosting/bot/php-telegram-bot/src/Request.php on line 199

PHP Catchable fatal error:  Argument 1 passed to Longman\\TelegramBot\\Entities\\ServerResponse::__construct() must be of the type array, null given, called in /home/hosting/bot/php-telegram-bot/src/Request.php on line 321 and defined in /home/hosting/bot/php-telegram-bot/src/Entities/ServerResponse.php on line 26

**Comment by noplanman** [comment]
Hi @joseh55 

If you could let us know what PHP and cURL version you're using it would make it easier for us to find the problem.

What version does `composer require longman/telegram-bot` install for you?

**Comment by MBoretto** [comment]
1) Try also to to use composer.json as explained in the documentation.
2) This is not a problem of the library this error happen when the telegram server is is not able to receive your request. Try later
