### ISSUE TITLE
Database script: timestamp defaults

### ISSUE THREAD

**Issue by pavlyuts** [akalongman/php-telegram-bot#121]
These lines in the sql script leads to failure on the latest MySQL verions:

  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',

To avoid script failure sql_mode shoud be ajusted for no use NO_ZERO_DATE mode.

It's better to check the issue and decide: 
1. to include some session extra mode-settins into the script OR 
2. require to switch off NO_ZERO_DATE manually OR
3. Change the field defenition to work without issue

Have a nice day!

**Comment by MBoretto** [comment]
Thanks for reporting and for using the library!
I prefer to change the definition, maybe we can move to nullable timestamps? 
@akalongman @noplanman

**Comment by akalongman** [comment]
Yes, we must make all date fields nullable (default null)

**Comment by MBoretto** [comment]
@pavlyuts feel free to pull request!

**Comment by MBoretto** [comment]
fixed in develop

**Comment by MBoretto** [comment]
fixed in 0.30 thanks
