### ISSUE TITLE
Message styling

### ISSUE THREAD

**Issue by pe3udent** [akalongman/php-telegram-bot#124]
Hi,

How to styling message with markdown or html?

**Comment by MBoretto** [comment]
you should add `parse_mode` to the `$data` array according to telegram bot api:
```
$data = [
            'chat_id' => $chat_id,
            'text'    => $your_mark_down_text,
            'parse_mode'  => 'MARKDOWN'
        ];
        return Request::sendMessage($data);
```
Could you please let me kwow if it works? Because i never tried it before and it would be nice to add an example in the library.

**Comment by pe3udent** [comment]
Yes, works great. Thanks!
