### ISSUE TITLE
How to launch bot?

### ISSUE THREAD

**Issue by pe3udent** [akalongman/php-telegram-bot#125]
Sorry for noob question, but how to launch getUpdatesCLI.php script in background (getUpdate installation)?

**Comment by yevstratov** [comment]
I use this method (by @larknart)

create a daemon configuration script under /etc/init ( NOT /etc/init.d ):-

nano /etc/init/mybot.conf
code sample:-

```
description "MyBot Daemon"
author "larknart"

start on startup
stop on shutdown
respawn

exec /usr/share/getUpdateCLI.php
alter getUpdateCLI.php:-

below code:

#while true; do ./getUpdatesCLI.php; done
add:-

$seconds = 5;
$micro = $seconds * 1000000;
```
at end of code below:

}
add:-

```
usleep($micro);
create symbolic link to /usr/share/
```

ln -s /var/www/html/bot/getUpdateCLI.php /usr/share
after finish all those steps...now you can use " stop mybot | start mybot | status mybot " in terminal then you'll automatically get update.

**Comment by MBoretto** [comment]
Thanks for sharing! Would be nice to add this example to the wiki!

**Comment by pe3udent** [comment]
thx!

**Comment by yevstratov** [comment]
I added this example in the wiki

**Comment by MBoretto** [comment]
Thanks!
