### ISSUE TITLE
Support telegram bot api 2.0

### ISSUE THREAD

**Issue by drdim** [akalongman/php-telegram-bot#131]
Today, developers telegram anonced bot api 2.0.
I think what can support whis vertion api.
https://telegram.org/blog/bots-2-0

Features:

- New inline keyboards with callback and URL buttons. Added new objects InlineKeyboardMarkup, InlineKeyboardButton and CallbackQuery, added reply_markup fields to all InlineQueryResult objects. Added field callback_query to the Update object, new method answerCallbackQuery.
Bots can now edit their messages. Added methods editMessageText, editMessageCaption, editMessageReplyMarkup.
Bots can request location and phone number from the user. The keyboard field in the object ReplyKeyboardMarkup now supports KeyboardButton, a new object that can have the fields request_location and request_contact.
Inline bots

- Added support for all content types available on Telegram. 19 types of InlineQueryResult objects are now supported.
Inline bots can now subsitute all kinds of content with text. Added 4 types of InputMessageContent objects.
- You inline bot can also ask users for permission to use their location. Added the new Botfather command /setinlinegeo, added field location to the InlineQuery object, added fields location and inline_message_id to the ChosenInlineResult object.
- Added an easy way to switch between inline mode and a private chat with the bot – useful for settings, establishing external connections and teaching users how to use your bot in inline mode. Added parameters switch_pm_text and switch_pm_parameter to the method answerInlineQuery.
Miscellaneous

- Added group administration tools. New methods kickChatMember and unbanChatMember.
- Added fields venue, pinned_message and entities to the Message object. Added new objects MessageEntity and Venue, new methods sendVenue and sendContact.
Renamed the fields new_chat_participant and left_chat_participant of the Message object to new_chat_member and left_chat_member.

**Comment by MBoretto** [comment]
Sure those this can be supported! Need people to contribute! ;)
