### ISSUE TITLE
Two or more commands in $usage

### ISSUE THREAD

**Issue by CrazyRedScorp** [akalongman/php-telegram-bot#132]
Thanks for this API. Sorry, my english isn't good. But!
Tell me please - how to make two or more "usage-key" in one CommandModule. I didn't find this in the documentation and in the demos.
Sample:
```
protected $usage = '/cat /tomcat /pussycat';
```
Thanks.

**Comment by CrazyRedScorp** [comment]
I have learned that the key depends on the name in the class definition.
```
class <UsageKey>Command extends UserCommand
protected $usage = '/UsageKey';
```

I did this, so:
##### file1: CatCommand.php
```
<?php
namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\Entities\ReplyKeyboardMarkup;

/**
 * User "/cat" command
 */
class CatCommand extends UserCommand
{
    /**#@+
     * {@inheritdoc}
     */
    protected $name = 'cat';
    protected $description = 'Send Cat';
    protected $usage = '/cat';
... ... ...
<code>
?>
```

##### file2: TomcatCommand.php
```
<?php
namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\Entities\ReplyKeyboardMarkup;

/**
 * User "/tomcat" command
 */

class TomcatCommand extends CatCommand
{
}
?>
```

And if you write '/cat' or 'tomcat', we get the same result.
Thanks.

**Comment by MBoretto** [comment]
There is also a wiki page
https://github.com/akalongman/php-telegram-bot/wiki/Create-your-own-commands
feel free to improve it!

**Comment by CrazyRedScorp** [comment]
Ops! Please sorry, I do not read the Wiki =((

**Comment by CrazyRedScorp** [comment]
But. There's a wiki does not say what to do to work with UTF-8 encoding. I know the solution. I write a new Issa or write here?

**Comment by CrazyRedScorp** [comment]
I wrote in the issue number #135

**Comment by MBoretto** [comment]
I'm closing!
