### ISSUE TITLE
UTF-8 characters in the class definition and command

### ISSUE THREAD

**Issue by CrazyRedScorp** [akalongman/php-telegram-bot#135]
Maybe it's no use to anyone, but I was helped.
I need a command in the Cyrillic alphabet. I added a few lines in "Telegram.php" file:
```
    protected function mb_ucwords($str, $encoding = 'UTF-8') {
        return mb_convert_case($str, MB_CASE_TITLE, $encoding);
    }

    protected function mb_ucfirst($str, $encoding = 'UTF-8') {
        return mb_strtoupper(mb_substr($str, 0, 1, $encoding), $encoding) . mb_strtolower(mb_substr($str, 1, mb_strlen($str), $encoding), $encoding);
    }
```
And replace in this file all function of "ucwords" to "mb_ucwords" and of "ucfirst" to "mb_ucfirst". Now I can use the Cyrillic alphabet in commands. Next, I created a file "КошкаCommand.php":
```
<?php
namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Request;

/**
 * User "/Кошка" command
 */

class КошкаCommand extends KursCommand
{
```
Thanks.

**Comment by MBoretto** [comment]
Thanks for the feedback! I think that this feature would be useful to other user! Would you open a pool request to include your mods in the library? Great!

**Comment by CrazyRedScorp** [comment]
Added #136
