### ISSUE TITLE
Add library in /examples/Commands/HidekeyboardCommand.php

### ISSUE THREAD

**Issue by CrazyRedScorp** [akalongman/php-telegram-bot#137]
Hi. I tested examples commands and found a bug.
```
PHP Fatal error:  Class 'Longman\\TelegramBot\\Commands\\UserCommands\\ReplyKeyboardHide' not found in ......../Commands/HidekeyboardCommand.php on line 42
```
You need to add a string of library in the file "examples/Commands/HidekeyboardCommand.php":
```
namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\Entities\ReplyKeyboardMarkup;

use Longman\TelegramBot\Entities\ReplyKeyboardHide; <- this
```
Thanks.

**Comment by noplanman** [comment]
@CrazyRedScorp, feel free to make pull requests yourself if you find something like this! 😃 
Thanks for reporting!

**Comment by CrazyRedScorp** [comment]
Thank for you!
I first tried to create a pull here and that did not work. Did you see my errors. Now I will try to fix it. If this is true (without errors) - I will use the pull.

**Comment by noplanman** [comment]
I've already made a pull request for this issue, but for future ones you can do them yourself if you like.
What errors? You mean the one `PHP Fatal error: ...`?

**Comment by CrazyRedScorp** [comment]
Yes. I have seen. Thanks.

I'm talking about the error in my code ("correct the line endings to Unix style").

**Comment by noplanman** [comment]
Ah yes I saw those. If you need any assistance considering that, just comment on your PR and we'll help 👍
