### ISSUE TITLE
Please update your description for the variable "$BOT_NAME"

### ISSUE THREAD

**Issue by CrazyRedScorp** [akalongman/php-telegram-bot#138]
Hi. I read the question and noticed the problem with the bot name. I had the same problem.

I send @botfather command "/setcommands" and choose @mycats_bot and type "command1 - my description". Then I wrote in a chat (or click on the left "/"):
```
/command1@mycats_bot
```
But answer = empty. Why?! This is my error! My $BOT_NAME was wrong.

You need to update your description for the variable $BOT_NAME:
$BOT_NAME = 'username_bot';
This is username of bot with "_bot"!!! That you have specified in the @botfather in a message: "Now let's choose a username for your bot. It must end in `bot`".

Not "namebot" (example: "firstcats"), only "username_bot" (example: "mycats_bot").

Thanks.

**Comment by noplanman** [comment]
I'll let you make a PR for this, ok?

**Comment by CrazyRedScorp** [comment]
Ok. Thank you very much!

**Comment by CrazyRedScorp** [comment]
I created #145
But, you change the description to "README.md" file. I am not strong in english.

**Comment by MBoretto** [comment]
merged!
