### ISSUE TITLE
Sequential chat

### ISSUE THREAD

**Issue by 0x38** [akalongman/php-telegram-bot#14]
Hi, is possible to make sequential chat?

I would like to build an interface like this:
user: /weather
bot: Enter location
user: Barcelona
bot: Show weather in Barcelona

**Comment by MBoretto** [comment]
Is not possible now.
There is already another conversation for this issue:
https://github.com/akalongman/php-telegram-bot/issues/7

**Comment by 0x38** [comment]
Yes I see it, but I don't know if was solved.
thanks.
