### ISSUE TITLE
How to add a record in to DB?

### ISSUE THREAD

**Issue by Recouse** [akalongman/php-telegram-bot#149]
I want to add a record in to DB to disable sending message from newsletter. How I can do it?

**Comment by jacklul** [comment]
I wasn't able to find other solution than this: https://gist.github.com/jacklul/2e4fd56d98a752cc728db425596df8ff

$result = DBHelper::query($query); - returns data for selection queries, true/false for others
$text = DBHelper::quote($text); - PDO::quote equivalent, for text that can contain quote symbols

**Comment by Recouse** [comment]
Thanks.
