### ISSUE TITLE
Task scheduler

### ISSUE THREAD

**Issue by jacklul** [akalongman/php-telegram-bot#156]
For example if you want to send notifications to users at specified time and date.
This can be of course done currently by sending fake update but it would be nice to have a build-in task scheduler.

**Comment by ruslanmedia** [comment]
You need add to cron

**Comment by aleksraiden** [comment]
At my project, I'am using Disque (project from Redis author) and one simple php daemon to send messages.

**Comment by jacklul** [comment]
Currently in testing: https://github.com/jacklul/php-telegram-bot/tree/crontab
