### ISSUE TITLE
First response

### ISSUE THREAD

**Issue by KotovDmitry** [akalongman/php-telegram-bot#16]
When I run the code nothing happens ("Input is empty!")
What should I do, what I would write to the bot (for example /newcommand) and he will respone "Hello Dmitry!" ?
Please, help me to write my first simple bot app.

**Comment by akalongman** [comment]
Read README file please. First you must create bot in Telegram via Botfather
After you must set webhook

**Comment by azizimusa** [comment]
I have setup all that, bot, hook and in browser displayed "Webhook was set". After that, I dont have idea how to make it response with bot command.

**Comment by MBoretto** [comment]
If everything is set properly as you say, type in a chat with your bot:
/echo Hello!
it should respond to you.

**Comment by danielberlin** [comment]
I have the same problem.

set.php gives `Webhook was not set! Error:` (with no error following after "Error:")

However, I can set the web hook manually by directly calling api.telegram.org with curl. Then interacting with my bot results in messages written to mysql table messages

`{"id":123344,"title":null,"first_name":"myName","last_name":null,"username":"null","bot_name":null}` and column `text` also contains what I wrote to my bot.

However, `/echo Hello!` doesn't result in any reaction from my bot. You wrote it should respond, but why doesn't it do that?

**Comment by MBoretto** [comment]
Hello, in the latest release I've work around setWebHook and request to the server. I've used setWebhook and it works for me.  Let me know if you still recognise this those problems.
