### ISSUE TITLE
is it tested with PHP7?

### ISSUE THREAD

**Issue by evazzadeh** [akalongman/php-telegram-bot#160]
Hi, i use PHP7.
Telegram server after sending some message getting in loop and repeatedly send some messages to our server and does not stop!
before getting in loop the response is created random! is it normal!?

we unset the bot, but after setting it again telegram send old messages again and start repeating!

**Comment by Recouse** [comment]
I also use PHP7. All my bots work good.

**Comment by MBoretto** [comment]
There are already two post about looping, 
php7 is not involved in this problem
https://github.com/akalongman/php-telegram-bot/issues/127
https://github.com/akalongman/php-telegram-bot/issues/126

**Comment by evazzadeh** [comment]
We find out the problem
In our system we disallow **cli** and telegram use cli for sending messages! and because of this our server refused telegram and telegram getting in loop because cant deliver messages
