### ISSUE TITLE
Result object properties are protected!

### ISSUE THREAD

**Issue by ahmadazizi** [akalongman/php-telegram-bot#161]
In response to message sending methods, the returning result object  has properties that have been set as protected.
There is the method is_ok() which returns the value of 'ok' property, but there are no methods to get the other response properties.
This is not perfect, as there is no way to access the server responses.
thanks.

**Comment by MBoretto** [comment]
https://github.com/akalongman/php-telegram-bot/blob/master/src/Entities/ServerResponse.php#L106
