### ISSUE TITLE
How does it handle command during a group chat?

### ISSUE THREAD

**Issue by aczone** [akalongman/php-telegram-bot#165]
If the bot is added a group chat, or with other bots in a group, the command will then be /command@bot_name, it will then fail to execute the command.
I do not know if it is my problem since I have amneded the scripts quite a lot
And Thanks for the fabulous work!!!

**Comment by jacklul** [comment]
$BOT_USERNAME must be set exactly to your's bot username.

**Comment by aczone** [comment]
work with charm! thank you!

**Comment by sprnza** [comment]
sorry for necrobump, but in what file this var is being set?
