### ISSUE TITLE
very need inlineQuery example commads to /expamples

### ISSUE THREAD

**Issue by tihoho** [akalongman/php-telegram-bot#166]
most wanted! :)

**Comment by MBoretto** [comment]
There is already an inline query command example in the library, you didn't spot it? Or you think thath is not enough ?
https://github.com/akalongman/php-telegram-bot/blob/master/src/Commands/SystemCommands/InlinequeryCommand.php

**Comment by tihoho** [comment]
Sorry, i lost eyes :)
