### ISSUE TITLE
error in composer

### ISSUE THREAD

**Issue by khazrakian** [akalongman/php-telegram-bot#17]
Hi dear, when I use this command " composer require longman/telegram-bot " I got this error 
"
Using version dev-master for longman/telegram-bot
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package longman/telegram-bot No version set (parsed as 1.0.0
) could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

Installation failed, reverting ./composer.json to its original content.
"

Can u say me, What should I do ????

**Comment by MBoretto** [comment]
It works fine to me!

**Comment by weiddolo** [comment]
I get the same problem!

 Problem 1
    - The requested package longman/telegram-bot No version set (parsed as 1.0.0) could not be found.

**Comment by MBoretto** [comment]
Try to:
1) Fork the project, and replace mboretto/php-telegram-bot with yourname/php-telegram-bot in the following instructions
2) Add to composer.json :
```
    "repositories": [
        {
            "type":"package",
            "package": {
              "name": "mboretto/php-telegram-bot",
              "version":"master",
              "source": {
                  "url": "https://github.com/mboretto/php-telegram-bot.git",
                  "type": "git",
                  "reference":"master"
                }
            }
        }
    ]
```
Add under "require" in composer.json :
```
"mboretto/php-telegram-bot": "*@dev" 
```
then run: (only update a specific package)
```
composer update mboretto/php-telegram-bot
```
Add the namespace fot the bot class under "autoload" "psr-4" in composer.json:
```
"Longman\\TelegramBot\\": "vendor/mboretto/php-telegram-bot/src"
```
then run:
```
composer dump-autoload
```
Let me know if it works also for you.

**Comment by weiddolo** [comment]
Have you a skype account or other chat? I'm a newbie of composer.

**Comment by weiddolo** [comment]
I get the same problem when i run:
<code>composer update mboretto/php-telegram-bot</code>

**Comment by akalongman** [comment]
@MBoretto maybe we must define version in composer as "*@dev"?

**Comment by MBoretto** [comment]
Here's my composer.json:
```
{                                                                                                      
    "name": "yourproject/yourproject",
    "type": "project",
    "require": {
        "php": ">=5.4.0",
        "mboretto/php-telegram-bot": "*@dev"
    },


    "autoload": {
        "psr-4": {
                "Longman\\TelegramBot\\": "vendor/mboretto/php-telegram-bot/src"
        }
    },


        "repositories": [
        {
            "type":"package",
            "package": {
              "name": "mboretto/php-telegram-bot",
              "version":"master",
              "source": {
                  "url": "https://github.com/mboretto/php-telegram-bot.git",
                  "type": "git",
                  "reference":"master"
                }
            }
        }
    ]
}
```

I'm new to composer too.. iIwill read the documentation better..

**Comment by weiddolo** [comment]
I've forked https://github.com/akalongman/php-telegram-bot and i've edit composer like this: 

<code>{
    "name": "longman/telegram-bot",
    "type": "library",
    "description": "PHP telegram bot",
    "keywords": ["telegram", "bot", "api"],
    "license": "MIT",
    "homepage": "https://github.com/akalongman/php-telegram-bot",
    "support": {
        "issues": "https://github.com/akalongman/php-telegram-bot/issues",
        "source": "https://github.com/akalongman/php-telegram-bot"
    },
    "authors": [
        {
        "name": "Avtandil Kikabidze aka LONGMAN",
        "email": "akalongman@gmail.com",
        "homepage": "http://longman.ge",
        "role": "Developer"
        }
    ],
    "require": {
        "php": ">=5.4.0",
        "ext-pdo": "*",
        "ext-curl": "*",
		"longman/telegram-bot": "*"
    },
    "autoload": {
        "psr-4": {
            "Longman\\TelegramBot\\": "src/"
        }
    },
	"repositories": [
        {
            "type":"package",
            "package": {
              "name": "weiddolo/php-telegram-bot",
              "version":"master",
              "source": {
                  "url": "https://github.com/mboretto/php-telegram-bot.git",
                  "type": "git",
                  "reference":"master"
                }
            }
        }
    ],
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "require-dev": {
        "phpunit/phpunit": "4.1.*",
        "phpspec/phpspec": "~2.1",
        "squizlabs/php_codesniffer": "2.3.*"
    }
}
</code>
what's wrong?

**Comment by MBoretto** [comment]
I can't reproduce the problem on Ubuntu 14.04. 
when i run:
```
composer require longman/telegram-bot
```
everything goes fine.
You can olso try to remove composer cache:
``` 
rm ~/.composer -R
```
@akalongman 
the installation works also with both those specification:
```
{                                                                                                                                 
    "name": "yourproject/yourproject",
    "type": "project",
    "require": {
        "php": ">=5.4.0",
        "longman/telegram-bot": "*@dev"
    }
}

{                                                                                                                                 
    "name": "yourproject/yourproject",
    "type": "project",
    "require": {
        "php": ">=5.4.0",
        "longman/telegram-bot": "*"
    }
}
```
@weiddolo 
Follow my instruction carefully...

**Comment by MBoretto** [comment]
Do this:
```
git clone https://github.com/akalongman/php-telegram-bot.git
cd php-telegram-bot/
composer dump-autoload
``` 
then edit the set.php and hook.php as described in the README

**Comment by weiddolo** [comment]
Ok thanks you i've cloned and upload on my host, but if i run set.php i will get this error:

Catchable fatal error: Object of class Longman\TelegramBot\Entities\ServerResponse could not be converted to string in /********************/******************/htdocs/php-telegram-bot/set.php on line 15

**Comment by weiddolo** [comment]
I've cloned and upload on my host the LAST VERSION (packagist v0.17.0), but if i run example-set.php i will get this error:

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /web/htdocs/DOMAIN.EXT/home/php-telegram-bot/example-set.php on line 10

Parse error: syntax error, unexpected T_STRING in /web/htdocs/DOMAIN.EXT/home/php-telegram-bot/example-set.php on line 10

**Comment by weiddolo** [comment]
I've cloned and upload on my host the LAST VERSION (packagist v0.17.0), but if i run example-set.php i will get this error:

<code>Parse error: syntax error, unexpected '[' in /web/htdocs/www.mindthelab.it/home/weiddolo/src/Telegram.php on line 112</code>

**Comment by MBoretto** [comment]
I reported all this information in https://github.com/akalongman/php-telegram-bot/wiki/Composer-require-Troubleshooting

**Comment by ivancarrazana** [comment]
I haved de same issue with other repos
Don't download a zip of the project, clone the project using git and de issue are solved
