### ISSUE TITLE
More than one message in the same command

### ISSUE THREAD

**Issue by daanieel** [akalongman/php-telegram-bot#173]
I have a doubt, how can I do to a command receive more than one User response without leaving the command. for example the command /data and the first command asks age after age User responds to the system asks other information such as name and then another as cell but all in the same command /data as if the User were talking to bot.

I do not know if I could be very clear.

**Comment by Recouse** [comment]
For example look **survey** command https://github.com/akalongman/php-telegram-bot/blob/master/src/Commands/UserCommands/SurveyCommand.php

**Comment by noplanman** [comment]
We're also in the process of planning a better way to create custom survey-like commands, making it easier for users to create questions and answers.
It will take a while till we start development, but stay tuned 😉

**Comment by daanieel** [comment]
Thank you guys, I got here .. I will stay connected update.

**Comment by juananpe** [comment]
> We're also in the process of planning a better way to create custom survey-like commands, making it easier for users to create questions and answers.

Is there any place (forum, wiki, mailing-list, irc..) where I can follow the discussion about how are you planning this? I'm interested. Thanks.

**Comment by noplanman** [comment]
@juananpe Not yet, it's just been a verbal discussion so far, but I will create a new issue when the time comes and mention you in it so that you get a notification 👍
