### ISSUE TITLE
How to send more than one message?

### ISSUE THREAD

**Issue by Recouse** [akalongman/php-telegram-bot#174]
How to send more than one message as answer of command?

**Comment by MBoretto** [comment]
? just call two time sendMessage

**Comment by Recouse** [comment]
How i do this?
`return sendMessage();
return sendMessage();`?
it's incorrect

**Comment by jacklul** [comment]
You only 'return' the last one. 
Or if you have complex command you can $result = Request::sendMessage(); each and on the end of command return $result;
