### ISSUE TITLE
How get user id in InlineQueryCommand?

### ISSUE THREAD

**Issue by tihoho** [akalongman/php-telegram-bot#175]
$update = $this->getUpdate();
$inline_query = $update->getInlineQuery();
$query = $inline_query->getQuery();
$fromId = $inline_query->getFrom()->getId(); // not work.

**Comment by jacklul** [comment]
Are you 100% sure? Because it works here

**Comment by tihoho** [comment]
No, not 100%, sorry, it's real work. Bug in my code.
