### ISSUE TITLE
How to make buttons like these?

### ISSUE THREAD

**Issue by deios0** [akalongman/php-telegram-bot#180]
Hi! I wondered how can I make buttons like these with your SDK?

![image](https://cloud.githubusercontent.com/assets/1776997/15179504/64fd8f2c-17a6-11e6-903e-c4253496eb25.png)

Thank you for your help!

**Comment by noplanman** [comment]
Hi @deios0, would you mind sharing where you get those? Is it a bot you're using?
I've never seen them like that, but they look cool 😃 

Clicking them dynamically changes the chart I assume?

**Comment by jacklul** [comment]
It's Bots 2.0 feature:

```
use Longman\TelegramBot\Entities\InlineKeyboardMarkup;

(...)

$inline_keyboard[] = [
    [
        'text' => "inline",
        'switch_inline_query' => ''
    ],
    [
        'text' => "callback",
        'callback_data' => ''
    ]
];
$inline_keyboard[] = [
    [
        'text' => 'open url',
        'url' => ''
    ]
];

$data['reply_markup'] = new InlineKeyboardMarkup(
    [
        'inline_keyboard' => $inline_keyboard
    ]
);
```

[My bot](telegram.me/inlinegamesbot) uses those.

**Comment by MBoretto** [comment]
Pick the code from develop there is a fix for the inline keyboard
let me know

**Comment by deios0** [comment]
Used **jackul** version and it works for me.

**Comment by MBoretto** [comment]
```  
      $inline_keyboard = [
            new InlineKeyboardButton(['text' => 'inline', 'switch_inline_query' => 'true']),
            new InlineKeyboardButton(['text' => 'callback', 'callback_data' => 'identifier']),
            new InlineKeyboardButton(['text' => 'open url', 'url' => 'https://github.com/akalongman/php-telegram-bot']),
        ];
        $data = [
            'chat_id' => $chat_id,
            'text'    => 'inline keyboard',
            'reply_markup' => new InlineKeyboardMarkup(['inline_keyboard' => [$inline_keyboard]]),                                           
        ];
```

In the latest version work with this code instead of the above

**Comment by deios0** [comment]
Thank you, works.

**Comment by noplanman** [comment]
@MBoretto Looking at the code required to create a keyboard, I feel there should be a way to simplify it all by making some kind of helper layer (which was the idea of the `Keyboard` etc. classes).

All those boxed array are quite confusing to me (maybe it's just me!).

What do you think, shall we open an issue for a "Keyboard Wizard" 😃

**Comment by jacklul** [comment]
Alternatively some kind of Helpers folder could be made containing classes that simplify some procedures like creating keyboards and inline keyboards.

**Comment by noplanman** [comment]
@jacklul Yes, I totally agree!

Added to that, we'd have a helper for the conversations, to simplify the setup of the survey.
(Will make a new issue about this when I've thought about it a bit more)

**Comment by MBoretto** [comment]
Would be nice, I agree only if those `tool` would not limit possibility

**Comment by noplanman** [comment]
@MBoretto In the contrary! We'd try to make them even more flexible and easy to use 😃 
From a user view, I think it would help a lot so that more energy can be put into the actual command functionality, not trying to get the individual features (keyboard, conversation, etc.) to work properly.

I think we'll leave this conversation here as it is and continue the discussion on a new issue, ok?

**Comment by MBoretto** [comment]
Ok also because i didn't understand exactly what you mean!
