### ISSUE TITLE
How to get responce to any non-command message?

### ISSUE THREAD

**Issue by Sogl** [akalongman/php-telegram-bot#185]
Hello!

I want to implement this thing:
* if user types `/<anycommand>` bot works with his/her command
* if user types something else, bot show him/her standard message

How to do the second part?

**Comment by jacklul** [comment]
GenericmessageCommand.php is executed every time user sends any message to the bot, text, sticker, photo etc.

**Comment by Sogl** [comment]
>GenericmessageCommand.php is executed every time user sends any message to the bot, text, sticker, photo etc.

I found that this file is already exists in `SystemCommands` folder, but why it not working by default?
I need to copy it to my `Commands` folder?

**Comment by jacklul** [comment]
Works fine here, if you expect it to work in groups you must set bot privacy to disabled in botfather.

**Comment by Sogl** [comment]
>Works fine here, if you expect it to work in groups you must set bot privacy to disabled in botfather.

I have no groups and my bot can't be added to any group (BotFather policy `/setjoingroups` DISABLED).
But if I type any non-command message my bot still silent. Do I need to copy `GenericmessageCommand.php` to my `Commands` folder?

**Comment by noplanman** [comment]
> Do I need to copy GenericmessageCommand.php to my Commands folder?

Yes! That's the command that handles all "generic messages" 😉 
Just copy that file to your custom commands folder and modify it.

You will find 2 methods there for you to customise:
- `executeNoDb()` is called if there is **no** database connection and
- `execute()` is called if there is a database connection

If you take a look at the [`/echo`](https://github.com/akalongman/php-telegram-bot/blob/master/src/Commands/UserCommands/EchoCommand.php) command, you can see how to get the message text, work with it and then return whatever you like.

**Comment by Sogl** [comment]
@noplanman I added file and change it a bit in `executeNoDb()` method and after sending test message my bot stop any activity... lol. I delete this file and try to set/unset webhook... nothing happenes.

**Comment by noplanman** [comment]
Could you post what you `hook.php` file and your `executeNoDb()` function looks like please.
If your other commands all work, I assume there is a problem somewhere there.

This is my example for `executeNoDb()`, which is basically like the `/echo` command:
```php
public function executeNoDb()
{
    $message = $this->getMessage();

    return Request::sendMessage([
        'chat_id' => $message->getChat()->getId(),
        'text'    => $message->getText(),
    ]);
}
```

**Comment by Sogl** [comment]
Now works like a charm.

The problem was that I copied the class file for editing, but forgot to do it inside:
```
[16-May-2016 17:53:01 Etc/GMT-11] PHP Fatal error:  Cannot redeclare class
Longman\TelegramBot\Commands\UserCommands\OrderCommand in /var/www/telegram/Commands/
TokenCommand.php on line 0
```

Solved. Thx for all for your help.
