### ISSUE TITLE
How create interaction with tunel ?

### ISSUE THREAD

**Issue by timothylhuillier** [akalongman/php-telegram-bot#186]
Hi,

I don't understand, you work only with command and not message of user ?
And how do I create interaction with the message ?

For example, How do I ask the number of point for this new party to my user and Him respond me with text, the number allowed.

If I understand, I have to create custom (or extends) GenericMessageCommand and this custom command have execute() who have a regex test ?

To create something like that ([telegram example](https://core.telegram.org/bots/samples/hellobot)) :

    if (strpos($text, "/start") === 0) {
      apiRequestJson("sendMessage", array('chat_id' => $chat_id, "text" => 'Hello', 'reply_markup' => array(
        'keyboard' => array(array('Hello', 'Hi')),
        'one_time_keyboard' => true,
        'resize_keyboard' => true)));
    } else if ($text === "Hello" || $text === "Hi") {
      apiRequest("sendMessage", array('chat_id' => $chat_id, "text" => 'Nice to meet you'));
    } else if (strpos($text, "/stop") === 0) {
      // stop now
    } else {
      apiRequestWebhook("sendMessage", array('chat_id' => $chat_id, "reply_to_message_id" => $message_id, "text" => 'Cool'));
    }
Thanks.

**Comment by MBoretto** [comment]
Did you tried the /survey command? i guess is what you looking for
