### ISSUE TITLE
nginx php-fpm running error

### ISSUE THREAD

**Issue by abc0707** [akalongman/php-telegram-bot#19]
Hello, after install and setup properly I got this error: 

 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function isEnabled() on a non-object in /var/www/vendor/longman/telegram-bot/src/Commands/HelpCommand.php

could you please help me this that?

**Comment by MBoretto** [comment]
are you using 0.11?

**Comment by abc0707** [comment]
Hello MBoretto,
I tried composer install require... then I got that problem
then I tried composer updatte .... problem solved :)

Thanks

**Comment by abc0707** [comment]
yeah... seem like 0.1.1 has problem (composer install), when i tried 0.0.7 (clone from git), it works just fine

**Comment by Doranku** [comment]
Issue is not related to nginx and still persists in 0.12

**Comment by abc0707** [comment]
confirmed... I tried with apache, still have this problem

**Comment by Doranku** [comment]
The problem there is a non object in the getCommandsLists ('leftchatparticipant' => false)

To prevent this from having a working bot, the symptom can be avoided with following patch.

```
--- a/src/Commands/HelpCommand.php
+++ b/src/Commands/HelpCommand.php
@@ -37,6 +37,10 @@ class HelpCommand extends Command
             $msg = 'GeoBot v. ' . $this->telegram->getVersion() . "\n\n";
             $msg .= 'Commands List:' . "\n";
             foreach ($commands as $command) {
+               if(!is_object($command))
+               {
+                       continue;
+               }
                 if (!$command->isEnabled()) {
                     continue;
                 }
```

Or by removing src/Commands/LeftChatParticipantCommand.php. But the real solve is having the getCommandsList method in Telegram check whether the getCommandClass returned a Command object.

**Comment by MBoretto** [comment]
I've pull a commit that fix the  help command. Just wait the merge or get
the code from my repository.

**Comment by Doranku** [comment]
That is a "lazy way" patch :)
I meant fix the source of the problem:  
````
--- a/src/Telegram.php
+++ b/src/Telegram.php
@@ -193,6 +193,10 @@ class Telegram
             if (substr($name, -11, 11) === 'Command.php') {
                 $name = strtolower(str_replace('Command.php', '', $name));
                 $commands[$name] = $this->getCommandClass($name);
+               if(!($commands[$name] instanceof \Longman\TelegramBot\Command))
+               {
+                       unset($commands[$name]);
+               }
             }
         }

@@ -209,7 +213,11 @@ class Telegram
                     $name = $fileInfo->getFilename();
                     if (substr($name, -11, 11) === 'Command.php') {
                         $name = strtolower(str_replace('Command.php', '', $name));
                         $commands[$name] = $this->getCommandClass($name);
+                       if(!($commands[$name] instanceof \Longman\TelegramBot\Command))
+                       {
+                               unset($commands[$name]);
+                       }
                     }
                 }
             }
````

**Comment by MBoretto** [comment]
Commits has been merged
