### ISSUE TITLE
ERROR: Unknown column in new update

### ISSUE THREAD

**Issue by deios0** [akalongman/php-telegram-bot#192]
With new update I;m getting this error message:

[2016-05-18 23:10:27] prod.ERROR: ErrorException: PDOStatement::execute(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'forward_from_chat' in 'field list' in vendor/longman/telegram-bot/src/DB.php:781

**Comment by deios0** [comment]
I've created in table message a column forward_from_chat BIGINT. It works now, but I'm not sure it's an expected behaviour.

**Comment by noplanman** [comment]
At the moment there is no automatic (or manual for that matter) update script to alter the table schema, they need to be made manually to the existing database table.
So it makes sense that you got the error, because that field was newly added.

The way you solved it is ok.

#112
