### ISSUE TITLE
Encoding problem? Maybe if you agree...

### ISSUE THREAD

**Issue by jmmosino** [akalongman/php-telegram-bot#195]
Hi everyone!

I develop both Telegram and Facebook Messenger bots. 

I have one (@ieechibot) that performs the same fuctions of a FB bot (https://facebook.com/ChatBot-para-Saber-Dónde-Votar-en-México-211948212518217/). The queries are the same and the encoding are the same [utf8_encode(string)].

In my FB bot everything works OK and my bot responds as expected (by sending the messages requested accordingly to the keywords sent by its users) but, in my Telegram bot, it seems that the encoding of the string retrieved from the database have a problem and the message requested by the user, using the same keyword that in my FB bot, it is NOT sent by my Telegram Bot (@ieechibot).

Any ideas?

Your help will be highly appreciated.

**Comment by MBoretto** [comment]
can you provide an example?

**Comment by jmmosino** [comment]
I solve it already! Thank you for your help MBoretto!

**Comment by MBoretto** [comment]
Could you report what the problem was and how you solve it?
