### ISSUE TITLE
Wrong parametrs to substr function

### ISSUE THREAD

**Issue by commfort** [akalongman/php-telegram-bot#196]
If you trying to call $message->getText(true)  for message where only command is present then you calculation would be wrong [Line 376](https://github.com/akalongman/php-telegram-bot/blob/master/src/Entities/Message.php#L376): 
`$text = substr($text, strlen($command) + 1, strlen($text));` 

And `substr` will return false because start position is higher than `$text ` it self. I think it should be something like this
`$text = substr($text, min(strlen($command) + 1, strlen($text)), strlen($text));`

**Comment by MBoretto** [comment]
Hello, would you pr?

**Comment by MBoretto** [comment]
how is possible?
this test works
https://github.com/akalongman/php-telegram-bot/blob/master/tests/Unit/Entities/MessageTest.php#L58

**Comment by commfort** [comment]
I tried to call $message->getText(true) for message with only command and instead of empty string I got false. Then I found that in EchoCommand example you wrap this call with trim

`trim($message->getText(true));`

**Comment by MBoretto** [comment]
Could you provide the raw update?
