### ISSUE TITLE
InlineQuery not working

### ISSUE THREAD

**Issue by blissy** [akalongman/php-telegram-bot#197]
Hi,
i try to use the InlineQuery command and get the following Error/Warning:
{"ok":false,"error_code":400,"description":"Bad request: Field \"input_message_content\" must be of type Object"}
{"update_id":896021,
"inline_query":{"id":"587238532085","from":{"id":MYID,"first_name":"MYNAME"},"query":"gu","offset":""}}

For this post i change MYID and MYNAME.

To reproduce copy InlinequeryCommand.php from src/Commands/SystemCommands in your Commands-Folder and then use your bot with the inline command. I also try to use the InlineQueryResultPhoto class in the InlineQueryCommand istead.

I also see this warning:
 PHP Warning:  Invalid argument supplied for foreach() in vendor/longman/telegram-bot/src/Entities/Entity.php on line 80 when using inline command.

Am I doing something wrong or is this a bug?

**Comment by jacklul** [comment]
Example in master branch is out of date, use example from develop:

https://github.com/akalongman/php-telegram-bot/blob/develop/src/Commands/SystemCommands/InlinequeryCommand.php

**Comment by blissy** [comment]
Thank you! Using the dev-branch solve the issue.

**Comment by noplanman** [comment]
> Command in master branch is out of date, use the one from develop

@MBoretto When are you planning to release the next version to have the master branch up to date and working?

**Comment by jacklul** [comment]
[API 2.1 changes](https://github.com/jacklul/php-telegram-bot/tree/apiupdate) should be added before releasing, optionally https://github.com/akalongman/php-telegram-bot/pull/189.
