### ISSUE TITLE
Telegram conversation encoding

### ISSUE THREAD

**Issue by Sogl** [akalongman/php-telegram-bot#205]
Hello!

I use DB to store bot data. Today I saw this in `conversation` table:
![image](https://cloud.githubusercontent.com/assets/7556290/15527123/6e660138-2283-11e6-9d4a-8c3fcbe0d09d.png)

English letters stores fine, but other looks like: `\u0417\u0430`. In telegram client all looks good...
In `message` table letters shows fine.
Is this a problem?

**Comment by jacklul** [comment]
Thats because this data is json encoded, jsons encodes special characters into this format.

**Comment by Sogl** [comment]
It's normal letters (Russian language), not the special chars.

**Comment by jacklul** [comment]
Russian characters are not normal characters, if it comes to encoding.

**Comment by Sogl** [comment]
In `message` table they are looks correct.

**Comment by jacklul** [comment]
Fields in ```message``` table are not being json encoded, they are using database/table encoding.
Json converts all UTF8 characters into escaped unicode characters.

What is the problem anyway? When you get state data back using Conversation characters should be as they were typed.

**Comment by Sogl** [comment]
>What is the problem anyway? 

Uncomfortable to watch string conversation values in the database.
Also I want to understand how it works.

**Comment by noplanman** [comment]
@Sogl 
To find out more about JSON and how it handles different data types, check here:
http://json.org/

closing here...
