### ISSUE TITLE
getChat() php fatal error

### ISSUE THREAD

**Issue by ivanuz** [akalongman/php-telegram-bot#206]
`[error] [client 173.245.53.24] PHP Notice:  Undefined variable: command in /vendor/longman/telegram-bot/src/Telegram.php on line 477`

`[error] [client 173.245.53.24] PHP Fatal error:  Call to a member function getChat() on a non-object in /vendor/longman/telegram-bot/src/Commands/GenericCommand.php on line 29`

Bot worked very well last 4 month. 
But yesterday began errors.
Nothing changed on server.
Any suggestions?

longman/telegram-bot : 0.21.0

`        DB::insertRequest($update);
        $result = $this->executeCommand($command, $update);
        return $result;
`

**Comment by jacklul** [comment]
Very outdated library version.

**Comment by ivanuz** [comment]
Your solution didn't help.
Just updated for a new version and there is new error:
`PHP Fatal error:  Call to a member function getFrom() on a non-object in /vendor/longman/telegram-bot/src/Commands/SystemCommands/GenericmessageCommand.php on line 51`

`        $conversation = new Conversation(
            $this->getMessage()->getFrom()->getId(),
            $this->getMessage()->getChat()->getId()
        );
`

**Comment by MBoretto** [comment]
Would be useful to see the raw update

**Comment by noplanman** [comment]
@ivanuz Is this still a problem or has it been solved in the meantime?
If it's still an issue, a raw update as @MBoretto suggested would really help, thanks!

**Comment by noplanman** [comment]
@ivanuz If this is still an issue for you, feel free to reopen.

**Comment by khaninejad** [comment]
version: 0.36.0
PHP Fatal error:  Call to a member function getFrom() on null in ...public_html/telegram/vendor/longman/telegram-bot/src/Commands/SystemCommands/GenericmessageCommand.php on line 63
