### ISSUE TITLE
Answer only to last message

### ISSUE THREAD

**Issue by Sogl** [akalongman/php-telegram-bot#208]
Hello!

Situation:
1. Server is down
2. Many users sends much messages thinking that bot is freezing.
4. Server is up
5. All users get answers to all the early messages after one of them sends new.

How to prevent this and receive answer only on the last message?

**Comment by jacklul** [comment]
If using webhooks Telegram 'forgets'  messages older than 24 hours, if using getUpdates requesting negative offset will fetch only latest update(s) (at least according to the documentation)
```offset = -99999999999999999999999999```

You could also check date in the beggining of the command, if its like older than 5 minutes reply with empty response.

**Comment by Sogl** [comment]
>If using webhooks Telegram 'forgets' messages older than 24 hours

Too much for this situation :D 

>You could also check date in the beggining of the command

Where to find it? 

>if its like older than 5 minutes reply with empty response.

In `GenericMessage.php`? 

Maybe you can provide some code?

**Comment by jacklul** [comment]
You will have to put something like this on the beggining of each command:
```php

if ($message->getDate() < strtotime("-5 minutes")) {
   return Request::emptyResponse();
}
```

It will have to be adjusted to other commands (provided code wont work for inline and callback queries etc).

This is untested code.

**Comment by Sogl** [comment]
Tested and works fine.

How to put this code in one "all commands" place?

**Comment by jacklul** [comment]
That will require editing **Telegram.php**.

Add before:
```php
//execute() method is executed after preExecute()
//This is to prevent executing a DB query without a valid connection
$this->last_command_response = $command_obj->preExecute();
```
something like this:
```php

if (($message = $this->update->getMessage()) && $message->getDate() < strtotime("-5 minutes")) {
   return Request::emptyResponse();
}
```
_Inline Queries, Chosen Inline Results and Callback Queries does not have date field._
Untested.
