### ISSUE TITLE
Getting two documents in one conversation

### ISSUE THREAD

**Issue by ruslanmedia** [akalongman/php-telegram-bot#215]
Hi! How to getting two documents in conversation. How to set $message->getDocument() to null?

**Comment by noplanman** [comment]
Could you please explain more?

Do I understand correctly, that you want to upload multiple documents to a conversation?
If it's always just 2, you could code it like that, in 2 steps of the conversation.

If it could be any number of documents, you could loop in the "upload documents" state of your conversation and ask the user if they have finished uploading all documents.

**Comment by ruslanmedia** [comment]
Not multiple documents, need step by step upload documents to conversation.
For example, first case was get one document and forward to second case. In second case need get an other document.

**Comment by jacklul** [comment]
```
1. Ask user to upload a document
2. When it's uploaded store it's id in conversation notes and ask user to finish or upload anoher document
3. GOTO 1 OR END
```

**Comment by ruslanmedia** [comment]
@jacklul Yep! Ask user to upload another document on next step.
For example:
```
Bot: Please, upload your passport document file
User: **User uploaded document**
Bot: Please, upload your photo as document file
User: **User uploaded document**
```
Need get two files from user.
Sorry, My English is bad :-1:

**Comment by noplanman** [comment]
Take the `/survey` command as a template, then add these cases:
```php


case 0:
    if (is_null($message->getDocument())) {
        $this->conversation->notes['state'] = 0;
        $this->conversation->update();

        $data['text'] = 'Upload document:';
        $data['reply_markup'] = new ReplyKeyBoardHide(['selective' => true]);
        $result = Request::sendMessage($data);
        break;
    }
    $file_id = $message->getDocument()->getFileId();
    $this->conversation->notes['document_id'] = $file_id;

    // Download the document.
    $r = Request::getFile(['file_id' => $file_id]);
    if ($r->isOk()) {
        Request::downloadFile($r->getResult());
    }

case 1:
    if (is_null($message->getPhoto())) {
        $this->conversation->notes['state'] = 0;
        $this->conversation->update();

        $data['text'] = 'Upload picture:';
        $data['reply_markup'] = new ReplyKeyBoardHide(['selective' => true]);
        $result = Request::sendMessage($data);
        break;
    }
    $file_id = $message->getPhoto()[0]->getFileId();
    $this->conversation->notes['photo_id'] = $file_id;

    // Download the photo.
    $r = Request::getFile(['file_id' => $file_id]);
    if ($r->isOk()) {
        Request::downloadFile($r->getResult());
    }
```

You can adapt as necessary 😃

**Comment by ruslanmedia** [comment]
But, I need get two document files not photo

**Comment by noplanman** [comment]
Right, I've adapted my example above.
Instead of getting a photo in the second case, we just get another document.

**Comment by ruslanmedia** [comment]
If you use $message->getDocument() more than one in switch, works only first $message->getDocument(). Other cases will be skip

**Comment by noplanman** [comment]
Oh, I see now what you mean, sorry!

What I did that worked:
- Upload document
- Upload photo
- Upload document
- Upload photo

But I see now that uploading 2 documents after one another fails.

I'll check this out in more depth!

**Comment by noplanman** [comment]
Ok, I see now what the problem is.
Because the cases have no `break;`, it just runs through. So it just runs through case 0 and then case 1 also, because `getDocument()` is still true! So it updates both cases in one step.

Will need to find a fix for you as an interim, as we're planning to redesign the conversations in the near future.

**Comment by noplanman** [comment]
As a quick fix, add these functions to your command class:
```php
/**
 * Set the value of a private/protected property of an object
 *
 * @param object $object   Object that contains the property
 * @param string $property Name of the property who's value we want to set
 * @param mixed  $value    The value to set to the property
 */
private function setObjectProperty($object, $property, $value)
{
    $ref_object   = new \ReflectionObject($object);
    $ref_property = $ref_object->getProperty($property);
    $ref_property->setAccessible(true);
    $ref_property->setValue($object, $value);
}

/**
 * Download file from Telegram
 *
 * @param string $file_id ID of the file to download
 */
private function downloadFile($file_id)
{
    $r = Request::getFile(['file_id' => $file_id]);
    if ($r->isOk()) {
        Request::downloadFile($r->getResult());
    }
}
```

Then, after downloading the document, we unset the document member variable of the message:
```php
case 0:
//fu($message->getDocument());
    if (is_null($message->getDocument())) {
        $this->conversation->notes['state'] = 0;
        $this->conversation->update();

        $data['text'] = 'Upload document 1:';
        $data['reply_markup'] = new ReplyKeyBoardHide(['selective' => true]);
        $result = Request::sendMessage($data);
        break;
    }
    $this->conversation->notes['document_1_id'] = $message->getDocument()->getFileId();

    // Download document.
    $this->downloadFile($message->getDocument()->getFileId());

    // Unset document.
    $this->setObjectProperty($message, 'document', null);
```
(Same thing for document 2 etc.)

**Comment by ruslanmedia** [comment]
Cheers! It works. Thank you for your help!

**Comment by noplanman** [comment]
👍
