### ISSUE TITLE
Copy message from other channel

### ISSUE THREAD

**Issue by ashkufaraz** [akalongman/php-telegram-bot#220]
Hi
Sorry,I have a question about your project(telegram).
Can I get the message channels that I'm not their admin?
I want write a script that read message from other chanel and write to
my chanel.
I can do it?
best regards
thanks

**Comment by noplanman** [comment]
This is not possible.

The channel administrator can only add your bot as an Administrator, granting it permissions to get the updates.

If the other channel administrator is willing to do this, then it is possible.
