### ISSUE TITLE
Best way to implement a "superadmin" handling?

### ISSUE THREAD

**Issue by xtrahost** [akalongman/php-telegram-bot#223]
In my bot project I search for a way to tread users ("superadmins") differently. The "superadmins" should coexist with the admins. They should be able to see / use some more commands than default users / admins can see (like this already implemented  in the admin feature).

What is the most efficient way to implement this?

Should I make a copy of all related enableAdmins classes? Because I'm very new to php I 
worry that I will fail.

Can someone give me some advices.

I would be very grateful! Thank you.

**Comment by noplanman** [comment]
As it is implemented now with the User and Admin commands, it's not possible to have a Superadmin one.

What you could do though, if have an Admin command that first checks to see if the user is a Superadmin.
Obviously all Admins would be able to see the command in the help list and call it, but they'd get an answer like "You are not authorised" or something.

Another possibility, as you suggested yourself, would be to adapt the code and duplicate everything that exists for Admin and call it Superadmin. That will work, but will need a lot of code modifications.

Regarding your worry of failing, if you don't try you've already failed!
So just give it a try and see 😃👍

**Comment by xtrahost** [comment]
I've implemented your first mentioned idea. It was easy to implement and is sufficient for my needs.

Thanks for your answer! :+1:

**Comment by noplanman** [comment]
Ok 👍 

@MBoretto @jacklul @akalongman 
Maybe we implement a SuperAdmin group into the library some day? What do you think?

**Comment by MBoretto** [comment]
Would be nice to have different levels of admin permissions! Could be introduced with the commander class! 
https://github.com/akalongman/php-telegram-bot/issues/93
https://github.com/akalongman/php-telegram-bot/issues/106
