### ISSUE TITLE
how to start it on open shift?

### ISSUE THREAD

**Issue by smaznet** [akalongman/php-telegram-bot#224]
i used this tut for installing on my openshift server but the but not working

whats is php version required and tools
i only setup php 5.4 and mysql

**Comment by noplanman** [comment]
Minimum requirements are PHP 5.5.

Regarding MySQL, it depends which features you would like to use.
Check the readme to learn more.

**Comment by smaznet** [comment]
@noplanman thank you i will test it 

another question : i used this method for my bot 

git clone https://github.com/akalongman/php-telegram-bot.git
cd php-telegram-bot/
composer dump-autoload

and question is where i should place the hook.php 
in php-telegram-bot folder ?

**Comment by noplanman** [comment]
You can put the `hook.php` wherever you want, you just need to include the `autoload.php` from your vendor folder.
Preferably it would be outside (and above) the vendor folder.

**Comment by smaznet** [comment]
thank you my problem solved by upgrading php version :+1:
