### ISSUE TITLE
Can't add custom command path

### ISSUE THREAD

**Issue by iamraccoon** [akalongman/php-telegram-bot#225]
Sorry for my English...

I can call addCommandsPath() in the Controller, but there is bug in Longman\TelegramBot\Telegram.php method getCommandObject() at line 243:

`$command_namespace = __NAMESPACE__ . '\\Commands\\' . $auth . 'Commands\\' . $this->ucfirstUnicode($command) . 'Command';`

__NAMESPACE__ return only "Longman\TelegramBot".
__NAMESPACE__  never return my commands path.

So new Commands can be executions only they are located in a system folder like Longman\TelegramBot\Commands\SystemCommands.

**Comment by noplanman** [comment]
All commands need to belong to the correct namespace.
Your custom commands classes need to extend the type of command they are.

Look at the [examples/commands](https://github.com/akalongman/php-telegram-bot/tree/master/examples/Commands) folder for examples.
e.g. [MarkdownCommand.php](https://github.com/akalongman/php-telegram-bot/blob/48619a2963e73bdb42d428a7bc84d2b06cbfdb47/examples/Commands/MarkdownCommand.php)

**Comment by iamraccoon** [comment]
Thanks a lot, it's work!

But it is not logical. [MarkdownCommand.php](https://github.com/akalongman/php-telegram-bot/blob/48619a2963e73bdb42d428a7bc84d2b06cbfdb47/examples/Commands/MarkdownCommand.php) should have namespace examples\commands, not Longman\TelegramBot\Commands\UserCommands.

I thought we adhere to the standard PSR-0

**Comment by noplanman** [comment]
The example commands are intended for copy-pasting, so that the namespaces are already set correctly 👍
