### ISSUE TITLE
Calc command doesn't work

### ISSUE THREAD

**Issue by yorickdewid** [akalongman/php-telegram-bot#23]
Due to an error in the Hoa packages the entire bots hangs on the /calc example. The other examples are clear enough to understand the API and how to implement your own commands. Took me a few hours to debug the whole thing to finally come to the conclusion its not this package that causes the problems.

**Comment by MBoretto** [comment]
What about require a particular version of hoa that let the command work? Which version did you use to test?

**Comment by yorickdewid** [comment]
You [require](https://github.com/akalongman/php-telegram-bot/blob/master/composer.json#L24) Hoa in the composer file for the telegram bot. Since its only an example and the bit doesn't really require the packages to work at all I removed the dependency from my project. Just letting you know.

**Comment by MBoretto** [comment]
Thanks for testing and reporting. 
Calc command has been moved to the branch cmdcalc so brave programmers can try to fix it!

**Comment by yorickdewid** [comment]
I believe Hoa has patched the error just today.

**Comment by Hywan** [comment]
Hello :-),

What was the error exactly?
