### ISSUE TITLE
How to get last message id?

### ISSUE THREAD

**Issue by deios0** [akalongman/php-telegram-bot#235]
I'm trying to use **editMessageText** and I need to know the ID of the message I sent. 

How can I get it? Thank you!

**Comment by jacklul** [comment]
If the message is using callback query buttons then you can extract it callbackquery->getmessage->getmessageid

Otherwise you have to save each message sent from request::sendmessage (it replies with sent message that includes the id)

**Comment by deios0** [comment]
Thank you!
