### ISSUE TITLE
Error 409 Conflict

### ISSUE THREAD

**Issue by nicktan147** [akalongman/php-telegram-bot#245]
When I try to run getUpdatesCLI.php, I received this error
```
exception 'Longman\TelegramBot\Exception\TelegramException' with message 'Client error: `POST https://api.telegram.org/bot183556241:AAHmVl68cfxjKhOrB0sDJuX9FndSb67U5OA/getUpdates` resulted in a `409 Conflict` response:
{"ok":false,"error_code":409,"description":"Conflict: another webhook is active"}
```

Any reason why? 

UPDATE: I managed to resolved that issue, but I have successfully setup Let's encrypt and https is up. I don't seems to receive any successful message as mentioned on FAQ section?

Here is my code:-
```php
require '../vendor/autoload.php';

$API_KEY = 'SOMEKEYHERE';
$BOT_NAME = 'SOMEBOTHERE';

$hook_url = 'https://example.com/path/to/hook.php';

try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);

    // Set webhook
    $result = $telegram->setWebHook($hook_url,'');
    if ($result->isOk()) {
        echo $result->getDescription();
    }
} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    echo $e;
}
```

**Comment by noplanman** [comment]
What is the output of your script? Just empty?

P.S. I have modified your hook URL to a dummy one, since this location should stay secret!!

**Comment by nicktan147** [comment]
Hmmm I think I will close this temporary. It call using CLI, it will return
empty. If i do it using browser with full link by copy and pasting
replacing it works fine.

**Comment by noplanman** [comment]
Ok, that's strange. CLI should output the same thing as calling it through the browser.

I'll close here now, open again if needed!
