### ISSUE TITLE
how to use edit message

### ISSUE THREAD

**Issue by rashcms** [akalongman/php-telegram-bot#249]
Hi
How is it possible to edit last message ?
Is it possible to edit image messages as well ?
Is it possible to get the source message id in inline query callback ?
Thanks

**Comment by jacklul** [comment]
>How is it possible to edit last message ? 
https://github.com/akalongman/php-telegram-bot/issues/235

>Is it possible to edit image messages as well ?
Editing image messages will only let you edit caption

>Is it possible to get the source message id in inline query callback ?
Full message object (including id) is sent with each callback query.
