### ISSUE TITLE
Dealing with undefined commands

### ISSUE THREAD

**Issue by manolab** [akalongman/php-telegram-bot#26]
Hi!

If the bot receives an undefined command something like that is thrown in the apache logs:

```
[Mon Aug 31 10:55:02.370494 2015] [:error] [pid 17414] [client 149.154.167.198:47253] PHP Fatal error:  Class 'Longman\\TelegramBot\\Commands\\GeloCommand' not found in /var/www/html/bot/vendor/longman/telegram-bot/src/Telegram.php
```

How can I deal with that? Which class do I need to tamper with to catch that error and, for example, reply some text to suggest the use of /help??

Thanks!

**Comment by MBoretto** [comment]
Thank for reporting!
you can try to modify this line:
https://github.com/akalongman/php-telegram-bot/blob/master/src/Telegram.php#L375
with:
if ($class) {
anyway i will fix it in the next relase

**Comment by manolab** [comment]
Thanks! I extended the Telegram class with my version of executeCommand function and all works as I wanted!

**Comment by manolab** [comment]
Thanks! I extended the Telegram class with my version of executeCommand function and all works as I wanted!
