### ISSUE TITLE
GuzzleHttp configuration problem

### ISSUE THREAD

**Issue by naghibi-farshad** [akalongman/php-telegram-bot#265]
Hi Dear,
i received an error message when configuration files with git:
`Class 'GuzzleHttp \ Client' not found in -> src \ Request.php on line 95
`

**Comment by noplanman** [comment]
Hi @naghibi-farshad 
So this is solved for you already?

Would you mind sharing what you did to make it work, just in case somebody else has the same problem at some point.

**Comment by naghibi-farshad** [comment]
Hi @noplanman 
thanks pal
my problem was the composer.json structure
that was resolved

**Comment by noplanman** [comment]
Ok! Glad you got it to work 👍
