### ISSUE TITLE
Use the command /sendtoall <message to send> error

### ISSUE THREAD

**Issue by nullcookies** [akalongman/php-telegram-bot#266]
Use the command / sendtoall <message to send>
get an error if someone from the bot users banned or removed from chat

`Longman\TelegramBot\Exception\TelegramException: Client error: `POST https://api.telegram.org/bot<token>/sendMessage` resulted in a `403 Forbidden` response: {"ok":false,"error_code":403,"description":"Bot was blocked by the user"} in src\Request.php:206 Stack trace: #0 src\Request.php(297): Longman\TelegramBot\Request::execute('sendMessage', Array) #1 src\Request.php(340): Longman\TelegramBot\Request::send('sendMessage', Array) #2 [internal function]: Longman\TelegramBot\Request::sendMessage(Array) #3 src\Request.php(861): call_user_func_array('Longman\\Telegra...', Array) #4 src\Commands\UserCommands\SendtoallCommand.php(53): Longman\TelegramBot\Request::sendToActiveChats('sendMessage', Array, true, true, true, NULL, NULL) #5 src\Commands\Command.php(131): Longman\TelegramBot\Commands\UserCommands\SendtoallCommand->execute() #6 src\Telegram.php(437): Longman\TelegramBot\Commands\Command->preExecute() #7 src\Telegram.php(407): Longman\TelegramBot\Telegram->executeCommand('sendtoall') #8 src\Telegram.php(316): Longman\TelegramBot\Telegram->processUpdate(Object(Longman\TelegramBot\Entities\Update)) #9 examples\getUpdatesCLI.php(59): Longman\TelegramBot\Telegram->handleGetUpdates() #10 {main}`

In Request.php comment  ~ 200 line
`// try {
            $response = self::$client->post(
                '/bot' . self::$telegram->getApiKey() . '/' . $action,
                $request_params
            );
       // } catch (RequestException $e) {
          //  throw new TelegramException($e->getMessage());
       // } finally {
            //Logging verbose debug output
        //    TelegramLog::endDebugLogTempStream("Verbose HTTP Request output:\n%s\n");
       // }`

I receive an error
`GuzzleHttp\Exception\ClientException: Client error: `POST https://api.telegram.org/bot<token>/sendMessage` resulted in a `403 Forbidden` response: {"ok":false,"error_code":403,"description":"Bot was blocked by the user"} in vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 107`

FIX
In Request.php ~ 95 line 
add 'exceptions'=>false, 'expect' => false

self::$client = new Client(['base_uri' => self::$api_base_uri, 'exceptions'=>false, 'expect' => false]);

**Comment by jacklul** [comment]
For now any non-200 response from telegram stops the script and throws exception.

**Comment by nullcookies** [comment]
Understood thanks

**Comment by deios0** [comment]
Is there way to ignore some non-200 responses? For example, 403? Just want to keep my error log clean.

**Comment by jacklul** [comment]
@deios0, my personal solution:

This assumes usage of `\Longman\TelegramBot\TelegramLog::initErrorLog('error.log');` in webhook:

```php
(...)

} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    $handle = fopen('ignored_errors.txt', 'r');
    if ($handle) {
        while (($line = fgets($handle)) !== false) {
            if (strpos($e, trim($line)) !== false) {
                exit;
            }
        }

        fclose($handle);
    }

    \Longman\TelegramBot\TelegramLog::error($e);
} catch (Longman\TelegramBot\Exception\TelegramLogException $e) {
    file_put_contents(
        'error.log',
        '[' . date('Y-m-d H:i:s', time()) . ']' . "\n" . $e . "\n",
        FILE_APPEND
    );
}

```
You have to put error text you want to ignore into `ignored_errors.txt`, my example:
```
Bot was blocked by the user
bot was kicked from the group chat
_ID_INVALID
message is not modified
message not found
is empty!
```

**Note that this will not fix script stop on non-200 reply.**

**Comment by deios0** [comment]
Thanks! Fixed it and got another one error:

`prod.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function isOk() on boolean in /vendor/longman/telegram-bot/src/Telegram.php:340`

Do you return something in this case? I tried return true, return null and return 1;

**Comment by noplanman** [comment]
Have a look at #263.

There seems to sometimes be an issue with updates coming from Telegram, which should be fixed in the next release of the library.

Hopefully it will be ready soon!

**Comment by dzarezenko** [comment]
What if we can take response data from the Exception message? Something like this:

```
try {
   .....
} catch (\Longman\TelegramBot\Exception\TelegramException $e) {
    $message = $e->getMessage();
    preg_match("/{.+}/", $message, $matches);
    $json = null;
    if (isset($matches[0]) && !empty($matches[0])) {
        $json = json_decode($matches[0]);
    }
    var_dump($json);
}
```

**Comment by deios0** [comment]
Did you try it? What should I send as return value?

**Comment by dzarezenko** [comment]
In this code I receive JSON object with Telegram API response. So now you can check...

```
if ($json->error_code == 403) {
    // ...
}
```
or something like that.
