### ISSUE TITLE
sendPhoto produces Bad Request: there is no photo in the request

### ISSUE THREAD

**Issue by nickustinov** [akalongman/php-telegram-bot#267]
Problem: sendPhoto produces telegram response "Bad Request: there is no photo in the request."

Here is CURLFile Object in $data['photo'] before self::send('sendPhoto', $data) in Request.php line 352: 
(
    [name] => /usr/share/nginx/html/callbot/public/assets/fancy.jpg
    [mime] => 
    [postname] =>
)

I am using included ImageCommand.php, the file is existent, is actually a jpg file and is chosen by Request::sendPhoto($data, $this->ShowRandomImage('/usr/share/nginx/html/callbot/public/assets')); in ImageCommand.php

Nick

**Comment by MBoretto** [comment]
Which version are you using?

**Comment by noplanman** [comment]
Hi, I seem to have missed this issue.

Check here: #268

**Comment by nickustinov** [comment]
Thanks, that was the problem, updating to 0.35 fixed it.
