### ISSUE TITLE
MySQL table 'messages' doesn't exist

### ISSUE THREAD

**Issue by dzarezenko** [akalongman/php-telegram-bot#272]
I am trying configure server for my bot with `getUpdate` method. I have configured MySQL database and created structure from the `structure.sql` file. But I received message like MySQL table 'messages' doesn't exist. 

I see only 'message' table in the DB. So what I do wrong?

**Comment by noplanman** [comment]
Is this a new installation with the latest version of the library and an empty database?

**Comment by dzarezenko** [comment]
Yes, I have installed it with composer and create empty database with your `structure.sql` file. Then I have created a `getUpdateCLI.php` file like in your example, but with my settings.

**Comment by noplanman** [comment]
Where do you see this error?
Could you add the entire stack trace if available please.

Also, make sure the MySQL credentials in your `getUpdatesCLI.php` are correct 😊 
(sometimes instead of `localhost`, you need to enter `127.0.0.1`)

**Comment by dzarezenko** [comment]
![telegram-bot](https://cloud.githubusercontent.com/assets/148570/17766894/0cadd2e0-6536-11e6-8a65-b047097e9f9b.jpg)

**Comment by noplanman** [comment]
I don't think this is the latest version 0.35, as the line numbers in your error message make no sense. It seems more likely to be <= 0.24. Could you verify your version number in Telegram.php please ($version member variable).

Also, I see that there is a self-signed certificate error. I assume you're using Webhook method, yes? In that case, make sure that the self-signed certificate is set correctly, [check the wiki](https://github.com/akalongman/php-telegram-bot/wiki/Self-Signed-Certificate) on how to do that.

**Comment by dzarezenko** [comment]
I have updated to the last version. DB error gone away. But I still have SSL certificate exception.

But I am trying not Webhook method but getUpdate. That's why I use MySQL. As I see SSL certificate not required in this case. Why I have received this exception.

Thanks!

**Comment by noplanman** [comment]
Hmm, that's a good question!

You still get the same error even with the latest version then?
Anything in the error log?

**Comment by noplanman** [comment]
Hi @dzarezenko 

What did you do to fix this?
We'd all appreciate it if you could describe the solution, just in case somebody else may have it at some point, thanks!

**Comment by dzarezenko** [comment]
I have moved from getUpdate to Webhook method and configured Self-signed certificate.
