### ISSUE TITLE
error Call to a member function tryMention()

### ISSUE THREAD

**Issue by ahora007** [akalongman/php-telegram-bot#275]
hi

Call to a member function tryMention() on a non-object in /home/***/***/***/vendor/longman/telegram-bot/src/Commands/SystemCommands/NewchatmemberCommand.php on line 42

Call to a member function getQuery()

Call to a member function getId()

**Comment by noplanman** [comment]
When does this error happen / what action you do triggers it?

Also, could you post the raw update string for us to see?

**Comment by ahora007** [comment]
after in start bot this error happen 

any type Actions do tiggers ..

**Comment by noplanman** [comment]
Do you have the latest version 0.35?

**Comment by ahora007** [comment]
yes

**Comment by noplanman** [comment]
Could you please activate the [raw update log](https://github.com/akalongman/php-telegram-bot/blob/0.35/doc/01-utils.md#raw-data) and then post the raw update(s)?

That way we can see why the error is happening. At the moment, it seems like Telegram is sending an incomplete update.

**Comment by MBoretto** [comment]
closing here fell free to reopen
