### ISSUE TITLE
not show list commands Admin

### ISSUE THREAD

**Issue by ahora007** [akalongman/php-telegram-bot#276]
i'm use $command->isAdminCommand() in help command but nothing show in list 

or !$command->isSystemCommand() && $command->isEnabled() not show list commands Admin 

however set  $telegram->enableAdmin(['123456']); for Admin in file hook.php

**Comment by noplanman** [comment]
Your admin ID should be set as an integer, not string!
```php
 $telegram->enableAdmin(123456);
```

**Comment by ahora007** [comment]
thanx

**Comment by noplanman** [comment]
You're welcome.

Just a reminder to check the readme first 😉
