### ISSUE TITLE
Move tests into a sub namespace of TelegramBot

### ISSUE THREAD

**Issue by noplanman** [akalongman/php-telegram-bot#284]
Having looked at many other libraries and learning more about unit testing, I think it would make sense to move the tests into a dedicated sub namespace of the TelegramBot namespace, namely: `Longman\TelegramBot\Tests`.
The folder structure would then become: `tests/TelegramBot/Tests`

This would make the test structure cleaner and more obvious.

What do you guys think?
@akalongman @MBoretto @jacklul

**Comment by akalongman** [comment]
Go ahead
