### ISSUE TITLE
Get updates from the channel

### ISSUE THREAD

**Issue by rutrader** [akalongman/php-telegram-bot#295]
### Required Information

- PHP version: php 7.0
- PHP Telegram Bot version: 0.35
- Using MySQL database: yes
- Update Method: getUpdates
- Self-signed certificate: no
- RAW update (if available):

Hi

I've created new channel, added my bot to this channel as administrator. How can I get all messages from all users in this channel? Can I do this?

**Comment by jacklul** [comment]
No.

**Comment by tchibomann** [comment]
Nope, this is (currently) not possible. The bot can only receive messages starting with a slash or if you mention the bot. And this is only possible if you enable this option via @botfather with /setprivacy.

**Comment by rutrader** [comment]
Well...this is sad, but thanks.
