### ISSUE TITLE
how to get any message when send by user

### ISSUE THREAD

**Issue by pooya-az** [akalongman/php-telegram-bot#299]
Hi,

### first question

I want when user send message (without /commands) like:
> test test1 test2

then handle this message.

-

I just find handle message when user send like
> /name test

**Comment by noplanman** [comment]
The command you need to override is [`GenericmessageCommand`](https://github.com/akalongman/php-telegram-bot/blob/0.35/src/Commands/SystemCommands/GenericmessageCommand.php)

In the `execute` method you can then get the text and do with it what you want 👍

**Comment by pooya-az** [comment]
Sry i change file [https://github.com/akalongman/php-telegram-bot/blob/0.35/src/Commands/SystemCommands/GenericmessageCommand.php](url)`

`return Request::emptyResponse();` 

to return 

` Request::sendMessage($data);` 

but can't get message without '/'

**Comment by noplanman** [comment]
This example `execute` method in `GenericmessageCommand` will simply return the entered text (which you can get with `$this->getMessage()->getText();`):
```php
public function execute()
{
    $message = $this->getMessage();

    return Request::sendMessage([
        'chat_id' => $message->getChat()->getId(),
        'text'    => $message->getText(),
    ]);
}
```

**Comment by pooya-az** [comment]
sry dude, but nothing change.

should change any file like hook.php or ...

-

my GenericmessageCommand file:
```<?php
namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Conversation;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\Commands\SystemCommand;

class GenericmessageCommand extends SystemCommand
{
    protected $name = 'Genericmessage';
    protected $description = 'Handle generic message';
    protected $version = '1.0.2';
    protected $need_mysql = true;

    public function executeNoDb()
    {
        //Do nothing
        return Request::emptyResponse();
    }

    public function execute()
    {
        $message = $this->getMessage();

        return Request::sendMessage([
            'chat_id' => $message->getChat()->getId(),
            'text'    => $message->getText(),
        ]);
    }
}

**Comment by jacklul** [comment]
Probably not using DB...?

**Comment by pooya-az** [comment]
ty @jacklul

I not using Db. 

ty very much

**Comment by noplanman** [comment]
@pooya-az Is it working now? What did you change to make it work?

**Comment by pooya-az** [comment]
I add your code in executeNoDb() because $need_mysql is true value

**Comment by noplanman** [comment]
Hmm, `executeNoDb` gets executed when there is no MySQL connection available.

If you don't use the MySQL database, just set `$mysql` to false.

Glad to see that it's working for you 👍

**Comment by pooya-az** [comment]
ty very much for answer my issue. 
@noplanman
