### ISSUE TITLE
How to create poll keyboard

### ISSUE THREAD

**Issue by mellat** [akalongman/php-telegram-bot#300]
### Required Information

- PHP version: 7
- PHP Telegram Bot version: Last version
- Using MySQL database: yes 
- Update Method: getUpdates
- Self-signed certificate: no

I want to have keyboard with default action than sending itself text ,
for example in a poll keyboard , we should show a text and send only the choose of user to moderate , not all of button text .

example : 
https://core.telegram.org/file/811140184/1/5YJxx-rostA/ad3f74094485fb97bd

thanks in advance

**Comment by noplanman** [comment]
Hi @mellat 

Not quite sure I understand exactly what you want.
The example that you linked, will print the entire button text when it is pressed.

Could you maybe explain what you would like in more detail with examples please?

Also, as far as I'm aware PHP version 5.7 was declined, so I'm not sure what version you're on. Did you mean PHP 7?

**Comment by mellat** [comment]
I want to send a value (like ID) when a button clicked .

example : 
`
                    $keyboard = [[
                                        'category1' => 2 ,
                                        'category2' => 4
                    ]];

                    $reply_keyboard_markup = new ReplyKeyboardMarkup(
                        [
                            'keyboard' => $keyboard ,
                            'resize_keyboard' => true,
                            'one_time_keyboard' => true,
                            'selective' => true
                        ]
                    );
`

Note : This code in incorrect and I just write it to say what I want.

**Comment by noplanman** [comment]
Unfortunately that does not work with normal buttons.
Passing a different value than what's on the button only works for [`InlineKeyboardButtons`](https://core.telegram.org/bots/api#inlinekeyboardbutton) using `callback_data`.

Hope this helps somehow 😕

**Comment by mellat** [comment]
I use genericMessageCommnet and handle buttons text as input .
thank you @noplanman
