### ISSUE TITLE
Refactoring HTTP requests

### ISSUE THREAD

**Issue by akalongman** [akalongman/php-telegram-bot#301]
Use Guzzle for HTTP requests

**Comment by jmauerhan** [comment]
I'd be interested in working on this, I use Guzzle on a lot of my projects and am familiar with it - do you have more info on where you want to implement it? What are you currently using?

**Comment by EagleEyeTiger** [comment]
I can help as well. I use guzzle quite frequently

**Comment by akalongman** [comment]
Sorry guys, seems like this feature already implemented. Please look to the issues https://github.com/akalongman/php-telegram-bot/issues/302 https://github.com/akalongman/php-telegram-bot/issues/232
