### ISSUE TITLE
Problem with set.php 

### ISSUE THREAD

**Issue by KilluaFein** [akalongman/php-telegram-bot#305]
### Required Information

- PHP version: 5.5.9
- PHP Telegram Bot version: latest I think
- Using MySQL database: no
- Update Method: Webhook 
- Self-signed certificate: yes 

### Actual behaviour
> What IS happening?
when I open set.php on my browser he return http error 500, but the webhook is correctly set.

I've tried to add 
`$result = Longman\TelegramBot\Request::sendMessage(['chat_id' => 'myid', 'text' => 'sample message']);
	//echo json_encode($result);`
after 
`$telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);`
and the message is correcly sent.

the apache error.log say:

`PHP Fatal error: Call to a member function isOk() on a non-object in /var/www/html/set.php on line 21`
![image](https://cloud.githubusercontent.com/assets/2939509/18998946/23fbae96-873b-11e6-92ac-2ec2453647d4.png)

Then, if I broswe directly to hook.php he return
`exception 'Longman\TelegramBot\Exception\TelegramException' with message 'Input is empty!' in /var/www/html/phptelebot/vendor/longman/telegram-bot/src/Telegram.php:252 Stack trace: #0 /var/www/html/hook.php(52): Longman\TelegramBot\Telegram->handle() #1 {main}`

What can I try to make it work? Thank you

**Comment by MBoretto** [comment]
The code is fine.
I don't understand why you get 500. Could be that the telegram server are in down did you check it?
Then input is empty is correct because with your browser you are not sending a json payload

**Comment by KilluaFein** [comment]
Is it possible that my server miss something? Is an ubuntu 14 set by me on cloudatcost, what can I check?

**Comment by noplanman** [comment]
I see you are using a custom certificate.
Are the permissions for the certificate file correct? It must be readable by the Apache user, probably `www-data`.

**Comment by KilluaFein** [comment]
I know becouse if I browse to https://api.telegram.org/botMYAPI/getUpdates I get `{"ok":false,"error_code":409,"description":"Conflict: can't use getUpdates method while webhook is active"}`

about the custom certificate, I tried to set www-data as group, but nothing changes, che error is still on line 21

**Comment by KilluaFein** [comment]
well, figured out the errors:
first, I had an old version of longman telegram-bot (don't know why, did a composer update couple times).
Then, I was trying to use as webhook www.domain.com/hook.php, but my certificate was for domain.com ... yes i feel so stupid. Thank you all

**Comment by noplanman** [comment]
Great that you figured it out and that it's working now 🎉
