### ISSUE TITLE
How to display multiselect or checkboxes

### ISSUE THREAD

**Issue by edwinmugendi** [akalongman/php-telegram-bot#307]
How does one handle multi-select or checkboxes

Something like this http://www.w3schools.com/html/tryit.asp?filename=tryhtml_checkbox

Thanks in advance

**Comment by noplanman** [comment]
Telegram bots only support buttons so far. Haven't heard of any plans to include checkboxes or multi-selects in the near future, but who knows.

What is your use-case? Maybe it can be handled with an InlineKeyboard?

**Comment by jacklul** [comment]
I had a simple solution in one of my bots:
Inline Keyboard + putting ✔ next to value when user selected it (another click unchecked it)

**Comment by edwinmugendi** [comment]
Thanks for your response @noplanman. The use case is being about the have users make more than on selections.

Thank you too @jacklul for your response. Is it possible to share the code for this.

**Comment by jacklul** [comment]
Small snippet from my code, hope it can show you the right direction!

```php
foreach ($items as $item) {
	array_push(
		$tmp_array,
		new InlineKeyboardButton(
			[
				'text' => (($this->isSelected($item['id'])) ? '✔ ' : ' ') . $item['name'],
				'callback_data' => $item['id']
			]
		)
	);
}
```
Callback queries are used to grab what item user clicked and update all the items, basically you can have an array with all the times and values true or false for them, when the command receives callback data (item id in it) it swaps the value (true->false or false=>true) and updates the inline keyboard.

**Comment by MBoretto** [comment]
Why don't add this in the wiki?

**Comment by nesttle** [comment]
Can't find a noob-example to achieve this, command `/callbackquery` is not working for me, and want to make a checklist like OP (thanks @jacklul, have a working example for something like https://github.com/akalongman/php-telegram-bot/issues/182#issuecomment-218896824 ?)

**Comment by jacklul** [comment]
https://github.com/jacklul/inlinegamesbot/blob/master/src/Commands/User/WaitinglistCommand.php somewhere around lines 250, also check callbackquerycommand in the same repo.

**Comment by abolfazlmohajeri** [comment]
@jacklul May have all your multyselect code with inlinekeyboard pls?

**Comment by sharkydog** [comment]
Check this
https://github.com/sharkydog/telegram-bot-test/blob/master/commands/SelectCommand.php
You will also need this
https://github.com/sharkydog/telegram-bot-test/blob/master/commands/CallbackqueryCommand.php

**Comment by abolfazlmohajeri** [comment]
tnx

**Comment by bsab** [comment]
1. Build a menu with buttons using InlineKeyboardButton
`button_list = [
    InlineKeyboardButton("col1", callback_data=...),
    InlineKeyboardButton("col2", callback_data=...),
    InlineKeyboardButton("row 2", callback_data=...)
]
reply_markup = InlineKeyboardMarkup(util.build_menu(button_list, n_cols=2))
bot.send_message(..., "A two-column menu", reply_markup=reply_markup)`

2. Fetch the messages sent to your Bot using the **getUpdates** (https://core.telegram.org/bots/api#getupdates)API method and select the message_id from the reply

3. Use the message_id and the method **edit_message_reply_markup** to edit the button menu with selected options :
```
button_list = [
    InlineKeyboardButton("col1*", callback_data=...),
    InlineKeyboardButton("col2", callback_data=...),
    InlineKeyboardButton("row 2*", callback_data=...)
]
reply_markup = InlineKeyboardMarkup(util.build_menu(button_list, n_cols=2))
bot.edit_message_reply_markup(chat_id=self.chat_id, message_id=message_id, reply_markup=reply_markup)

```

**Comment by Darskiy** [comment]
Please tell me a similar piece of python code

**Comment by noplanman** [comment]
@Darskiy This is a PHP library, you'll have to search elsewhere for Python.
