### ISSUE TITLE
Get Value Form Command

### ISSUE THREAD

**Issue by jafar-rezaei** [akalongman/php-telegram-bot#309]
How can I get value with a command , like : 
`/download_1234`
I want to catch download and 1234 as data .

thanks in advance

**Comment by dzarezenko** [comment]
Why not to use command with parameter like `/download 1234` ?

**Comment by jacklul** [comment]
He probably wants it to be clickable by the user.

Check GenericCommand.php, check ```$command = $message->getCommand();``` if it contains 'command_' if yes redirect it to download command ```return $this->telegram->executeCommand('download');```
in download command ```$command = $message->getCommand();``` then explode() it by '_', second value in array will be your '1234' id.

**Comment by noplanman** [comment]
@mellat I assume we can close here, yes?
