### ISSUE TITLE
Catchable fatal error - could not be converted to string

### ISSUE THREAD

**Issue by weiddolo** [akalongman/php-telegram-bot#31]
I've cloned and upload on my host the LAST VERSION (packagist v0.17.0), but if i run example-set.php on a host with php 5.4 and i will get this error:
<code>
Catchable fatal error: Object of class Longman\TelegramBot\Entities\ServerResponse could not be converted to string in /var/www/vhosts/XXXXXXXXXXX/XXXXXXXXXX/weiddolo/set.php on line 16</code>

**Comment by weiddolo** [comment]
If i will change <code>echo $telegram->setWebHook($url);</code> in <code>print_r($telegram->setWebHook($url));</code> and i get this:

<code>Longman\TelegramBot\Entities\ServerResponse Object ( [ok:protected] => 1 [result:protected] => 1 [error_code:protected] => [description:protected] => Webhook was set [bot_name:protected] => )</code>

Response is proteced. It's Normal?

**Comment by weiddolo** [comment]
anyone can help me?

**Comment by sanok** [comment]
You can try to set the Webhook manually using an url formed as this

https://api.telegram.org/bot12345:ABCDEFGHIJKL/setWebhook?url=https://yourdomain.com/path_to_bot_directory/hook.php

12345:ABCDEFGHIJKL is the token that FatherBot has created for your bot

**Comment by weiddolo** [comment]
After i have set manually the webhook, how do I check that the ALL works properly?

**Comment by sanok** [comment]
Using the telegram app, open a chat with your bot. After that, send the /help command, and you must see response and also something in botname.log and mysql database if enabled. If not, check your server logs.

**Comment by weiddolo** [comment]
The log file is not created. I have not set the bot with mysql, but I have enabled the log file in the setting in hook.php.

**Comment by MBoretto** [comment]
I've fix the error with setWebhook in 0.17.1 let me know if you still have problems.

**Comment by sanok** [comment]
Weiddolo if the file it's not created, check that your web server has granted permissions to write on the folder, if not, you can create the file and change ownership (I'm assuming that you are using an OS that this considerations matters)

**Comment by weiddolo** [comment]
@MBoretto now Webhook was set! How i can test if the bot works properly?

@sanok Thanks for your help, i have also checked the folder permissions.

**Comment by WISTFUL12** [comment]
When I use Webhook Method and visit set.php, I get "Webhook was set" but:
The bot doesn't reply
The log file is empty

I have server with self-signed certificate.
I don't know how can I upload my public key certificate according https://core.telegram.org/bots/api#setwebhook method.

When I use getUpdate Method and run "while true; do ./getUpdatesCLI.php; done", I get below error on my error log:
[17-Sep-2015 10:12:08] PHP Catchable fatal error:  Object of class Longman\TelegramBot\Entities\ServerResponse could not be converted to string in /home/***/***.com/php-telegram-bot-master/vendor/longman/telegram-bot/src/Request.php on line 80

**Comment by weiddolo** [comment]
@WISTFUL12 have you update with 0.17.1 versions?

**Comment by WISTFUL12** [comment]
Yes. I have installed fresh version on yesterday...

**Comment by MBoretto** [comment]
Try to disable logging i verified that it cause some problems

**Comment by weiddolo** [comment]
2015-09-17 17:35:54 - Fail fetch updates

**Comment by MBoretto** [comment]
Are you under Windows?

**Comment by weiddolo** [comment]
Dedicated Server Linux - Aruba

**Comment by WISTFUL12** [comment]
@MBoretto :+1: 
https://github.com/akalongman/php-telegram-bot/issues/35#issuecomment-141195216

**Comment by weiddolo** [comment]
My getUpdatesCLI.php is like this: 

![senza-titolo-1](https://cloud.githubusercontent.com/assets/10815675/9954546/41d22e8e-5dea-11e5-8edb-6068af2305f4.png)

It's Ok?

**Comment by weiddolo** [comment]
My getUpdatesCLI.php is like this, it's ok?

![senza-titolo-1](https://cloud.githubusercontent.com/assets/10815675/9954603/bae236b6-5dea-11e5-841b-c7fcef03c0de.png)
