### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to Longman\TelegramBot\DB::insertUser()

### ISSUE THREAD

**Issue by nullcookies** [akalongman/php-telegram-bot#312]
**posting in Channel and callback**

code good - http://pastebin.com/E6SmuZ7w 
result - 
![res](https://cloud.githubusercontent.com/assets/20815917/19211325/63ce410c-8d29-11e6-87f2-70746b62a924.png)

pressed button - callback  > an error  `Fatal error: Uncaught TypeError: Argument 1 passed to Longman\TelegramBot\DB::insertUser() must be an instance of Longman\TelegramBot\Entities\User, null given, called in \src\DB.php on line 686 and defined in \src\DB.php on line 317` 
![res2](https://cloud.githubusercontent.com/assets/20815917/19211385/772da48a-8d2a-11e6-9a20-a3fca464ae7f.png)

please fix?

**Comment by MBoretto** [comment]
Hello, that's why in channels user field is not specified right? is a bug

**Comment by jacklul** [comment]
My PR should fix it

**Comment by noplanman** [comment]
@nullcookies This still a problem? Should be fixed
