### ISSUE TITLE
How can I set icons and custom text to the buttons on Replay Keyboard?

### ISSUE THREAD

**Issue by dzarezenko** [akalongman/php-telegram-bot#316]
I have investigated all Issues and Wiki, but I haven't found how to create custom buttons with icons. Where can I look on example or some docs?

**Comment by jacklul** [comment]
Use emojis in text fields, those are 'images'.

**Comment by dzarezenko** [comment]
Thanks! And can I create buttons with some text, but on click execute some command? Or should I compare button text in code with some constant and execute some functionality?

**Comment by jacklul** [comment]
### ReplyKeyboard
_keyboard that can be opened/closed_
on click can send only text to the chat or request_contact/request_location actions

### InlineKeyboard
_keyboard under a particular message_
can send url, **callback data (callbackquery)** or switch user to inline mode

Bolded text is probably what you want.

**Comment by dzarezenko** [comment]
Thanks!
