### ISSUE TITLE
Send message to multiple users and sending restrictions

### ISSUE THREAD

**Issue by dzarezenko** [akalongman/php-telegram-bot#317]
I have a few conceptual questions:
1. How can I send some message to multiple users with Telegram IDs list.
2. How many `sendMessage()` calls in a loop can I perform in some time period (for one script run for example)? Is there some restrictions from Telegram?
3. What is the better way to send mass messages, make this in a loop for every user separately or send at one time with multiple sending command (from q.1)? And what restrictions for number of users in case of multiple sending?

**Comment by jacklul** [comment]
Do not send more than 30 per second.

Do not use build in function for mass sending, write own command and function for this that will check if you're not sending too many in one second.

**Comment by natanrufino** [comment]
> I have a few conceptual questions:
> 
> 1. How can I send some message to multiple users with Telegram IDs list.
> 2. How many `sendMessage()` calls in a loop can I perform in some time period (for one script run for example)? Is there some restrictions from Telegram?
> 3. What is the better way to send mass messages, make this in a loop for every user separately or send at one time with multiple sending command (from q.1)? And what restrictions for number of users in case of multiple sending?

Hey brother! Have you ever found out the solution for your questions? Would you likke to share some insights? Thanks!!

**Comment by dzarezenko** [comment]
Hi, @natanrufino 
1. Telegram doesn't support mass-sending ([How can I message all of my bot's subscribers at once?](https://core.telegram.org/bots/faq#how-can-i-message-all-of-my-bot-39s-subscribers-at-once))
2. For Bots, there is a hard limit of 30 messages / second and 1 message per second to each user ([My bot is hitting limits, how do I avoid this?](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this))
3. In my case I have created queue mechanism to control messages sending, so I can set how many messages send in some period of time.

**Comment by jacklul** [comment]
Queue software like Rabbitmq is useful for mass sending

**Comment by natanrufino** [comment]
> Queue software like Rabbitmq is useful for mass sending.
> It allows you to retry failed deliveries or drop them in specific cases (bot blocked by user etc).
> You could have a separated queue for each distinct chat_id with configuration that fetches one message (and sending it) from the queue per second.

Thank you for the help. Is this Rabbitmq a free app or something like that? I'll take a look on it. I also thinking about using "Cron" to schedule the sending of messages... thanks

**Comment by natanrufino** [comment]
> Hi, @natanrufino
> 
> 1. Telegram doesn't support mass-sending ([How can I message all of my bot's subscribers at once?](https://core.telegram.org/bots/faq#how-can-i-message-all-of-my-bot-39s-subscribers-at-once))
> 2. For Bots, there is a hard limit of 30 messages / second and 1 message per second to each user ([My bot is hitting limits, how do I avoid this?](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this))
> 3. In my case I have created queue mechanism to control messages sending, so I can set how many messages send in some period of time.

Yes brother, I know that. Could you share your solution with me? this part: _"In my case I have created queue mechanism to control messages sending, so I can set how many messages send in some period of time."_. I have done something to avoid the limitations but I am not happy with it. When I send the comand /msg inside the bo it will send a message to 23 users and stop; so, I send the comand again and  the bot will send the same messge to other more 23 users, and so on and so forth... 
Thanks for the answer!!
