### ISSUE TITLE
How to respond to a file?

### ISSUE THREAD

**Issue by sprnza** [akalongman/php-telegram-bot#318]
Hi there!
Is there any way to respond to a file that was forwarded from another chat in order to move it to a particular folder? I.e. in case *.doc file has been recieved respond with "moved to the Docs folder!"

Thank you!!

**Comment by jacklul** [comment]
GenericMessagecommand, simply check if message contains attached file and work with that. 

To get file name:
```php
$message->getDocument()->getFileName();
```
I think this will do. 

Remember to check with getDocument earlier otherwise you will get 'not an object' errors for messages without file.

**Comment by sprnza** [comment]
Thank you @jacklul !
