### ISSUE TITLE
using @Bot_Name

### ISSUE THREAD

**Issue by ufhy** [akalongman/php-telegram-bot#319]
how can I use the format command like:
```
/help@Bot_Name
```

**Comment by jacklul** [comment]
Every "/command" in message posted by bot is automatically converted to /command@botname in groups.

You could always define a constant in hook file with bot username and simply add it in your command's output.

**Comment by ufhy** [comment]
when i using "/command@botname". bot not reply

**Comment by jacklul** [comment]
you must set your bot's username in hook file:
```php
$API_KEY = 'your_bot_api_key';
$BOT_NAME = 'username_bot';
```
without "@".

**Comment by ufhy** [comment]
oh. my bad.. 
i'm not using username bot but i using bot name.
