### ISSUE TITLE
Looking for some help

### ISSUE THREAD

**Issue by CapraTheBest** [akalongman/php-telegram-bot#32]
I just started looking into telegram bots and I've found this really nice repo with a lot of interesting stuff. I tried to follow the instructions to install it, but I fail somewhere (I've never installed a php application actually, so I was just shooting in the dark), so I'm asking if someone could help me to get the bot working please.

I'm struck at the point where I pull the whole repo in my computer and I do "php composer.phar install". Now I'm stuck. 
How can I start the php server?

**Comment by camagenta** [comment]
Do you have local server like xampp or wampp? You should start one of them.

maybe you should watch this : https://www.youtube.com/watch?v=lVcTqkHtNMg

or just googling about running local server using xampp / wampp

**Comment by CapraTheBest** [comment]
... I forgot to move everything in the xampp folder... I feel so dumb. Thanks @camagenta

**Comment by camagenta** [comment]
yes. you're welcom @CapraTheBest
