### ISSUE TITLE
Hi, a question Admin Commands

### ISSUE THREAD

**Issue by Telegramsrv** [akalongman/php-telegram-bot#320]
### How to hide the list /help of Admin commands?

```php
class WhoisCommand extends AdminCommand
{
    protected $name = 'whois';
    protected $description = 'Lookup user or group info';
    protected $usage = '/whois <id> or /whois <search string>';
    protected $version = '1.1.0';
    protected $need_mysql = true;

    protected $enabled = true; //?
    protected $public = false; //?
```

**Comment by noplanman** [comment]
Not sure I understand your question.

Would you like to hide all admin commands from the `/help` command?
Or just a specific command?

**Comment by Telegramsrv** [comment]
before the flag was protected $public = false; // Remove the team visibility

for admin commands not working

**Comment by Telegramsrv** [comment]
if (!$command->isEnabled()) {
                        continue;
                    }
                    if (!$command->isPublic()) { //?
                        continue;
                    }

**Comment by noplanman** [comment]
Now the class you're extending defines if it's a public user (`UserCommand`) or admin (`AdminCommand`) command.
The `$public` variable has no effect any more.

It would really help if you could explain in more detail what you would like to achieve :wink:

**Comment by Telegramsrv** [comment]
I wanted the team to the administrator, which are displayed via /help 
hide and show, but that they worked
