### ISSUE TITLE
Turn off default commands

### ISSUE THREAD

**Issue by tobsn** [akalongman/php-telegram-bot#321]
is it somehow possible to disable the src/Commands ?

**Comment by jacklul** [comment]
https://github.com/akalongman/php-telegram-bot/issues/183#issuecomment-219239372

**Comment by tobsn** [comment]
well the remove files comment is kinda nonsense... since its a composer install...

**Comment by jacklul** [comment]
You can remove when you're not using composer for install, some people simply sync repository to theirs keeping removed files removed. For composer users you just have to create dummy commands in your custom commands directory.

**Comment by tobsn** [comment]
@jacklul but why wouldn't they be just in the example folder?

**Comment by jacklul** [comment]
Well... that's a good question... some of them are core functionality though.

summoning @akalongman @MBoretto @noplanman

**Comment by noplanman** [comment]
> that's a good question

Yep, sure is. I guess this library started as a base for developing a Telegram Bot in PHP, but it has now evolved into something much more.

As a part of #231 (and #232) we should take this into account, to keep the library itself as skeletal as possible and offer the preset commands as examples.

I think @MBoretto has started to look into this a bit.
