### ISSUE TITLE
Top command?

### ISSUE THREAD

**Issue by Telegramsrv** [akalongman/php-telegram-bot#322]
Hi, how to count the number of used the command?

**Comment by Telegramsrv** [comment]
Top list use command?

**Comment by MBoretto** [comment]
Why don' t you use the botan service? You  can also use the database and count the rows

**Comment by nullcookies** [comment]
https://github.com/akalongman/php-telegram-bot/pull/238#issuecomment-230151347 ?

**Comment by Telegramsrv** [comment]
Thanks, I will use botan service.
