### ISSUE TITLE
Custom keyboard in group

### ISSUE THREAD

**Issue by sprnza** [akalongman/php-telegram-bot#324]
Hi guys!
Could you please check if custom keyboard in a group chat still works? I's stopped working at some moment for some reason for me. I use this config to call it:
`
	$reply_keyboard_markup = new ReplyKeyboardMarkup(
			[
				'keyboard' => $keyboard,
				'resize_keyboard' => false,
				'one_time_keyboard' => true,
				'selective' => true
			]
`
I've tried to set selective to false to test and it still doesn't show up. But (!) it works fine in direct chat (non group) though.

**Comment by noplanman** [comment]
When using `'selective' => true`, be sure to add the `reply_to_message_id` to the message data.

Also, what client are you using? I've seen issues with the keyboards on some clients, be sure to update it/them.

Apart from that, I'm not sure what to say. Could you maybe add more context?

I assume you're on version 0.35, yes?

**Comment by sprnza** [comment]
Cool! Thank you! Adding `reply_to_message_id` solved my issue. But I needed to add it to /cancel command either to have it hiding the keyboard properly.

**Comment by noplanman** [comment]
Wow, thanks for pointing that out. Will be fixing that 👍
