### ISSUE TITLE
Overwriting System commands

### ISSUE THREAD

**Issue by tchibomann** [akalongman/php-telegram-bot#330]
Sorry, did press enter too fast -.-

I have another question. I want to use inline-buttons with a callback action, this is done in SystemCommands\CallbackqueryCommand.php, but this is a package file which will be overwritten if I update via composer, am I right?

How do i overwrite this system commands?

Many thanks! :)

**Comment by jacklul** [comment]
``` $telegram->addCommandsPath('commands/);``` in hook script.
you just copy CallbackqueryCommand.php there and edit, that's how ur supposed to develop your bot.

**Comment by tchibomann** [comment]
Oh my. Why didn't I... 

Okay, forgot my question, I'm a fool. Thanks very much! 👍
