### ISSUE TITLE
Troubles after Telegram update on November 21, 2016

### ISSUE THREAD

**Issue by deios0** [akalongman/php-telegram-bot#332]
Hi guys, we got troubles after last Telegram update with this:
> Your bot will now get updates about posts in channels. Added new fields channel_post and edited_channel_post to Update.

Here is an exception we were getting after update:
`[2016-11-23 23:59:59] prod.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getFrom() on null in /app/Services/TelegramCommands/SystemCommands/GenericmessageCommand.php:49`

We fixed it with the following code, could you please add fixes to repository?

`public function messenger()
{
if (array_key_exists("edited_channel_post", \Illuminate\Support\Facades\Input::get())) return;
if (array_key_exists("channel_post", \Illuminate\Support\Facades\Input::get())) return;
$this->api->handle();
}`

**Comment by jacklul** [comment]
It's because of the latest API update, will be fixed

Look here https://github.com/akalongman/php-telegram-bot/pull/333 for commit with a fix

**Comment by deios0** [comment]
Thanks!
