### ISSUE TITLE
PHP Fatal error:  Class 'Longman\TelegramBot\Entities\ReplyKeyboardMarkup' not found

### ISSUE THREAD

**Issue by dzarezenko** [akalongman/php-telegram-bot#335]
Hi,

I have received "PHP Fatal error:  Class 'Longman\TelegramBot\Entities\ReplyKeyboardMarkup' not found"
error after migration from v0.35 to v0.36. And now I can't find this class at all. How can I fix my code without serious refactoring?

**Comment by tchibomann** [comment]
I think you have to refactor. There is a new way to handle keyboards in telegram, think this is because some changes in the telegram api itself...

see:

https://github.com/akalongman/php-telegram-bot/blob/master/examples/Commands/KeyboardCommand.php

**Comment by noplanman** [comment]
Hi @dzarezenko 

0.36 has a lot of new code, especially concerning the Entities.

I've written a short wiki entry about [migrating from 0.35](https://github.com/akalongman/php-telegram-bot/wiki/Migrating-from-0.35).

It's not that exhaustive and it contains just the main changes, so you might run in to other errors as you refactor. It shouldn't be too crazy and you can check the example/predefined commands to see how the new Entites / InlineQuery / Keyboard / InputMessageContent classes are used.

If you need any further assistance, please write.
Also, feel free to adjust the wiki as you're refactoring 👍

**Comment by dzarezenko** [comment]
Thanks @noplanman 

I just replaced `Longman\TelegramBot\Entities\ReplyKeyboardMarkup` with `Longman\TelegramBot\Entities\Keyboard` and all works now.

**Comment by noplanman** [comment]
Ok 👍 

Just make sure to test all your custom commands, to be safe.
