### ISSUE TITLE
A bug in the commands in chat

### ISSUE THREAD

**Issue by Telegramsrv** [akalongman/php-telegram-bot#337]
### /help@bot_namebot

goes in > GenericmessageCommand.php 

but you must HelpCommand.php

**Comment by jacklul** [comment]
Did you set the bot's username in hook.php right? It must be exactly like the username (without @).

**Comment by Telegramsrv** [comment]
$BOT_NAME ? 
Yes set bot name (without @).

**Comment by Telegramsrv** [comment]
https://github.com/akalongman/php-telegram-bot/blob/be36bbbc3d565f1666f83c2c033301f9d91df18f/src/Entities/Message.php#L185

strtolower($this->bot_name) == ''

**Comment by chuv1** [comment]
Same here... Is there any way to trace this problem?

**Comment by chuv1** [comment]
Ok, solved it by setting default value of the bot name in 
`Message::__construct(array $data, $bot_name = 'my_bot_name');`

**Comment by noplanman** [comment]
Ok, I think we should take the step to make the `$bot_name` static in the `Telegram` class.

As much as I don't like the idea, it's a lot better than passing the variable around everywhere...

@akalongman @jacklul @MBoretto 
What do you think? Until we find a better solution.

**Comment by chuv1** [comment]
@noplanman but why don't you like that idea?

**Comment by noplanman** [comment]
Having things static really limits the library's functionality.

If for example, at some point, you would like 2 bots in parallel, sharing information and executing side-by-side, it's just not possible, because the variable is static.

Same thing applies to the logger and DB at the moment, but it would be nice to allow more flexible/dynamic setups.

**Comment by fenghuilee** [comment]
if (strtolower($split_cmd[1]) === strtolower($this->bot_name))

that is not Attributes bot_name in Class Message or Entity

**Comment by Telegramsrv** [comment]
@noplanman thanks, good work!
