### ISSUE TITLE
Adding custom commands

### ISSUE THREAD

**Issue by PatrickePatate** [akalongman/php-telegram-bot#338]
Hello !
I am a bit nil, especially since I do not work very much with this kind of system, so I would like to know:
Where do I add this to add my custom commands ?

_$commands_folder = __DIR__ . '/Commands/';
$telegram->addCommandsPath($commands_folder);_

Thanks for your help.

**Comment by PatrickePatate** [comment]
I find this : 
https://github.com/akalongman/php-telegram-bot/wiki/Create-your-own-commands

But that doesn't work :((

This is my hook file :
```
<?php
// Load composer
require __DIR__ . '/vendor/autoload.php';

$API_KEY = '253936959:AAFQ0dnDs0nULnnoxPS2J1_sVHnHUZGIFuI';
$BOT_NAME = 'CyanidBot';
$commands_path = __DIR__ . '/commands/';
try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);

    // ADD COMMANDS
    $commands_path = '/home/Patricke/web/bot.cyanid.fr/public_html/vendor/longman/commands/';
    $telegram->addCommandsPath($commands_path);

    // Handle telegram webhook request
    $telegram->handle();
} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    // Silence is golden!
    // log telegram errors
    // echo $e;
}
?>
```

**Comment by noplanman** [comment]
@PatrickePatate Did you get it to work then?

I've edited your code above as you had your API key and bot name in it. Please remember to remove the API key when posting code, as that would allow anybody to alter your bot!

For this reason, I highly recommend you reset that ID to ensure your bot is safe:
https://core.telegram.org/bots#generating-an-authorization-token
