### ISSUE TITLE
Create wiki entry regarding "Bot Security"

### ISSUE THREAD

**Issue by noplanman** [akalongman/php-telegram-bot#339]
It would make sense to create an entry explaining how to secure a bot to prevent easy direct access to the `set.php`, `unset.php` and `hook.php` files.

Namely the following:
- [x] Put these files in a secret subfolder.
- [x] Rename them.
- [x] Add some special secret parameter.
- [x] Limit access to Telegram API IPs.
- [x] Anything else that helps...

Wiki entry: https://github.com/akalongman/php-telegram-bot/wiki/Securing-&-Hardening-your-Telegram-Bot

**Comment by jacklul** [comment]
There is htaccess possibility to allow only Telegram API IPs to make POST requests. 
Bot developer must know which API server is querying them, there are multiple IPs, we shouldn't list them, only give a hint about checking the logs.

**Comment by jacklul** [comment]
It wasn't working very well on my webhost so for now Im just using secret query string.

**Comment by noplanman** [comment]
IPs are listed here: https://core.telegram.org/bots/webhooks#the-short-version

Secret query string is a nice solution too. I'm using that for the [Telegram Bot Manager](https://github.com/noplanman/php-telegram-bot-manager/)

**Comment by noplanman** [comment]
Ok, have finished an initial write-up here:
https://github.com/akalongman/php-telegram-bot/wiki/Securing-&-Hardening-your-Telegram-Bot

**Comment by noplanman** [comment]
Any extra comments on this?
Maybe other things to consider?

Otherwise I'll close this off here.
