### ISSUE TITLE
Extend mysql access to custom commands

### ISSUE THREAD

**Issue by sanok** [akalongman/php-telegram-bot#34]
Good morning!

I'm testing the code, trying to implement a command that uses mysql as storage.

I've seen that on a recent update of the source now the pdo variable it's inside a new DB class... but I cannot figure out how to use the class to make custom queries to the database...

Can anyone help me please?

Thanks in advance, Sergio

**Comment by MBoretto** [comment]
Thanks for reporting, the idea is to have all the queries inside DB.php so you can make your own extending the DB class and creating new methods.
Anyway in 0.17.1 I've reintroduced the pdo var in Telegram.php.

**Comment by sanok** [comment]
Hi, thank you for the update. Maybe it would be better remove the pdo var in Telegram and implement some mecanism inside DB.php, if you can provide a quick example it would be a great starting point, I think.

**Comment by MBoretto** [comment]
You can inspire from the ConversationDB.php Class
