### ISSUE TITLE
botan.io integration

### ISSUE THREAD

**Issue by novia713** [akalongman/php-telegram-bot#341]
### Required Information

- PHP version: 7.0
- PHP Telegram Bot version: 0.35
- Using MySQL database: yes 
- Update Method: getUpdates
- Self-signed certificate: no

### Expected behaviour
botan.io bot should show some info on my statistics bot

### Actual behaviour
besides i have 
`$telegram->enableBotan('abcde');`
botan.io bot doesn't show any info

### Steps to reproduce
put personal token at `enableBotan()` method

### Extra details
which level of log should i use to see if there is a problem?

**Comment by noplanman** [comment]
@jacklul Would appreciate your input, as I've only used botan for some simple tests.

**Comment by jacklul** [comment]
I don't think Botan integration was even updated to use monolog

**Comment by noplanman** [comment]
@jacklul Thanks for the quick fix!

@novia713 For the moment follow the comment above.
Correct logging output will be in the next version 👍

**Comment by noplanman** [comment]
@novia713 Is this solved for you? Did you try out version 0.37?

**Comment by novia713** [comment]
yes, i've tried 0.37.0 with these lines on my `getUpdatesCLI.php`
```php
ini_set('log_errors', 1);
ini_set('error_log', 'error.log');
```

but i can't find any `error.log` file on my system :-(

**Comment by noplanman** [comment]
Have you set the [`TelegramLog`](https://github.com/akalongman/php-telegram-bot/blob/0.37.0/examples/getUpdatesCLI.php#L34) log files?

There's no need for the lines you posted above, as @jacklul has fixed that in 0.37.0.

**Comment by novia713** [comment]
i did as you said, and it doesn't generate any `error.log`
which is very natural because my bot never throw an error,
it simply ignores the Botan topic

i can see a `debug.log` but it hasn't any Botan related info

**Comment by noplanman** [comment]
Could you post your `getUpdatesCLI.php` file please?
Remember to remove your API key!

**Comment by jacklul** [comment]
Maybe there is issue on Botan's end, tried regenerating Botany token?

**Comment by novia713** [comment]
here you are, @noplanman 
http://sprunge.us/MUGK

passwords and tokens have been edited for my safety :)

**Comment by noplanman** [comment]
Config looks good.
My botan metrics are working, so I don't think it's a botan problem.

Have you tried @jacklul's suggestion of regenerating the botan token?

So that I understand you correctly: When you chat with the botan bot and request statistics, the image you get back is empty, correct? (Assuming you've waited a bit for botan to process)

**Comment by novia713** [comment]
yes, you undestood well @noplanman 

seems there is a problem for Botan with my bot's name
it doesn't allow me to re-register it (again) 

![seleccion_109](https://cloud.githubusercontent.com/assets/423279/21258251/6b8a9ace-c37c-11e6-87e5-fc938f643643.png)


i will look into Botan system further later
i consider it's a Botan problem too

**Comment by noplanman** [comment]
Have you deleted it first though? You probably can't use that name because it already exists.

Alternatively, you could choose "Resend token" to make 100% sure that you have the correct one in your script.

**Comment by novia713** [comment]
deleted and re-registered again
i had checked the token with "resend token", it was correct

i'm going to wait a couple of hours and see what happens at Botan stats ...

**Comment by noplanman** [comment]
Ok, hope it works out! Good luck 😃
