### ISSUE TITLE
"allowed_updates" while setting webHook

### ISSUE THREAD

**Issue by chuv1** [akalongman/php-telegram-bot#345]
Coudn't find "official" way to set "allowed_updates" parameter of [setWebhook](https://core.telegram.org/bots/api#setwebhook) function. 
Only possible way to edit Request.php, right?

**Comment by noplanman** [comment]
These new fields haven't been implemented yet! 😁 
So yes, you would have to modify the `Request.php` file for now.

**Comment by noplanman** [comment]
@chuv1 This is part of 0.38.0 👍
