### ISSUE TITLE
Can not recognise commands in a chat with multiple bot

### ISSUE THREAD

**Issue by fenghuilee** [akalongman/php-telegram-bot#347]
### Required Information

- PHP version:7.0
- PHP Telegram Bot version:latest
- Using MySQL database: yes
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

**Comment by noplanman** [comment]
This is related to #337, will continue the discussion there.

@fenghuilee If you feel this is a separate thing, please reopen and elaborate on the issue please.
