### ISSUE TITLE
non-ok replies from Telegram API stops execution

### ISSUE THREAD

**Issue by jacklul** [akalongman/php-telegram-bot#354]
*I could swear I mentioned this already...*

Basically all fail replies from Telegram throw an exception, this is very bad behavior.
This prevents usage of any mass messaging commands (like announcements), because when one of the users blocks the bot library will throw exception and stop.

```
exception 'Longman\TelegramBot\Exception\TelegramException' with message 'Client error: `POST https://api.telegram.org/bot123/editMessageText` resulted in a `400 Bad Request` response:
{"ok":false,"error_code":400,"description":"Bot was blocked by the user"}
```

This is seriously annoying and makes 

```php
$result = Request::sendMessage($data)
````
useless because any fail will stop the execution, so the developer can't properly react to failures.

Can we have this fixed? This must have something to do with Guzzle and I wasn't been able to figure it out.

**Comment by noplanman** [comment]
Yes, I remember you mentioning this at some point.
I'll look into this too 👍

**Comment by jacklul** [comment]
BTW: Seems like it doesn't happen now! (on latest dev)

**Comment by noplanman** [comment]
Yes, a test would be great, because I haven't actively changed anything to fix this...

**Comment by jacklul** [comment]
Tested it, it's fixed now! :thumbsup:

Maybe it was fixed at Guzzle's side?

**Comment by noplanman** [comment]
Possibly. If you feel like it, you could test different versions of Guzzle and see if the issue pops up at a certain version.

Anyway, if it happens again, just reopen here 😊
