### ISSUE TITLE
Is there any possibility to detect user's client? At least mobile/desktop version.

### ISSUE THREAD

**Issue by chuv1** [akalongman/php-telegram-bot#357]
For example not to show "Send my location" button in Reply keyboard on desktop client, since it's not supported, or use shorter sentences in replies on mobile?

**Comment by jacklul** [comment]
I don't think there is...

**Comment by noplanman** [comment]
Write a message to `@BotSupport` to ask and give them a feature request.

**Comment by chuv1** [comment]
Ok, I'll do. )
Thanks. )
