### ISSUE TITLE
Is it possible to send a message to a user given just the phone number or user name?

### ISSUE THREAD

**Issue by Nesh108** [akalongman/php-telegram-bot#36]
Hello,

I was playing around this (great) library and I noticed that most of the examples use the chat_id as the key for sending messages.

I was wondering if there was a way to send a message to a specific user given the phone number or the user name (knowing both would be awesome). Also, is there a way to initiate a secure chat with such a user?

Cheers and keep up the amazing job!

/Nesh

**Comment by MBoretto** [comment]
Telegram api don't provide users telephone number. 
Chat_id is equal to user_id in single chat with the bot.
Anyway if you know the user_id you can't contanct the user with the bot, the first interaction have to be human.

**Comment by Nesh108** [comment]
Ok, I see. Thanks!

**Comment by weiddolo** [comment]
@Nesh108 the script will work to you?

**Comment by Nesh108** [comment]
@weiddolo What do you mean?

**Comment by weiddolo** [comment]
The bot work? Responds to your requests in Telegram?

**Comment by Nesh108** [comment]
Yeah, it does. But I don't think this is the right place to discuss your problem. How about opening a new issue?

**Comment by weiddolo** [comment]
Yes, but I have not received replies :D
