### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by noplanman** [akalongman/php-telegram-bot#366]
Just a short issue to discuss a few style things.
I suggest we vote on these to agree on a certain style that we can all go by, to prevent to-and-fro overwrites of little things.

Following are just a few that have different variants in the codebase at the moment. Most things are already managed thanks to following PSR-2 guidelines, but some things need to be defined by us (or I haven't found the PSR-2 equivalent, in which case let me know please!)

(in these examples, I favour the first suggestions)

- Type cast spacing: `(int) $var` vs. `(int)$var`
- New line before `return` statements: 1 empty line vs. 0 empty lines
```php
    lastLineOfCode();

    return $something;
}
```
vs.
```php
    lastLineOfCode();
    return $something;
}
```
- Align variable assignments (also for arrays): yes vs. no
```php
$short        = 'short';
$a_bit_longer = 'a_bit_longer';
```
vs.
```php
$short = 'short';
$a_bit_longer = 'a_bit_longer';
```

*summoning @akalongman @MBoretto @jacklul*

**Comment by akalongman** [comment]
I am agree with all, except "Align variable assignments". I think align for arrays is good, but for variables - not.

**Comment by noplanman** [comment]
Ok 👍
Initially I would have liked it like that as well and looked for an option in PhpStorm and thought there was only 1 option for both alignments. Now I looked again and found both, one for each setting. So I'm more than happy to have arrays aligned and assignments not.

**Comment by jacklul** [comment]
First suggestions for first and second, for the last one both are fine so I'm neutral here.
