### ISSUE TITLE
How to get simple text message

### ISSUE THREAD

**Issue by mnameghi** [akalongman/php-telegram-bot#367]
How to get simple text message? such as text from custom button and etc.
They are not command.
I am using webhook method.

**Comment by chuv1** [comment]
Check **Commands/SystemCommands/GenericmessageCommand.php** you can handle it there.

**Comment by noplanman** [comment]
You can add a custom commands directory and copy the `src/Commands/SystemCommands/GenericmessageCommand.php` file into it.

Then you can handle each and every incoming message the way you want to!
The method you're interested is [`execute()`](https://github.com/akalongman/php-telegram-bot/blob/0.38.1/src/Commands/SystemCommands/GenericmessageCommand.php#L59).

**Comment by mnameghi** [comment]
Thanks
Maybe It is better to write it on wiki pages.
