### ISSUE TITLE
DB fatal error after forward photo to bot!

### ISSUE THREAD

**Issue by WISTFUL12** [akalongman/php-telegram-bot#37]
I forwarded one photo from a third person to my bot and now when I try to run "getUpdatesCLI.php", below error added on error log:

[18-Sep-2015 10:54:19] PHP Catchable fatal error:  Object of class Longman\TelegramBot\Entities\User could not be converted to string in /home/x/xxx.com/telegram/vendor/longman/telegram-bot/src/DB.php on line 230

**Comment by WISTFUL12** [comment]
I temporary edit DB.php on line 217 with "$forward_from = '123';" and run "getUpdatesCLI.php" again. Now problem temporary solved!

**Comment by WISTFUL12** [comment]
Also this issue occurred after forwarding text (no photo) to bot until do post 2 temp solution...

**Comment by MBoretto** [comment]
Thanks for reporting I push the fix on the branch hotfix.
