### ISSUE TITLE
Easier database access in commands

### ISSUE THREAD

**Issue by noplanman** [akalongman/php-telegram-bot#373]
I hope that the whole DB part will experience an upgrade at some point, but for the moment I really think we should allow the usage of the DB to be more open.

Basically, I'd suggest we implement a `getPdo()` method (name to be discussed) that returns the open PDO connection. This would make it a lot easier to just do stuff with the database in a custom command.

As I'm working on the [`/debug`](#363)  command at the moment, this would make life a lot easier.

@akalongman @MBoretto @jacklul 
What do you think?

**Comment by jacklul** [comment]
Yes! I had to use my own DBHelper class that had own query function and pdo getter.

**Comment by nesttle** [comment]
Can't figure out how to make custom calls to DB (I'm making a custom FileDB.php based on BotanDB.php, but not success). I'll do DB calls from scratch until I find a more elegant alternative

**Comment by jacklul** [comment]
@nesttle, what do you mean? 
You simply use `$pdo = DB::getPdo();` to access already initalized PDO object in the library.

**Comment by nesttle** [comment]
@jacklul Thanks! $pdo = DB::getPdo(); plus $pdo = DB::getPdo();*  did the job!

* Inside public function execute(){ $pdo = DB::getPdo(); (...) }

**Comment by nesttle** [comment]
But having problems with $query->bindParam (I can only INSERT with full statement on $pdo->prepare(statement); but bindParam looks to broke my code:

`
                try {
                    $query = $pdo->prepare('
                        INSERT INTO `mycustomtable`
                        (`id`, `param2`, `param3`, `param4`, `param5`)
                        VALUES
                        (:id, :param2, :param3, :param4, :param5)
                        ON DUPLICATE KEY UPDATE
                            `id`   = :id,
                            `param2` = :param2,
                            `param3` = :param3,
                            `param4`  = :param4,
                            `param5` = :param5
                    ');
                    
                    $query->bindParam(':id', 111, PDO::PARAM_INT);
                    $query->bindParam(':param2', 222, PDO::PARAM_INT);
                    $query->bindParam(':param3', 'string', PDO::PARAM_STR);
                    $query->bindParam(':param4', 333, PDO::PARAM_INT);
                    $query->bindParam(':param5', 'string', PDO::PARAM_STR);
                    $execute_query = $query->execute();
                } catch (PDOException $e) {
                    //throw new TelegramException($e->getMessage());
                    $data['text'] = 'ERROR';
                }
`

**Comment by jacklul** [comment]
`bindParam()` requires the values to be passed by reference, so:

```php
$id = 111;
$param2 = 222;
$param3 = 'string';
$param4 = 333;
$param5 = 'string';

$query->bindParam(':id', $id, \PDO::PARAM_INT);
$query->bindParam(':param2', $param2, \PDO::PARAM_INT);
$query->bindParam(':param3', $param3, \PDO::PARAM_STR);
$query->bindParam(':param4', $param4, \PDO::PARAM_INT);
$query->bindParam(':param5', $param5, \PDO::PARAM_STR);
$execute_query = $query->execute();

```

Also it will be good practice to use `\PDO`.
