### ISSUE TITLE
Xampp Problem

### ISSUE THREAD

**Issue by MrMehdi** [akalongman/php-telegram-bot#381]
### Required Information

- PHP version:
- PHP Telegram Bot version:
- Using MySQL database: yes / no
- Update Method: Webhook / getUpdates
- Self-signed certificate: yes / no
- RAW update (if available):

### Expected behaviour

Hi 
i try to test this sdk on xampp and i got this error:
Fatal error: Call to a member function getBody() on null in 

> **C:\xampp\htdocs\Ajax\vendor\longman\telegram-bot\src\Request.php on line 229**

anybody could help me?
i try to getupdate method for telegram bot.
tnx for your attention

**Comment by jacklul** [comment]
Library currently doesn't work on Windows OS.

**Comment by MrMehdi** [comment]
tnx for your help

**Comment by juandiii** [comment]
I don't understand bro 
I'm sorry
