### ISSUE TITLE
Commands sent in Channel are error-prone

### ISSUE THREAD

**Issue by ahmadazizi** [akalongman/php-telegram-bot#383]
If in a channel(not a group or supergroup) we send a /command , the command will be directed to GenericmessageCommand.php where in line 51 it tries a getFrom() on null which causes this error:

> Call to a member function getFrom() on null in /vendor/longman/telegram-bot/src/Commands/SystemCommands/GenericmessageCommand.php:51

It shouldn't try getFrom() where in channel.

**Comment by jacklul** [comment]
You're probably not using newest version, in the latest version channel messages are handled by ChannelpostCommand.

**Comment by ahmadazizi** [comment]
Thanks, just solved. The version defined in composer was ^0.35 which may was as a result of old instructions.
