### ISSUE TITLE
How to pictures from the bot will automatically download and save?

### ISSUE THREAD

**Issue by SacredSpirit** [akalongman/php-telegram-bot#386]
### Required Information

- PHP version: **5.5.0**
- PHP Telegram Bot version: **^0.38.1**
- Using MySQL database: **yes**
- Update Method: **Webhook**
- Self-signed certificate: **no**
- RAW update (if available):

### Expected behaviour
Download and save all picture from channel automatically

### Actual behaviour
Need tuning

### Extra details
I tried to take advantage of [this advice](https://github.com/akalongman/php-telegram-bot/issues/221#issuecomment-224727595), but this has no effect((

Please, help(((

hook.php
`    // Set custom Upload and Download path
    $telegram->setDownloadPath(BASE_PATH . '/var/www/html/download');
    $telegram->setUploadPath(BASE_PATH . '/var/www/html/upload');`
I tried in different ways, but has no effect

**Comment by jacklul** [comment]
Adding something like this to GenericmessageCommand should keep saving all files sent to the bot:
```php
        if (in_array($message->getType(), ['Audio', 'Document', 'Photo', 'Video', 'Voice'])) {
            $doc = call_user_method('get' . $message->getType(), $message);
            ($message->getType() === 'Photo') && $doc = $doc[0];

            $file_id = $doc->getFileId();
            $file = Request::getFile(['file_id' => $file_id]);
            if ($file->isOk()) {
                return Request::downloadFile($file->getResult()
            }
        }
```

(literally cut code from https://github.com/akalongman/php-telegram-bot/issues/221#issuecomment-224727595)

**Comment by SacredSpirit** [comment]
Hangs on this instruction: `$file_id = $doc->getFileId();`
((

**Comment by jacklul** [comment]
Define hangs? Script does nothing? Not even an error? Thats weird.

**Comment by noplanman** [comment]
Check out #221.

@jacklul Since 0.35, `->getType()` returns the type in lowercase!

Here the corrected code:
```php
...
if (in_array($message->getType(), ['audio', 'document', 'photo', 'video', 'voice'], true)) {
    $doc = call_user_func([$message, 'get' . ucfirst($message->getType())]);
    ($message->getType() === 'photo') && $doc = $doc[0];
...
```

**Comment by SacredSpirit** [comment]
Its worked!!!! Thanks!!!
But very little size
How take full size pic?

**Comment by noplanman** [comment]
The variable `$doc` is an array of images, starting from smallest to biggest.

So for the biggest version you could just get the last item like so: `$doc = end($doc);`

**Comment by SacredSpirit** [comment]
Thank you very match!!! Its work!!!
