### ISSUE TITLE
Changelog file?

### ISSUE THREAD

**Issue by Sogl** [akalongman/php-telegram-bot#388]
Hello!

I'm using 0.33 version.
From the latest commit I found that the new version is 0.38.1.

Where I can find which changes are been made?

p.s, Only this issue I can find searcing with "changelog" keyword:
https://github.com/akalongman/php-telegram-bot/issues/360

**Comment by noplanman** [comment]
Hm, we don't have a changelog per se (which we really should!), but you can check through the releases page and read what has changed in each version there.

https://github.com/akalongman/php-telegram-bot/releases

**Comment by Sogl** [comment]
Hm...in release `0.34` I see:
```
Table structure fixes (thanks to @jacklul )
```

So what fixes are been made?
How to integrate them into existing project?

**Comment by jacklul** [comment]
You can always pull the repository to temporary directory and make a comparison between release tags or browse through commits and check changes.

**Comment by noplanman** [comment]
Another **big** ping to myself and #112 ❗️ 

Really need to get this sorted. Manually updating the table schemas every time there is a change just sucks big time...

**Comment by lichtscheu** [comment]
@noplanman could close this? =)

**Comment by noplanman** [comment]
@lichtscheu: Yep 👍 
@Sogl: We finally have a [`CHANGELOG.md`](https://github.com/akalongman/php-telegram-bot/blob/master/CHANGELOG.md) file, yaay 🎉

**Comment by Sogl** [comment]
@noplanman Cool!
And what about update scripts? I'm still on 0.33 now and want to quickly update it to latest without data loss or something.

It would be great if the scripts were working after `composer update/install`.

**Comment by noplanman** [comment]
Right, that's my next mission.
Wow, 0.33 is quite far back :grin:

**Comment by lichtscheu** [comment]
+1 for update script!
