### ISSUE TITLE
Problem with buttons size of Keyboard

### ISSUE THREAD

**Issue by MostafaSh** [akalongman/php-telegram-bot#389]
Hi !
I have a problem when I display a keyboard. the buttons doesn't fit in an appropriate size. the buttons are too big. I'm using this code: 

```php
$data = [
	'chat_id'      => $chat_id,
];`
	
$replyMarkup = array(
	'keyboard' => array(
		array("myButton")
	)
);
	
$encodedMarkup = json_encode($replyMarkup);
$data['text'] = "Choose :";
$data['reply_markup'] = $encodedMarkup;
Request::sendMessage($data);
```

what should i do to have buttons in an appropriate size?

"It would be a big honor for me if you help me again @noplanman !"

**Comment by noplanman** [comment]
Hi @MostafaSh 

What version of the library are you using?
(Please remember to post that when asking a question :wink:)

To resize the keyboard, there is a property that you can add called `resize_keyboard`:
```php
$replyMarkup = array(
    'keyboard' => array(
        array("myButton")
    ),
    'resize_keyboard' => true,
);
```

---

Also, with the newest versions of the library, you need to change this:
```php
$encodedMarkup = json_encode($replyMarkup);
$data['text'] = "Choose :";
$data['reply_markup'] = $encodedMarkup;
```
to this:
```php
$data['text'] = "Choose :";
$data['reply_markup'] = $replyMarkup;
```
No need to use `json_encode` here.

---

The best would be to upgrade to the newest version of the library and to use the new Keyboard creating functionality we have added:
```php
$data = [
  'chat_id' => $chat_id,
];

$replyMarkup = new Keyboard('myButton');
$replyMarkup->setResizeKeyboard(true);

$data['text'] = 'Choose :';
$data['reply_markup'] = $replyMarkup;

return Request::sendMessage($data);
```

**Comment by MostafaSh** [comment]
thank you so so much @noplanman !

and again you did the best for me!

but also I have another question! 

I don't know how  i can use inline keyboard. I mean how I can describe an action when an inline button is clicked? I think there is no example in this lib to know that!

and also one more! how can I display Emojis inside buttons! 

thank you so much!

**Comment by DestroyKun** [comment]
@MostafaSh emojis are Unicode symbols and you can just copy and paste it to your button text.

**Comment by jacklul** [comment]
Also: do not let any PHP text functions parse a string containing an emoji, there is a chance the string will be corrupted and Telegram will deny the request.

**Comment by noplanman** [comment]
@MostafaSh How is this going?

Also, when using Emojis, it might be better to use a library for that if your editor doesn't support them.
https://github.com/spatie/emoji

**Comment by MostafaSh** [comment]
hi again guys!
thanks to @noplanman , @jacklul and @DestroyKun  for answering!

everything almost is going fine, except one tiny problem, which I,ll open a new issue for that!

**Comment by mansour161** [comment]
hi guys 
i have list of product in database
and with cod i call them 

$list_type = mysql_query("SELECT * FROM `group` ");
			while($item_type = mysql_fetch_array($list_type))
			{
				$keys[$j] = array($item_type['id'].'. '.$item_type['name']);
				$j++;
			}
			$replyMarkup = array(
				'keyboard' => 
					$keys,'resize_keyboard' => true,
              'one_time_keyboard' => true,'selective' => true
			);

but i can not resize keyboard 

plz help me

**Comment by noplanman** [comment]
@mansour161 What version of the bot are you using? You can use the `/help` command to find out.

**Comment by mansour161** [comment]
My bot is @faranetkala_bot
Yes I am searching . But cant do this.

**Comment by noplanman** [comment]
@mansour161 You can also check in the `vendor/longman/telegram-bot/src/Telegram.php` file, look for `protected $version = 'x.y.z';`

**Comment by mansour161** [comment]
i am doing this cod

$list_type = mysql_query("SELECT * FROM `group` ");
while($item_type = mysql_fetch_array($list_type)) {
	$keys[$j] = array($item_type['id'].'. '.$item_type['name']);
	$j++;
}
			$replyMarkup = array(
			        'keyboard' =>
				array($keys[0],$keys[1],$keys[2]),
                                array($keys[3],$keys[4]),

    "resize_keyboard" => true,
    "one_time_keyboard" => true,
				
			);

but this cod give me just 3 keys(0,1,2) and didnt work (resize_keyboard and one_time_keyboard)

plz help me

**Comment by noplanman** [comment]
You're really not making it easy to help you.

What version of the bot are you using?!
This is important, as keyboard things have changed in some versions.

**Comment by noplanman** [comment]
End of discussion, user isn't using this library...

Also, locking this thread.
