### ISSUE TITLE
how to resolve PHP Warning: date() ?

### ISSUE THREAD

**Issue by MostafaSh** [akalongman/php-telegram-bot#391]
### Required Information

- PHP version: '5.6.29'
- PHP Telegram Bot version: '0.2.0'
- Using MySQL database: yes
- Update Method: Webhook

Hi everybody!
I always get an error in my error log. actually there is no problem with bot performance, but it is getting annoying to see this error too much in error log! this is the error :
`PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/mybotpro/public_html/FumTweet/vendor/longman/telegram-bot/src/DB.php on line 245`

and this is the DB.php lines 239 to 246:
`protected static function getTimestamp($time = null)
 {
 if ($time === null) {
$time = time();
 }
 return date('Y-m-d H:i:s', $time);
}`

and the line 245:
`return date('Y-m-d H:i:s', $time);`

How can I solve this problem guys?
thanks.

**Comment by jacklul** [comment]
Your PHP configuration has no timezone set.
Either set it in php.ini or via  ```date_default_timezone_set("Europe/Warsaw");``` at the beginning of the script.

Timezones list: https://secure.php.net/manual/en/timezones.php
