### ISSUE TITLE
how too resolvee in PHP Fatal error: Uncaught Error: Call to a member function getBody() on null in   ? 

### ISSUE THREAD

**Issue by juandiii** [akalongman/php-telegram-bot#392]
Fatal error: Uncaught Error: Call to a member function getBody() on null in C:\inetpub\wwwroot\vendor\longman\telegram-bot\src\Request.php:229 Stack trace: #0 C:\inetpub\wwwroot\vendor\longman\telegram-bot\src\Request.php(318): Longman\TelegramBot\Request::execute('setWebhook', Array) #1 C:\inetpub\wwwroot\vendor\longman\telegram-bot\src\Request.php(823): Longman\TelegramBot\Request::send('setWebhook', Array) #2 C:\inetpub\wwwroot\vendor\longman\telegram-bot\src\Telegram.php(744): Longman\TelegramBot\Request::setWebhook('https://juandie...', Array) #3 C:\inetpub\wwwroot\set.php(13): Longman\TelegramBot\Telegram->setWebhook('https://juandie...') #4 {main} thrown in C:\inetpub\wwwroot\vendor\longman\telegram-bot\src\Request.php on line 229

**Comment by jacklul** [comment]
https://github.com/akalongman/php-telegram-bot/issues/381
