### ISSUE TITLE
Microsoft Bot: Bot Data getProperty is returning null when I try to set Property

### ISSUE THREAD

**Issue by msBot1111** [akalongman/php-telegram-bot#393]
I'm trying to authenticate my Bot using my web project and I store the token in Bot Data using Bot State. But when I try to get thee token from my Bot using getProperty it always returns null. I'm using this sample: https://blogs.msdn.microsoft.com/tsmatsuz/2016/09/06/microsoft-bot-framework-bot-with-authentication-and-signin-login/ Here is my code in web:
var botCred = new MicrosoftAppCredentials(
         ConfigurationManager.AppSettings["MicrosoftAppId"],                           
         ConfigurationManager.AppSettings["MicrosoftAppPassword"]);
var stateClient = new StateClient(botCred);
BotState botState = new BotState(stateClient);
BotData botData = new BotData(eTag: "*");
botData.SetProperty<string>("AccessToken", authResult.AuthenticationToken);
await stateClient.BotState.SetPrivateConversationDataAsync(TempData["channelid"].ToString(), TempData["conversationid"].ToString(), TempData["skypeuserid"].ToString(), botData);
And here is in my Bot:
ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
StateClient stateClient = activity.GetStateClient();
BotState botState = new BotState(stateClient);
BotData botData = await botState.GetPrivateConversationDataAsync(activity.ChannelId,activity.Conversation.Id, activity.From.Id); 
string token = botData.GetProperty<string>("AccessToken");
The token is always null.

**Comment by noplanman** [comment]
Erm, I think you've landed in the wrong repo here 😕 

This is a PHP library for Telegram Bots.
