### ISSUE TITLE
How best to implement "next" function

### ISSUE THREAD

**Issue by opkiler22789** [akalongman/php-telegram-bot#398]
![picsart_01-21-10 55 36](https://cloud.githubusercontent.com/assets/17113289/22177723/ba57bae8-e02c-11e6-99cb-84c4e6511908.jpg)
 How best to implement "next" function. That works in many bots. Do I need to record a value for each user? Whether there are working examples?

**Comment by jacklul** [comment]
You can use Conversation feature to save which page user is currently on, example how to use it is in SurveyCommand !

If the content in pages is static you can assign each page an unique id then simply create a button with id+1 for each page.

**Comment by opkiler22789** [comment]
@jacklul Thank you figured out, happened
