### ISSUE TITLE
How to handle non-commands?

### ISSUE THREAD

**Issue by emehran** [akalongman/php-telegram-bot#399]
Hello there, 

My question is how to handle simple strings instead of /commands ? for example I show a keyboard to the user and he can select a string or number. I would like to respond to the selected text. How is it possible with your wrapper?
I know it should be managed through genericmessage but not show how.
Thanks

**Comment by jacklul** [comment]
GenericmessageCommand.

**Comment by emehran** [comment]
@jacklul thanks for your help.  could you provide an example of how to use Conversation feature to redirect a sample text like "45" to something like "read 45"?

**Comment by jacklul** [comment]
Take a look at survey command, it's interactive question-answer command.

**Comment by emehran** [comment]
Thanks, resolved
