### ISSUE TITLE
what about Receiving messages?

### ISSUE THREAD

**Issue by AliCrash** [akalongman/php-telegram-bot#4]
Hello.

I want my bot to receive some messages and store them on local database (mysql).
what is your suggestion?
please help me.

Regards.

**Comment by akalongman** [comment]
Already implemented in latest version. Check mysql block in readme

**Comment by AliCrash** [comment]
I rechecked readme file. there is nothing about receiving message and also there isn't any mysql block.
I just want my bot to receive messages. please help me.

**Comment by akalongman** [comment]
Look at readme: https://github.com/akalongman/php-telegram-bot#usage
