### ISSUE TITLE
Input is empty! - hook.php

### ISSUE THREAD

**Issue by weiddolo** [akalongman/php-telegram-bot#40]
I first used <strong>getUpdatesCLI.php</strong> and works properly every time i will refresh the page manually (Each refresh of the page the bot reply to me). It's ok!

Now I wanted to try to set webhook. After setting the webhook (<strong>set.php</strong> - Webhook was set!), i try to write in the chat, but the bot does not reply to me .. Then I go to to <strong>hook.php</strong> page and i get this error:
<code>Input is empty!</code>

What wrong? <h3>The same configuration for getUpdatesCLI.php works</h3>

This is my <strong>hook.php</strong>:
<pre>
	//Composer Loader
	$loader = require __DIR__.'/vendor/autoload.php';
	
	$API_KEY = 'XXXXXXXXXXXXX:XXXXXXXXXXXXX';
	$BOT_NAME = 'XXXXXXXXXXXXX';
	//$COMMANDS_FOLDER = __DIR__.'/src/Commands/';
	$credentials = array('host'=>'localhost', 'user'=>'XXXXXXXXXXXXX', 'password'=>'XXXXXXXXXXXXX', 'database'=>'XXXXXXXXXXXXX');
	
	try {
		// create Telegram API object
		$telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);
	
		//Options
	
		$telegram->enableMySQL($credentials);
		//$telegram->enableMySQL($credentials, $BOT_NAME.'_');
		//$telegram->addCommandsPath($COMMANDS_FOLDER);
		// here you can set some command specified parameters,
		// for example, google geocode/timezone api key for date command:
		//$telegram->setCommandConfig('date', array('google_api_key'=>'your_google_api_key_here'));
		//$telegram->setLogRequests(true);
		//$telegram->setLogPath($BOT_NAME.'.log');
	
	
		// handle telegram webhook request
		$telegram->handle();
	} catch (Longman\TelegramBot\Exception\TelegramException $e) {
		// log telegram errors
		echo $e->getMessage();
	}

</pre>

**Comment by MBoretto** [comment]
Is your link to hook.php secure (https)? In 0.17.2 Exceptions are logged this can help to understand the problem.

**Comment by weiddolo** [comment]
Yes hook.php in on HTTPS

**Comment by weiddolo** [comment]
Yes is on HTTPS. I've update file <strong>TelegramException.php</strong> but i retrive always <strong>Input is empty!</strong>

**Comment by weiddolo** [comment]
This is LOG file: 

<pre>2015-09-22 00:43:47 exception 'Longman\TelegramBot\Exception\TelegramException' with message 'Input is empty!' in /var/www/vhosts/domain.it/sub.domain.it//weiddolo/src/Telegram.php:330
Stack trace:
#0 /var/www/vhosts/domain.it/sub.domain.it/weiddolo/hook.php(30): Longman\TelegramBot\Telegram->handle()
#1 {main}</pre>

**Comment by weiddolo** [comment]
Any ideas?

**Comment by danielberlin** [comment]
The input should only be logged as empty when you directly access your hook.php in your browser. The requests from the Telegram API should not produce the empty error. Have a look at what is logged in the web server's error_log when Telegram requests hook.php.

I also have the problem that the bot does not answer but I think it's because the echo command is not set up properly and so far this is not documented how to do it.

**Comment by weiddolo** [comment]
With the 0.18.0 version i do not see this problem. But if i went in hook.php, the page is blank and the bot still does not respond

**Comment by ShinDongHwan** [comment]
I want to solve same problem. i setted using set.php, but message 'Input is empty!'.
plz, help me...

**Comment by MBoretto** [comment]
If webhook has been set properly telegram will point to that address. 
You don't need to open the page from you browser.
https://github.com/akalongman/php-telegram-bot/issues/38
https://github.com/akalongman/php-telegram-bot/issues/16

**Comment by ShinDongHwan** [comment]
not solve...TT.

http://hscoop.esy.es/wordpress/tele/php-telegram-bot/examples/hook.php

and $telegram->setWebHook($url, $cert);
$url is hoop.php ?? 
$cert is ~.crt path??

i want you to understand my English skill.

**Comment by MBoretto** [comment]
feel free to reopen this

**Comment by antonanton** [comment]
have the same problem. Web hook is set but hook.php says input is empty, bot does not respond

**Comment by devdenis** [comment]
Have the same problem. Use SSL from Let's Encrypt, webhook is set, but have the error
Fatal error: Uncaught exception 'Longman\TelegramBot\Exception\TelegramException' with message 'Input is empty!' in /path/vendor/longman/telegram-bot/src/Telegram.php on line 414

**Comment by KilluaFein** [comment]
well, figured out the errors:
first, I had an old version of longman telegram-bot (don't know why, did a composer update couple times).
Then, I was trying to use as webhook `www.domain.com/hook.php`, but my certificate was for `domain.com` ... yes i feel so stupid. Thank you all

**Comment by noplanman** [comment]
The "Input is empty!" message is correct, as there is no input.

Have you tried enabling the error and debug logs?
Look here: https://github.com/akalongman/php-telegram-bot/blob/0.35/doc/01-utils.md#logging

Then you can try to send a command to your bot again and see if there is an entry in the logs that may explain what is wrong.

**Comment by NabiKAZ** [comment]
I had same problem, The problem is with SSL certificate, I renew key and resolve it.
You must check the hostname in here:
https://www.ssllabs.com/ssltest/analyze.html
And make sure `Trusted` is `Yes`.
