### ISSUE TITLE
Uncaught Error: Call to a member function isOk()

### ISSUE THREAD

**Issue by nesttle** [akalongman/php-telegram-bot#403]
### Required Information

- PHP version: 7.0.13
- PHP Telegram Bot version: 0.39.0
- Using MySQL database: yes 
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour
Bot should reply to commands.

### Actual behaviour
Bot stucks and is not responding to any messages/commands after an unknown issue. Sometimes I can solve this cleaning DB or removing/uploading again files.

### Steps to reproduce
Execute some /command, and randomly all commands stop working. Bot don't reply anymore to any command after this.
OR call directly hook.php, and next error appears

### Extra details (error.log Apache)
```
PHP Fatal error:  Uncaught Error: Call to a member function isOk() on boolean in /var/www/html/_tg/vendor/longman/telegram-bot/src/Telegram.php:363
Stack trace:\n#0 /var/www/html/_tg/hook.php(29): Longman\\TelegramBot\\Telegram->handle()
#1 {main}\n  thrown in /var/www/html/_tg/vendor/longman/telegram-bot/src/Telegram.php on line 363
```

**Comment by nesttle** [comment]
@jacklul @noplanman

**Comment by nesttle** [comment]
<?php
// Load composer
require __DIR__ . '/vendor/autoload.php';

$API_KEY = '11111:Botidhere';
$BOT_NAME = 'MyBotName';
$mysql_credentials = [
   'host'     => 'localhost',
   'user'     => 'usern',
   'password' => 'passw',
   'database' => 'dbname',
];


try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);
/*
    \Longman\TelegramBot\TelegramLog::initUpdateLog(__DIR__ . '/' . $BOT_NAME . '_update.log');
    \Longman\TelegramBot\TelegramLog::initDebugLog(__DIR__ . '/' . $BOT_NAME . '_debug.log');
    \Longman\TelegramBot\TelegramLog::initErrorLog(__DIR__ . '/' . $BOT_NAME . '_error.log');
*/
    $telegram->enableMySQL($mysql_credentials);
    $telegram->enableAdmin(1111);
    $telegram->addCommandsPath(__DIR__ . '/vendor/longman/telegram-bot/src/Commands/CustomCommands');

    // Handle telegram webhook request
    $telegram->handle();
} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    // Silence is golden!
    // log telegram errors
    // echo $e;
}

**Comment by nesttle** [comment]
hook.php output:
```
Longman\TelegramBot\Exception\TelegramException: Input is empty! in /var/www/html/teleg/vendor/longman/telegram-bot/src/Telegram.php:354
Stack trace:
#0 /var/www/html/teleg/hook.php(28): Longman\TelegramBot\Telegram->handle()
#1 {main}
```

**Comment by noplanman** [comment]
Is this the case for all commands or just custom ones?

It looks like the command you are calling returns a `boolean` instead of a `ServerResponse` object.

**Comment by nesttle** [comment]
Stack trace:
#0 /var/www/html/tg/hook.php(29): Longman\TelegramBot\Telegram->handle()
#1 {main}Longman\TelegramBot\Exception\TelegramException: Input is empty! in /var/www/html/tg/vendor/longman/telegram-bot/src/Telegram.php:354
Stack trace:

**Comment by noplanman** [comment]
That is a normal response when opening `hook.php` with your browser.

When you install a fresh version of the latest version and an empty database, do all commands work without any issues?

If issues start when you add custom commands, could you please post one of the commands that creates the issue? That way we can see what is causing it, thanks!

**Comment by nesttle** [comment]
Thanks for your reply @noplanman 

Yes, all commands works without any issues on a fresh install. Also, when I use my customs commands works too, but after 1-2 days something broke, and all commands stops working.

Some times I can fix this commenting my custom commands include on hook.php:
`//$telegram->addCommandsPath(__DIR__ . '/vendor/longman/telegram-bot/src/Commands/CustomComm');`
and calling hook.php again.

This time I can't fix this, neither commenting line above :(

**Comment by noplanman** [comment]
So you always get the `PHP Fatal error:  Uncaught Error: Call to a member function isOk() on boolean` error then?

Have you enabled the error logging in your bot?

**Comment by nesttle** [comment]
@noplanman hope I can enable error loggin, but having issuis with write permissions (tried with 755 also on all bot files/folders and same). Will try to enable logging to give you best acurate details about error!

**Comment by nesttle** [comment]
@noplanman solved with chown & chmod:  http://stackoverflow.com/questions/5165183/apache-permissions-php-file-create-mkdir-fail


Now bot can write _error.log and _access.log also

_error.log
`
{"update_id":990XXXXX, "edited_message":{"message_id":5XXX,"from":{"id":32XXXXXX"first_name":"nesttle","username":"nesttle"},"chat":{"id":32XXXXXX,"first_name":"nesttle","username":"nesttle","type":"private"},"date":148646XXX,"edit_date":1486468XXX,"text":"/whois testing","entities":[{"type":"bot_command","offset":0,"length":6}]}}
{"update_id":990XXXXX, "edited_message":{"message_id":5XXX,"from":{"id":32XXXXXX"first_name":"nesttle","username":"nesttle"},"chat":{"id":32XXXXXX,"first_name":"nesttle","username":"nesttle","type":"private"},"date":148646XXX,"edit_date":1486468XXX,"text":"/whois testing","entities":[{"type":"bot_command","offset":0,"length":6}]}}
{"update_id":990XXXXX, "edited_message":{"message_id":5XXX,"from":{"id":32XXXXXX"first_name":"nesttle","username":"nesttle"},"chat":{"id":32XXXXXX,"first_name":"nesttle","username":"nesttle","type":"private"},"date":148646XXX,"edit_date":1486468XXX,"text":"/whois testing","entities":[{"type":"bot_command","offset":0,"length":6}]}}
{"update_id":990XXXXX, "edited_message":{"message_id":5XXX,"from":{"id":32XXXXXX"first_name":"nesttle","username":"nesttle"},"chat":{"id":32XXXXXX,"first_name":"nesttle","username":"nesttle","type":"private"},"date":148646XXX,"edit_date":1486468XXX,"text":"/whois testing","entities":[{"type":"bot_command","offset":0,"length":6}]}}
{"update_id":990XXXXX, "edited_message":{"message_id":5XXX,"from":{"id":32XXXXXX"first_name":"nesttle","username":"nesttle"},"chat":{"id":32XXXXXX,"first_name":"nesttle","username":"nesttle","type":"private"},"date":148646XXX,"edit_date":1486468XXX,"text":"/whois testing","entities":[{"type":"bot_command","offset":0,"length":6}]}}

`

**Comment by nesttle** [comment]
@noplanman solved with chown & chmod:  http://stackoverflow.com/questions/5165183/apache-permissions-php-file-create-mkdir-fail


Now bot can write _error.log and _access.log also

_error.log
`
{"update_id":990XXXXX, "edited_message":{"message_id":5XXX,"from":{"id":32XXXXXX"first_name":"nesttle","username":"nesttle"},"chat":{"id":32XXXXXX,"first_name":"nesttle","username":"nesttle","type":"private"},"date":148646XXX,"edit_date":1486468XXX,"text":"/whois testing","entities":[{"type":"bot_command","offset":0,"length":6}]}}
{"update_id":990XXXXX, "edited_message":{"message_id":5XXX,"from":{"id":32XXXXXX"first_name":"nesttle","username":"nesttle"},"chat":{"id":32XXXXXX,"first_name":"nesttle","username":"nesttle","type":"private"},"date":148646XXX,"edit_date":1486468XXX,"text":"/whois testing","entities":[{"type":"bot_command","offset":0,"length":6}]}}
{"update_id":990XXXXX, "edited_message":{"message_id":5XXX,"from":{"id":32XXXXXX"first_name":"nesttle","username":"nesttle"},"chat":{"id":32XXXXXX,"first_name":"nesttle","username":"nesttle","type":"private"},"date":148646XXX,"edit_date":1486468XXX,"text":"/whois testing","entities":[{"type":"bot_command","offset":0,"length":6}]}}
{"update_id":990XXXXX, "edited_message":{"message_id":5XXX,"from":{"id":32XXXXXX"first_name":"nesttle","username":"nesttle"},"chat":{"id":32XXXXXX,"first_name":"nesttle","username":"nesttle","type":"private"},"date":148646XXX,"edit_date":1486468XXX,"text":"/whois testing","entities":[{"type":"bot_command","offset":0,"length":6}]}}
{"update_id":990XXXXX, "edited_message":{"message_id":5XXX,"from":{"id":32XXXXXX"first_name":"nesttle","username":"nesttle"},"chat":{"id":32XXXXXX,"first_name":"nesttle","username":"nesttle","type":"private"},"date":148646XXX,"edit_date":1486468XXX,"text":"/whois testing","entities":[{"type":"bot_command","offset":0,"length":6}]}}

`

**Comment by nesttle** [comment]
Also, on db table.`edited_message` I can see same request again and again:
http://i.imgur.com/s1fsHZG.png :: [Database](http://i.imgur.com/s1fsHZG.png)

**Comment by nesttle** [comment]
Target username on `/whois` has numbers. Username is like `A1234b`.

**Comment by nesttle** [comment]
@noplanman you can close this, I made a new issue better explained with this error, ty!
