### ISSUE TITLE
InlineKeyboard callback features

### ISSUE THREAD

**Issue by dzarezenko** [akalongman/php-telegram-bot#404]
Hi,
I have implemented `InlineKeyboard` functionality in my bot. This is a set of buttons with bullets, each button represents a category. All works fine on the server side, but I need changes on the client in the Telegram:

1. I want show/hide bullet on button click, when user check/uncheck category. How can I do this with your lib?
2. How can I remove top drop-down message on button click ("Hello World!")?

![tb](https://cloud.githubusercontent.com/assets/148570/22667192/7108ec0a-ecc4-11e6-8228-8bd43df9fd73.jpg)

Thanks!

**Comment by jacklul** [comment]
Store which buttons are checked using Conversation's notes array?

**Comment by dzarezenko** [comment]
@jacklul Sorry, what do you mean?

**Comment by jacklul** [comment]
Look into surveycommand example, use Conversation to store which ones are checked.

**Comment by dzarezenko** [comment]
Thank you for the response. I have resolved both my issues:

1. Resolved with `Request::editMessageReplyMarkup`:
```php
Longman\TelegramBot\Request::editMessageReplyMarkup([
   'chat_id'      => $this->chatId,
   'message_id'   => $this->messageId,
   'reply_markup' => $this->generateKeyboard()
]);
```
I detect what button is pressed by `callback_data` parameter of the `InlineKeyboard` button, something like
```php
[
   'text' => (isset($userCategories[$category->id]) ? Icons::LARGE_RED_CIRCLE . " " : "") . $category->title,
   'callback_data' => "setCategory:{$category->id}"
]
```
so I know what action to perform and with what category (what button pressed).

2. I have resolved by replacing `CallbackqueryCommand` class with my own class as you suggested.

Thank!
