### ISSUE TITLE
Can not add other command

### ISSUE THREAD

**Issue by msrahmanian** [akalongman/php-telegram-bot#41]
Hello
First of all thanks for implementing the robot code
My problem is on adding new commands to my robot, for example I copied echo command and changed command name to test and rename the file to TestCommand.php but when I enter /test command in my rovot in telegram it just says Command: test not found :(
would you please help about this issue ?

Thanks alot.

**Comment by MBoretto** [comment]
Check lowercase and uppercase letter try also to print the entire path of your folder.
In 0.17.2 Exceptions are logged this can help to understand the problem.

**Comment by MBoretto** [comment]
A wiki guide has been written to create 
your fist commad: https://github.com/akalongman/php-telegram-bot/wiki/Create-your-own-commands
