### ISSUE TITLE
It's possible create an bot without botFather?

### ISSUE THREAD

**Issue by dvjunior** [akalongman/php-telegram-bot#411]
I'm sorry for make this question here, but I would like automatization the process for create an bot.
 Object: Internal Software as a Service, an API for create new bot and configure it.
 Someone know if it's possible?

**Comment by chuv1** [comment]
To authomate it use cli telegram client and request botfather with it.
There is no other way to get api key, except BotFather.

**Comment by dvjunior** [comment]
I came to the same conclusion. Tks @chuv1

**Comment by noplanman** [comment]
Just to point you to the [Telegram CLI](https://github.com/vysheng/tg)
