### ISSUE TITLE
echo bot

### ISSUE THREAD

**Issue by crocodilered** [akalongman/php-telegram-bot#416]
Hello

Im trying to use php-telegram-bot and i've got a question: you operates with commands but is it possible to handle any user message, not command only?

In other words, can I write with this api echo bot?

Thank you,
Serge

**Comment by jacklul** [comment]
`GenericmessageCommand.php` handles user messages.

**Comment by noplanman** [comment]
@crocodilered To make an echo bot (for whatever reason), you can copy the `Commands/SystemCommands/GenericmessageCommand.php` to a custom directory and add it to your bot using `$telegram->addCommandsPath(...);` in your `hook.php`.

Then modify your custom `GenericmessageCommand.php` `execute()` (or `executeNoDb()`) method like this:
```php
public function execute()
{
    $message = $this->getMessage();

    return Request::sendMessage([
        'chat_id' => $message->getChat()->getId(),
        'text'    => $message->getText(),
    ]);
}
```

Now, every message received, gets sent right back.

**Comment by crocodilered** [comment]
Thank you pals!
