### ISSUE TITLE
how can i attach a file to a long message?

### ISSUE THREAD

**Issue by hamidamel** [akalongman/php-telegram-bot#418]
how can i attach a file to long message?
like this?
[https://i.stack.imgur.com/0u9hc.png](https://i.stack.imgur.com/0u9hc.png)

**Comment by akalongman** [comment]
@MBoretto @noplanman @jacklul can you suggest anything guys?

**Comment by MBoretto** [comment]
Have you already tried with this? https://github.com/akalongman/php-telegram-bot/blob/master/src/Entities/Document.php

**Comment by noplanman** [comment]
Document caption has a limit of 200 characters.

Trying to figure out if that is the document caption in the screenshot or something else...

**Comment by jacklul** [comment]
This might be something they didn't release yet to the API, it looks like linked content but also like attachment. Maybe there is some kind of new field that allows links to be attached?

**Comment by noplanman** [comment]
@jacklul I agree, it's not a document caption. It looks like a preview when sharing a link, maybe they'll be adding that to the Document entity?
@hamidamel Where did you take that screenshot from?

**Comment by chuv1** [comment]
Link can be attached with zero width space utf symbol.
Test this message, for example:
```
$data = [
            'chat_id' => $chat_id,
            'parse_mode'=> 'HTML',
            'text'    => 'So, is there a secret way? <a href="http://telegra.ph/Another-11-30">​​​​​​​​​​​</a>',
        ];
```
![image](https://cloud.githubusercontent.com/assets/13127366/23404938/2ff9278e-fdea-11e6-8b00-5472db35f636.png)

**Comment by hamidamel** [comment]
@chuv1 Thanks, before you wrote this comment i solved my problem like you do, bu I used your sample for white space trick.thats really useful.
we can set parse_mode to markdown and use like this:

```
$data = [
    'chat_id'    => $chat_id,
    'parse_mode' => 'HTML',
    'text'       => '['white-spaces'](url)',
];
```
thank @MBoretto @noplanman @jacklul @akalongman for your comments and specialy thank to you @chuv1
