### ISSUE TITLE
persian command

### ISSUE THREAD

**Issue by ErFUN-KH** [akalongman/php-telegram-bot#42]
i want use persian command in my telegram bot
How can I do this?

**Comment by ErFUN-KH** [comment]
Or How can I receive and process all the data from the telegram?

**Comment by MBoretto** [comment]
Hello, good question..
What can you do now is to handle the text with GenericCommand.php:
https://github.com/akalongman/php-telegram-bot/blob/master/src/Commands/GenericCommand.php#L31

The problem can be solved implementing aliasing for commands.

**Comment by ErFUN-KH** [comment]
Thanks bro
