### ISSUE TITLE
Upload a picture to url, and send

### ISSUE THREAD

**Issue by opkiler22789** [akalongman/php-telegram-bot#420]
Welcome to be the task with the link to download the image and send. I think it is easier, but nothing happened happened.
Code:
`  $image = $this->curl_get_contents("https://www.ru/data/resource_icons/0/{$id}.jpg");
        file_put_contents("/var/www/www-root/data/www/www.ru/bots/test/Download/image.jpg" , $image);`
try $this->telegram->getUploadPath(), and in other ways but failed to get a working effect it.
I will be very grateful for the example code

**Comment by noplanman** [comment]
Hi @opkiler22789 
Not sure I totally understand. Do you want users to be able to send a link to your bot, which then downloads it into the upload folder?

**Comment by opkiler22789** [comment]
@noplanman In general, the bot is integrated with the site and information is displayed, I also try to download links from the site to the directory and send to the chat

**Comment by noplanman** [comment]
Ok, so you're trying to send a picture to a chat via the bot?

In that case you can do the following in the command's `execute` method:
```php
return Request::sendPhoto([
        'chat_id' => $chat_id,
    ],
    '/path/to/your/image.jpg'
);
```

**Comment by opkiler22789** [comment]
@noplanman and it, therefore, but the picture itself does not appear in the directory

**Comment by noplanman** [comment]
Have you set your upload path properly in your `hook.php` file?

You should be able to use this to save the file to the right location:
```php
file_put_contents($this->telegram->getUploadPath() . '/image.jpg', $image);
```
Also, make sure the folder exists and that the permissions are set properly!

**Comment by opkiler22789** [comment]
Thank you gave permissions 777 folder everything worked

**Comment by noplanman** [comment]
Please don't use 777, especially for a folder that allows user uploads!
755 should work perfectly too.
