### ISSUE TITLE
Infinity loop after forwarding message from channel

### ISSUE THREAD

**Issue by SerafimPikalov** [akalongman/php-telegram-bot#421]
### Required Information

- PHP version: PHP 5.6.30
- PHP Telegram Bot version: 0.40.0
- Using MySQL database: yes
- Update Method: getUpdates
- Self-signed certificate:
- RAW update (if available):

### Expected behaviour
1. Forwarding message from channel.
2. Bot processing message.
3. Bot checking next update with incremented offset

### Actual behaviour
1. Forwarding message from channel.
2. Bot processing message.
3. Bot checking next update with same offset.
4. Bot processing same message.
5. Bot checking next update with same offset.
...
infinity loop why bot will get any new message (not forwarded from channel!)

### Steps to reproduce
1. Run getUpdatesCLI.php
2. Create chat with you bot
3. Join any channel (not a group!)
4. Forward any message from channel to you bot
5. Check logs… you will see:
"2017-03-07 01:21:36 - Processed 1 updates
2017-03-07 01:21:36 - Processed 1 updates
2017-03-07 01:21:36 - Processed 1 updates
2017-03-07 01:21:36 - Processed 1 updates"

### Extra details
I have not enough time to find how to fix the problem but its looks like it something around DB::insertMessageRequest and DB::insertTelegramUpdate. It’s looks like telegram-bot not inserting info about forwarded message to the telegram_update table in the DB because violating constrain message_ibfk_4 (but all operation making with INSERT IGNORE and this why everything happining in «silence»)

**Comment by SerafimPikalov** [comment]
Its looks like problem somewhere here: DB.inc:778 - $forward_from_chat for forwarded message is User object (but type is channel :/)

**Comment by SerafimPikalov** [comment]
And finnaly.... Message.inc:57 Are you sure that here have to be   'forward_from_chat' => User::class, not          'forward_from_chat' => Chat::class ?

**Comment by SerafimPikalov** [comment]
That commit bring the bug:
https://github.com/akalongman/php-telegram-bot/commit/f6fb481d0d41360b695dfac2e851b3bfc5213530#diff-c677a2f49b92b068a764b7b31f669c38

It was like that:
-    /**
 -     * @var \Longman\TelegramBot\Entities\Chat|null
 -     */
 -    protected $forward_from_chat;

It become like that:
 'forward_from_chat' => User::class,

Looks like copy/past mistake.

**Comment by SerafimPikalov** [comment]
Have tried to push fix to hotfix branch but got: ERROR: Permission to akalongman/php-telegram-bot.git denied to SerafimPikalov. :((

Anyway fix is simple. Just change in src/Entities/Message.php line number 59 to "'forward_from_chat' => Chat::class,"

**Comment by noplanman** [comment]
0.40.1 released, get it while it's hot 😉
