### ISSUE TITLE
Send to Group?

### ISSUE THREAD

**Issue by lichtscheu** [akalongman/php-telegram-bot#425]
I always read about Channels, i want to send a Message to a specific Group with Cron, is there something like `sendtochannel` for Groups? Like `sendtogroups`? ^^ Couldn't find something about. And if i send `/chats`, Bot answers `Groups:0` `Supergroups: 0`

**Comment by jacklul** [comment]
Bot will have to be added to the group first.

You will have to write your own command that will send messages to specified channel.

Then look here: https://github.com/akalongman/php-telegram-bot/wiki/Running-with-cron-(scheduled-commands)

**Comment by lichtscheu** [comment]
Bot is in group.
Don't want to send to specified channel, i want to send to spedicified group, and channels seem to be different from groups.

I did it like the wiki said, but the `runCommands()` needs to be `sendtochannel` before, but there is the old problem with channels != groups? =)

**Comment by jacklul** [comment]
Oh sorry, late hour's mistake, I meant group.

Just create a custom command that sends the text to the group you want then add it to cron just like in the wiki article.

**Comment by lichtscheu** [comment]
No Problem, ok i'll try this, if i understand it right. Thanks, i'll report the result =)

**Comment by lichtscheu** [comment]
I think it works now, thanks! Great Work by the Way, i'll contribute as soon as i can =)
