### ISSUE TITLE
How to handle errors in an unique way?

### ISSUE THREAD

**Issue by ahmadazizi** [akalongman/php-telegram-bot#432]
When sending requests to telegram API sometimes errors happen. For example maybe the message format is invalid and the API responds with an error.
Catching these errors is not easy and straightforward in this library, it looks like that the library throws an `\Longman\TelegramBot\Exception\TelegramException `in some error cases. So I tried to catch the exceptions like the following:

```
try {
  $result = Request::sendMessage('......');
} catch (\Longman\TelegramBot\Exception\TelegramException $ex) {
      echo $ex->getMessage()
}
```

But this does not work all the time, sometimes the catch block catches some errors, while in other cases it doesn't and the $result contain the error info.

It is usually required to handle errors in a unique way while working with API, maybe someone wants to take special actions on error cases.
What is the best way to handle the errors in a unique way?

**Comment by jacklul** [comment]
You must check for errors inside $result. 

`$result->isOk()` returns false on error, I think `$result->getDescription()` will return the error text

Because of past issues where the library stopped while Telegram returned error we no longer thrown errors here, it's up to bot developer to handle those. (some can be ignore like the ones saying you tried to edit message but sent exactly same content)

**Comment by ahmadazizi** [comment]
Yes, I'm already doing this, but as I described, sometimes it throws exceptions in some cases and I have my code to handle all exceptions. So I'm taking care of both cases.

Thank you.

**Comment by jacklul** [comment]
I'm curious - what kind of exceptions are you getting there?

**Comment by ahmadazizi** [comment]
As long as I remember it was in cases like the chat_id does not exist.
I will update here as soon as I noticed the case was happened again.

**Comment by ahmadazizi** [comment]
@jacklul here is an exception case:

`Request::getChatMember(['chat_id' => $chatId, 'user_id' => $wrongUserId);`

This raises an exception catchable by \Longman\TelegramBot\Exception\TelegramException

**Comment by ahmadazizi** [comment]
There was a confusion on my installation done by composer:
The current package version was reported '1.0.8' by composer while the latest version on master was '0.41'.
This has resulted to not updating the package by composer update for a while and my real version was outdated.
I did remove & re-installed the package and this issue seems to be fixed with current version.

It looks like the versioning conventions has changed during updates, you'd better to notify users, thanks..

**Comment by noplanman** [comment]
@ahmadazizi The wrong versions (1.0.x) have been removed from packagist for quite some time.
I check periodically to make sure they don't somehow slip in again...

So we can close off here?

**Comment by ahmadazizi** [comment]
Thank you @noplanman I close this issue.
