### ISSUE TITLE
Error GenericmessageCommand line 51 on geting updates

### ISSUE THREAD

**Issue by a-potap** [akalongman/php-telegram-bot#433]
### Required Information

- PHP version : 7
- PHP Telegram Bot version: 1.0.8
- Using MySQL database: yes
- Update Method: getUpdates
- Self-signed certificate: no
- RAW update (if available): 

  ["ok"]=>
  bool(true)
  ["result"]=>
  array(18) {
    [0]=>
    array(2) {
      ["update_id"]=>
      int(731401822)
      ["channel_post"]=>
      array(6) {
        ["message_id"]=>
        int(228)
        ["from"]=>
        array(2) {
          ["id"]=>
          int(266589209)
          ["first_name"]=>
          string(33) "Ненужный-одиночка"
        }
        ["chat"]=>
        array(4) {
          ["id"]=>
          float(-1001105495013)
          ["title"]=>
          string(15) "📈BTS_BTS📈"
          ["username"]=>
          string(13) "BangTang_boyS"
          ["type"]=>
          string(7) "channel"
        }
        ["date"]=>
        int(1489523204)
        ["text"]=>
        string(2364) " .... "
        ["entities"]=>
        array(1) {
          [0]=>
          array(3) {
            ["type"]=>
            string(7) "mention"
            ["offset"]=>
            int(1338)
            ["length"]=>
            int(14)
          }
        }
      }
    }
    [1]=>
    array(2) {
      ["update_id"]=>
      int(731401823)
      ["channel_post"]=>
      array(6) {
        ["message_id"]=>
        int(229)
        ["from"]=>
        array(2) {
          ["id"]=>
          int(266589209)
          ["first_name"]=>
          string(33) "Ненужный-одиночка"
        }
        ["chat"]=>
        array(4) {
          ["id"]=>
          float(-1001105495013)
          ["title"]=>
          string(15) "📈BTS_BTS📈"
          ["username"]=>
          string(13) "BangTang_boyS"
          ["type"]=>
          string(7) "channel"
        }
        ["date"]=>
        int(1489523392)
        ["video"]=>
        array(6) {
          ["duration"]=>
          int(15)
          ["width"]=>
          int(360)
          ["height"]=>
          int(360)
          ["thumb"]=>
          array(4) {
            ["file_id"]=>
            string(34) "AAQCABNTTEsNAAR3Qt6v279TDkYgAQABAg"
            ["file_size"]=>
            int(2631)
            ["width"]=>
            int(90)
            ["height"]=>
            int(90)
          }
          ["file_id"]=>
          string(30) "BAADAgADHQADnwxBSpvucrGNuO9IAg"
          ["file_size"]=>
          int(927253)
        }
        ["caption"]=>
        string(42) "Ха-ха-ха!!!!!
BTS приколы😂"
      }
    }
    [2]=>
    array(2) {
      ["update_id"]=>
      int(731401824)
      ["channel_post"]=>
      array(5) {
        ["message_id"]=>
        int(230)
        ["from"]=>
        array(2) {
          ["id"]=>
          int(266589209)
          ["first_name"]=>
          string(33) "Ненужный-одиночка"
        }
        ["chat"]=>
        array(4) {
          ["id"]=>
          float(-1001105495013)
          ["title"]=>
          string(15) "📈BTS_BTS📈"
          ["username"]=>
          string(13) "BangTang_boyS"
          ["type"]=>
          string(7) "channel"
        }
        ["date"]=>
        int(1489556736)
        ["text"]=>
        string(262) "доброго времени суток хочу представить вам топ супер ботов👾
MarkdownBot
VoteBot
LikeBot
ControllerBot
надеюсь они вам понравится    создатель - ненужный одиночка"
      }
    }
    [3]=>
    array(2) {
      ["update_id"]=>
      int(731401825)
      ["channel_post"]=>
      array(6) {
        ["message_id"]=>
        int(231)
        ["from"]=>
        array(2) {
          ["id"]=>
          int(266589209)
          ["first_name"]=>
          string(33) "Ненужный-одиночка"
        }
        ["chat"]=>
        array(4) {
          ["id"]=>
          float(-1001105495013)
          ["title"]=>
          string(15) "📈BTS_BTS📈"
          ["username"]=>
          string(13) "BangTang_boyS"
          ["type"]=>
          string(7) "channel"
        }
        ["date"]=>
        int(1489556838)
        ["text"]=>
        string(24) "@like #c19053f7bdb2b9b13"
        ["entities"]=>
        array(2) {
          [0]=>
          array(3) {
            ["type"]=>
            string(7) "mention"
            ["offset"]=>
            int(0)
            ["length"]=>
            int(5)
          }
          [1]=>
          array(3) {
            ["type"]=>
            string(7) "hashtag"
            ["offset"]=>
            int(6)
            ["length"]=>
            int(18)
          }
        }
      }
    }

### Expected behaviour
Normal  receiving updates

### Actual behaviour
Stop updating script with error in Longman\TelegramBot\Commands\SystemCommands\GenericmessageCommand string 51
Can't get property

### Steps to reproduce
Bot has to subscrybe on some chanell and get message from chanell. Then run getUpdatesCLI.php 

### Extra details
full vardump file in attachment
[updates_vardump.txt](https://github.com/akalongman/php-telegram-bot/files/844154/updates_vardump.txt)

I have fix this by modifing string 35 in /longman/telegram-bot/src/Entities/Update.php
$this->message = isset($data['message']) ? $data['message'] : (isset($data['channel_post']) ? $data['channel_post'] : null);

**Comment by jacklul** [comment]
I think you don't have the latest version of the library. 
In the current version in the repository channel posts are handled by `ChannelpostCommand` not `GenericmessageCommand`.

**Comment by a-potap** [comment]
Thank you very much! I really had the old version
