### ISSUE TITLE
I can't start the process in the background

### ISSUE THREAD

**Issue by Bombe93** [akalongman/php-telegram-bot#437]
Hi,

I followed this guide: https://github.com/akalongman/php-telegram-bot/wiki/%D0%9Dow-to-launch-getUpdatesCLI.php-script-in-background-(getUpdate-installation)%3F

The php file if run as web works but if I start the command "start nameOfTheDaemon" does not works.
(I get no answers of the bot to my telephone, in the command line return the bot is started but if i send command status returns not started)

It possible simplify the wiki to understand it better?

Thanks

**Comment by noplanman** [comment]
Ok, I've revised the wiki page, please do try it again.

Note: This method is for Ubuntu, using Upstart.

**Comment by Bombe93** [comment]
it works perfectly.
Thanks for your immediate answer.

**Comment by noplanman** [comment]
You're welcome, glad it works now 👌
