### ISSUE TITLE
Fail fetch updates

### ISSUE THREAD

**Issue by raniongolu** [akalongman/php-telegram-bot#44]
can you explain step by step installation after creating telegram bot.
i got this error Fail fetch updates

**Comment by danielberlin** [comment]
A minimum working sample would be nice for the step by step installation, see also #43.

**Comment by MBoretto** [comment]
Have you enabled DB?  example-getUpdatesCLI.php provide a working installation for the getUpdate Methods. Fail fetch update mean also that the server didn't reply to the request.

**Comment by MBoretto** [comment]
feel free to reopen this
