### ISSUE TITLE
Support group bot

### ISSUE THREAD

**Issue by noplanman** [akalongman/php-telegram-bot#440]
Would be cool to have a home-grown bot living among us in the support chat on Telegram.

So let's brainstorm about what it could do for us!

Some ideas:
- Allow linking to GitHub issues / PRs for the core library.
    `gh#123` -> `https://github.com/akalongman/php-telegram-bot/(issues|pulls)/123`
- Send automatic notification on new release (with changelog even?)

**Comment by lichtscheu** [comment]
Would be cool to have this for Dev-Group too? 

Dev-Group:
* send new issues with link
* send new PR with link

Support-Group:
* /ask ->  "Don't ask to ask, just ask"
* /wiki -> Link to Wiki
* /latest -> Latest Version with Link?
* /issue -> "Please open an Issue for this: $link"
* /allsupporters -> just for admins, tags all Supporters in Group and request help/info
* /link "name" -> add preselected custom links like an link to an wiki page with often asked questions

**Comment by noplanman** [comment]
@lichtscheu Great ideas! 👌

Also, taking #438 into account, we could use inline pagination to display the Wiki entries.
`/wiki <search-term>` could display only pages that are related to what is being searched.

Maybe have a separate `/faq` that we manage separately/manually?

I guess we could also include `/changelog <version-number>`.

**Comment by lichtscheu** [comment]
How about a faq in Wiki? ;)

**Comment by noplanman** [comment]
Yes, that would be the easiest and makes total sense!

We could make sure it's parseable, to keep the option open of implementing an `/faq` command if need be.

**Comment by lichtscheu** [comment]
would be cool if there were numbers so you could /faq 13 and then for special we could set some sort auf names so /faq nomysql relates to /faq 13

**Comment by lichtscheu** [comment]
And to the /link "name" part, these are custom links we can set, something like /link telegrambotapi gives the link to the telegram bot api page, and if someone writes own commands for public access and someone asks for a command like this we could link it with /link surveycommand

**Comment by noplanman** [comment]
Ah right, so basically shortcuts that print links, yes?

As for the FAQ command, I think it would make sense to have a page in the wiki that gets used by the bot, so that updates are automatically added to the command.
Regarding the numbers, it would make sense to keep them the same, even if the wiki page gets reorganised at some point. So they would be 'hard-coded' to the FAQ entry in the wiki page. What do you think?
e.g.
Q5: Question number 5?
A5: Yes, answer number 5!

(hmm, this doesn't look too pretty, would need to find a nicer way of presenting them)

**Comment by lichtscheu** [comment]
Yeah, some sort of shortcut!

Do we really need to reorganise? ^^
i think i would go with 
5. "Question"
"Answer" and use some sort of markdown to make it parsable

i would parse the wiki on daily cron, and save the info as json object in the options table =) so we have the "automatically" add new faq to command.

**Comment by noplanman** [comment]
👌 Perfecto!
Instead of cron, we could also make use of GitHub webhooks, which will let you know when the wiki has been updated.

**Comment by lichtscheu** [comment]
or this =)

**Comment by noplanman** [comment]
Moving this discussion over to https://github.com/PHP-Telegram-Bot/Support-Bot
