### ISSUE TITLE
How to make auto-completion works ?

### ISSUE THREAD

**Issue by gabriel-lopez** [akalongman/php-telegram-bot#445]
Hello,

This a great project, got my bot running in no time.

However, I can't get this feature working:

![](http://s1.bild.me/bilder/240416/5266606Capture.JPG "")

Any clues how to enable this ?

Thanks

**Comment by jacklul** [comment]
You have to set them in @BotFather, use `/setcommands`.

**Comment by gabriel-lopez** [comment]
@jacklul I feel totally dumb 🙈 thanks for the fast answer !
