### ISSUE TITLE
How to send message to user who never chatted with bot?

### ISSUE THREAD

**Issue by Sogl** [akalongman/php-telegram-bot#446]
Hello!

I found that when user had chat with bot before, then bot can send messages to this user even if conversation was deleted.
Usually `user_id` is equal to `chat_id`. I try to send message to another user and I know his `user_id` , but this user had no chat with bot before. Unsuccessfully.
Why?

I'm using webhook method so I can't see what's going on on Telegram side.

**Comment by jacklul** [comment]
You can't send message to people that never opened conversation with the bot. 
This is done by Telegram to prevent abuse and advertising bots spam.
