### ISSUE TITLE
Commands list menu and button

### ISSUE THREAD

**Issue by dzarezenko** [akalongman/php-telegram-bot#447]
Hi, this is not an issue, but question, as I didn't found an answer in other places.

How can I implement commands menu with this lib? I mean pop-up menu when you type "/" and if it's possible "/" button like at @BotFather bot.

![bot-commands1](https://cloud.githubusercontent.com/assets/148570/24565418/d21ca546-165d-11e7-8611-0c07a580cc71.jpg)

![bot-commands2](https://cloud.githubusercontent.com/assets/148570/24565424/d698ac82-165d-11e7-9dd5-d869fa67cb8e.jpg)

### Required Information

- PHP version: 5.6
- PHP Telegram Bot version: last one
- Using MySQL database: no
- Update Method: Webhook
- Self-signed certificate: no (letsencrypt)

**Comment by jacklul** [comment]
https://github.com/akalongman/php-telegram-bot/issues/445
