### ISSUE TITLE
An error when calling a \TelegramBot\Api\Types\Message::toJson

### ISSUE THREAD

**Issue by vansanblch** [akalongman/php-telegram-bot#448]
### Required Information

- PHP version: PHP 7.0.15
- PHP Telegram Bot version: 2.2.7

- Using MySQL database: no
- Update Method: getUpdates
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour
Calling \TelegramBot\Api\Types\Message::toJson of an object with a non-empty `entities` filed should return a json-string

### Actual behaviour
An erro `Call to a member function toJson() on array`

### Steps to reproduce
1. Create a response array
``` php
    $response = [
        "message_id" => 17,
        "from" => [
            "id" => 142775991,
            "first_name" => "first name",
            "last_name" => "last name",
            "username" => "nickname",
        ],
        "chat" => [
            "id" => 142775991,
            "first_name" => "first name",
            "last_name" => "last name",
            "username" => "nickname",
            "type" => "private",
        ],
        "date" => 1491068438,
        "text" => "/latest",
        "entities" => [
            [
                "type" => "bot_command",
                "offset" => 0,
                "length" => 7,
            ],
        ],
    ];
```
2. Create a message from a response
``` php
    $message = \TelegramBot\Api\Types\Message::fromResponse($response);
```
3. Dump the message into a json-string
``` php
    $json = $message->toJson();
```
4. Got an error since `$this->$property->toJson(true)` is called for a field `entities` which is an array

**Comment by chuv1** [comment]
Wrong repo, mate....

**Comment by vansanblch** [comment]
Сорри, слишком много вкладок открыл.

**Comment by chuv1** [comment]
![sith-happens-hd-vector](https://cloud.githubusercontent.com/assets/13127366/24586041/831b64ee-17c2-11e7-97c7-a675434d5d56.png)
