### ISSUE TITLE
bug at message send to all user

### ISSUE THREAD

**Issue by sohrablou** [akalongman/php-telegram-bot#45]
Hi
thanks for this script
When I send a message, the message sent to users is 8 to 9 series.

please help me.

**Comment by MBoretto** [comment]
Thanks for reporting, can you provide more information? 
Do you run it from the admin bot interface or with a custom script?

**Comment by sohrablou** [comment]
Hello
I am the administrator robot to run this command.
My robot more than 2,000 users. My message is about 8 to 9 series sent to users.

If a small number are registered, a message is successfully completed. When the number of users increases, the problem caused by repetitive message.

**Comment by sohrablou** [comment]
+ I am using the webhook in robot...

**Comment by MBoretto** [comment]
I can't reproduce the bug, anyway in the hotfix branch I wrote a new admin function that list all the chats.
Is used the same query as SendtoAll commands, so you can see if there are some duplicate entries.
Please notice that messages are sent to chats not to user, so if a user has more group chats with the bot he will receive a message for each chat.
