### ISSUE TITLE
[question] Create Channel add Users 

### ISSUE THREAD

**Issue by hananaq** [akalongman/php-telegram-bot#453]
Is it possible to create a channel and add user from a database to it through the Bot , 
i managed to use the bot to send a message to a public channel in which he's a member of, but i want it to create the channel, add users and start broadcasting

**Comment by jacklul** [comment]
Bots can't create channels or groups, they also can't add people to them.

**Comment by serviceiran** [comment]
Hello
I have this source
Private Message to guide

http://t.me/hosseineghlimia
