### ISSUE TITLE
Commands without / only Plaintext

### ISSUE THREAD

**Issue by InSide24** [akalongman/php-telegram-bot#459]
Can i create Commands without / ?
Only Plaintext.

Like: User send Text: Deutsch -> Command will be executed 

Kind Regards

**Comment by jacklul** [comment]
Text messages are handled by GenericmessageCommand.
You will have to do your magic there.

**Comment by InSide24** [comment]
i dont understand that ;( 

it is very frustrating

**Comment by haiksu** [comment]
The file
https://github.com/akalongman/php-telegram-bot/blob/master/src/Commands/SystemCommands/GenericmessageCommand.php is the file you need to edit.

For example, add this code to automaticly download photos and files.


	$message = $this->getMessage();
	if (in_array($message->getType(), ['audio', 'document', 'photo', 'video', 'voice'], true)) {
	    $doc = call_user_func([$message, 'get' . ucfirst($message->getType())]);
	    ($message->getType() === 'photo') && $doc = $doc[0];
            $file = Request::getFile(['file_id' => $doc->getFileId()]);
            if ($file->isOk()) {
                Request::downloadFile($file->getResult());
	    }
	}

**Comment by InSide24** [comment]
I made it like this:
`<?php
/**
 * This file is part of the TelegramBot package.
 *
 * (c) Avtandil Kikabidze aka LONGMAN <akalongman@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Longman\TelegramBot\Commands\UserCommands;
use Longman\TelegramBot\Conversation;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\Commands\UserCommands;
/**
 * Generic message command
 */
class TestCommand extends SystemCommand
{
    /**
     * @var string
     */
    protected $name = 'Test';
    /**
     * @var string
     */
    protected $description = 'Handle generic message';
    /**
     * @var string
     */
    protected $version = '1.1.0';
    /**
     * @var bool
     */
    protected $need_mysql = true;
    /**
     * Execution if MySQL is required but not available
     *
     * @return \Longman\TelegramBot\Entities\ServerResponse
     */
    public function executeNoDb()
    {
        //Do nothing
        return Request::emptyResponse();
    }
    /**
     * Execute command
     *
     * @return \Longman\TelegramBot\Entities\ServerResponse
     * @throws \Longman\TelegramBot\Exception\TelegramException
     */
    public function execute()
    {
        //If a conversation is busy, execute the conversation command after handling the message
        $message = $this->getMessage();
		 $from       = $message->getFrom();
        $user_id    = $from->getId();
	
        $chat_id = $message->getChat()->getId();
            $text = 'Sprache erfolgreich auf Deutsch geandert.';

        $data = [
            'chat_id' => $chat_id,
            'text'    => $text,
        ];
        return Request::sendMessage($data);
    }
}`

But it doesnt work ;(

**Comment by noplanman** [comment]
@InSide24 Make a copy of the `GenericmessageCommand.php` file and make your changes there, leaving the class name and namespace. Put that file in a custom folder and add that folder to the bot using `$telegram->addCommandsPath(...);`

**Comment by InSide24** [comment]
@noplanman I allready made all that things you said
But it didnt worked ;(

https://pastebin.com/5uck4SzZ

**Comment by noplanman** [comment]
> ...leaving the class name and namespace.

Class and file name must be `GenericmessageCommand`.

**Comment by InSide24** [comment]
and what is if i need about 5-10 GenericmessageCommands ?
Caus they cant all have the same Filename

**Comment by noplanman** [comment]
Inside the `GenericmessageCommand` you can do whatever you like, require new classes, add extra methods, etc. etc.

Any "generic message" points to the `GenericmessageCommand`, where you can then go crazy 🎉

**Comment by InSide24** [comment]
@noplanman thanks for the Help.

And greetings from Switzerland ;)

**Comment by noplanman** [comment]
> And greetings from Switzerland ;)

😃 vili grüess zrugg!!

As soon as it's working for you, just close off or carry on asking 👍

**Comment by InSide24** [comment]
@noplanman Hey 📦 

German:
Also es funktioniert zwar, komischer Weise wird das aber bei jedem Text denn man eingibt ausgeführt ;(
Möchte es aber gerne so haben das wenn man z.b. denn Text 'Deutsch' sendet, das dann der Command ausgeführt wird.
English:
It makes the Command every time when i send some text and not only when i send text 'Deutsch'

Pastebin: https://pastebin.com/T0LPJJw4
Screenshot: http://prntscr.com/etyr5v

**Comment by noplanman** [comment]
I'll stick to English 😉 

This behaviour is correct, because **every** generic message gets handled by this command!
So you'll have to add some `if` statements to handle specific commands.

Also, for what you're doing, I'd suggest you create a new command for that, like `/config` or something. Then you can handle all configurations much better.

**Comment by InSide24** [comment]
Thanks for helping 😍

**Comment by noplanman** [comment]
@InSide24 You're welcome!

P.S. You can post code and images on GitHub directly, makes it much easier to follow the thread 👍
