### ISSUE TITLE
Sending emojis

### ISSUE THREAD

**Issue by Bizkaitarra** [akalongman/php-telegram-bot#48]
Hi,

First of all thanks for your code and work, it makes very easy to make a bot.

I want to send emojis and I can't see how to do it.

I've sent to a log file all messages I recive and I sent in the conversation with the bot. Then I sent to the bot all the emojis I want. Then I tried to resent the message I recived and the emoji was shown.

But, when I try to send the text I have in my log file, it doesn't work at all...

My log: 
2015-10-29 8:48:31 Jontxu  ha puesto lo siguiente : \ud83d\udc4e\n\n"

In my code I tried all I find:

$data['text'] .= "\n"  . '\ud83d\udc4e\n\n'

OR 

$data['text'] .= "\n"  . utf8_encode('\ud83d\udc4e\n\n')

OR 

$data['text'] .= "\n"  . utf8_decode('\ud83d\udc4e\n\n')

OR as I have read here: http://stackoverflow.com/questions/31279158/unicode-characters-like-emoticons-in-telegram-bot-message-or-keyboard

$data['text'] .= "\n"  . '\xF0\x9F\x91\x8E'

Can you please give me a clue?

Thanks!

**Comment by MBoretto** [comment]
Hello!
Should work with:
'''php
$emoticons = "\ud83d\udc4e";
$data['text'] =  "your text ".json_decode('"'.$emoticons.'"').' bla bla';

'''

**Comment by Bizkaitarra** [comment]
It works!

Thanks one more time :+1: 

I've done a IRC Trivial like bot and with emojis will look better!!! :)

**Comment by NabiKAZ** [comment]
And so can use here: 
http://apps.timwhitlock.info/emoji/tables/unicode
Bytes column directly.
For example:
$data['text'] = "\xF0\x9F\x91\x8D"; // :thumbsup:

**Comment by noplanman** [comment]
Or better yet, just use a proper dedicated library:
[spatie/emoji](https://packagist.org/packages/spatie/emoji)

**Comment by NabiKAZ** [comment]
@noplanman Requires php: ^7.0 is stringent.

**Comment by noplanman** [comment]
True, as should any serious project nowadays.
PHP 7+ should be standard now, best upgrade if you can 👍

**Comment by IgorUsoltsev** [comment]
Double quote was my solution
