### ISSUE TITLE
CURLFile requires PHP >= 5.5.0

### ISSUE THREAD

**Issue by ivanbaldo** [akalongman/php-telegram-bot#52]
composer.json says that it requires PHP 5.4 but CURLFile is available only in PHP 5.5.0.
It is used here:
https://github.com/akalongman/php-telegram-bot/blob/master/src/Request.php#L225
Thanks!

**Comment by MBoretto** [comment]
@akalongman shouldn't travis ci complain about this?

**Comment by akalongman** [comment]
@MBoretto no, travis can not check real required php version of script. We must change minimum required php version to >=5.5 and remove php 5.4 tests from .travis.yaml

**Comment by MBoretto** [comment]
Fixed
