### ISSUE TITLE
Disabling WebHook

### ISSUE THREAD

**Issue by ivanbaldo** [akalongman/php-telegram-bot#53]
It is valid to set URL to an empty string to disable a webhook.
Either not throw exception when URL is empty in setWebHook() or create a disableWebHook() method.
Thanks!!!

**Comment by MBoretto** [comment]
Thanks for reporting it will be fixed

**Comment by MBoretto** [comment]
Fixed in 0.23

**Comment by deadmann** [comment]
if fixed why there's nothing about it on the doc? how it works?

**Comment by noplanman** [comment]
It is in the readme, right [here](https://github.com/akalongman/php-telegram-bot#unset-webhook) 👍 
Check the appropriate file to see the usage.

Basically `$telegram->unsetWebHook();`

**Comment by deadmann** [comment]
well i meant the telegram documents :) :+1:
