### ISSUE TITLE
Error when sending message to channel

### ISSUE THREAD

**Issue by luigif** [akalongman/php-telegram-bot#54]
It is now possible to send messages to channels using @channelname as chat_id in the sendMessage method.
However the curl_exec in executeCurl of Request.php breaks since a @ is interpreted as prefixing a file to upload.

Suggested fix is to add:

            if (!empty($data['chat_id']) && substr($data['chat_id'], 0, 1) === '@') {
                curl_setopt($ch, CURLOPT_SAFE_UPLOAD, true);
            }

before curl_setopt_array($ch, $curlConfig) in function executeCurl

**Comment by MBoretto** [comment]
Thanks for reporting it will be fixed!

**Comment by MBoretto** [comment]
fixed in 0.25.0
