### ISSUE TITLE
Create custom command and keyboard

### ISSUE THREAD

**Issue by kiarash3tar** [akalongman/php-telegram-bot#58]
Hi;
Thanks for this cool script. :+1: 

I wish that I could find more detailed documentation for your script.

I started to use your script recently and everything seems nice BUT
need to know :
 How can I write my own commands?
I did create a class named `testCommand` in commands folder but this way didn't work.

Would you please help me to create my own `command` and `custom keyboard`?

***Thanks in Advance***

**Comment by kiarash3tar** [comment]
Problem solved.

I did made my command file in lower case :
<h6>Wrong way</h6>  **t**estCommand.php
<h5>Right way</h5> **T**estCommand.php

Well, now I need to learn how can I create my own custom keyboard?
Would you please help me?

**Comment by kiarash3tar** [comment]
OK,
Second problem Solved.

`KeyboardCommand.php` in `examples/Commands/` was Checked and this is the solution : 

first of all, use dependencies for reply_markup:
<pre>
use Longman\TelegramBot\Entities\ReplyKeyboardMarkup;
use Longman\TelegramBot\Entities\ReplyKeyboardHide;
use Longman\TelegramBot\Entities\ForceReply;
</pre>

and then, prepare a variable named `$keyboards` : 
<pre>
        $keyboards = array();
</pre>

And next step is styling custom keyboard using an array named $keyboard: 
<pre>
        $keyboard[] = ['7','8','9'];
        $keyboard[] = ['4','5','6'];
        $keyboard[] = ['1','2','3'];
        $keyboard[] = [' ','0',' '];
</pre>

In next step, you have to pass $keyboard array to $keyboard***s*** and `unset` $keyboard :
<pre>
        $keyboards[] = $keyboard;
        unset($keyboard);
</pre>
Now initiate `ReplyKeyboardMarkup` : 
<pre>
        $reply_keyboard_markup = new ReplyKeyboardMarkup(
            [
                'keyboard' => $keyboards[0] ,
                'resize_keyboard' => true,
                'one_time_keyboard' => false,
                'selective' => false
            ]
        );
</pre>

And at last simply add this to send parameters using  : 
<pre>
        $data['reply_markup'] = $reply_keyboard_markup;
</pre>

This is very cool script and just need more documentations.

Well Done...

**Comment by MBoretto** [comment]
Thanks, for trying it! It would be great if you could start write a wiki page with this recipe to build custom commands!

**Comment by kiarash3tar** [comment]
Your welcome...
I'll do it... Please correct me if I did understand something wrong.

**Comment by MBoretto** [comment]
I've seen the page good job! Thanks again!
