### ISSUE TITLE
Reply Markup

### ISSUE THREAD

**Issue by MBoretto** [akalongman/php-telegram-bot#6]
I'm working on class that build the json query to fill the reply_markup parameters in send message, this will let you create keyboard faster.

**Comment by akalongman** [comment]
We must create ReplyKeyboardMarkup entitiy for that.

**Comment by MBoretto** [comment]
It have to be an extension of the Entity class Rigth? I will put it in the Entity dir!

**Comment by akalongman** [comment]
Yes. Like Message or Update entity
