### ISSUE TITLE
Messages containing Emoji are not stored correctly in the database

### ISSUE THREAD

**Issue by trashish** [akalongman/php-telegram-bot#62]
Looks like it is stored only the first part part of the text before the Emoji.

**Comment by MBoretto** [comment]
Thanks for reporting,
can you provide further details? Which version are you using? Which emoji?
If you have mysql 5.5 you can try the the branch [utf8mb4](https://github.com/MBoretto/php-telegram-bot/tree/utf8mb4). Should provide a better support for special characters

**Comment by trashish** [comment]
This is an example of message: "text":"\/location \ud83c\udf07 Milano (1)",
my mysql  is 5.5.41 on ubuntu 14 x8_64, my version is still: ^0.22.0

Idid not update yet but I see that branch utf8mb4
<https://github.com/MBoretto/php-telegram-bot/tree/utf8mb4> has some slight
changes in structure.sql

-) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
+) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

I tried altering the tables directly with no results.
es: ALTER TABLE `tg_messages` DEFAULT CHARACTER SET utf8mb4 COLLATE
utf8mb4_general_ci;

Note that the following message: "\/company (3) \u2b50\u2b50\u2b50
4\ud83d\udcdd 171\ud83d\ude95\n\ud83d\udcdeYellowTaxi"
Stores only the following part: /"company (3) ⭐⭐⭐ 4"

Nito

2015-12-13 15:24 GMT+01:00 Marco Boretto <notifications@github.com>:

> Thanks for reporting,
> can you provide further details? Which version are you using? Which emoji?
> If you have mysql 5.5 you can try the the branch utf8mb4
> <https://github.com/MBoretto/php-telegram-bot/tree/utf8mb4>. Should
> provide a better support for special characters
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akalongman/php-telegram-bot/issues/62#issuecomment-164263010>
> .
>



-- 

*BiT-wins Ventures Ltd*
20-22 Wenlock Road, London
N1 7GU United Kingdom
+39 3939576993

**Comment by MBoretto** [comment]
Did you alter also the columns? 
http://tonyshowoff.com/articles/better-unicode-support-for-mysql-including-emoji/

**Comment by trashish** [comment]
I did now and fixed the problem.
Thanks for the link!

2015-12-14 18:01 GMT+01:00 Marco Boretto <notifications@github.com>:

> Did you alter also the columns?
>
> http://tonyshowoff.com/articles/better-unicode-support-for-mysql-including-emoji/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akalongman/php-telegram-bot/issues/62#issuecomment-164494827>
> .
>



-- 

*BiT-wins Ventures Ltd*
20-22 Wenlock Road, London
N1 7GU United Kingdom
+39 3939576993
