### ISSUE TITLE
Custom commands name problems

### ISSUE THREAD

**Issue by Jertlok** [akalongman/php-telegram-bot#63]
Hello there, i noticed that some custom name commands work and others not.
I didn't set any custom path, i directly wrote inside the original commands path... i made a command that allows to see the user stats, it just works fine but only under specific names "/slap"...i tried it with "/SeeStats" and it didn't work. I also created another command under the name "/SetWelcome" and this works. What can i do?

**Comment by MBoretto** [comment]
Have you seen the guide on the wiki?
https://github.com/akalongman/php-telegram-bot/wiki/Create-your-own-commands
Should be a case sensitive name problem

**Comment by Jertlok** [comment]
It's been syntax error, defined the class name without the Command suffix. Thank you anyway, and sorry about this little report.
