### ISSUE TITLE
one question , array or  object 

### ISSUE THREAD

**Issue by alpastar** [akalongman/php-telegram-bot#65]
i  appreciate your effort  for this library .
but  i have one question , trying to figure out why

$a_result= json_decode($result, true)                              // parse as array, not object
$o_message = new Message($a_result,$c_bot_name)   // make  messageobject from array

my question is, why decode with a array, 
is there any problem or some  other reasons  that you  do not  make a target object from object?
(example)
$o_result= json_decode($result)                                        // parse as object
$o_message = new Message($o_result,$c_bot_name)    // make object from object

**Comment by MBoretto** [comment]
Hello I think that can work olso with object, never consider this option before, maybe @akalongman knows more about this choice

**Comment by alpastar** [comment]
thank you for your reply
