### ISSUE TITLE
CurlFile class not found

### ISSUE THREAD

**Issue by Excody** [akalongman/php-telegram-bot#66]
Good afternoon. If you try to send a local file, I come across an error PHP Fatal error: Class 'CURLFile' not found in ... /src/Request.php on line 224
I have no idea how to fix it. Thank you.

**Comment by Excody** [comment]
PHP Version 5.4.16
cURL support 	enabled
cURL Information 	7.29.0
Age 	3
Features
AsynchDNS 	Yes
Debug 	No
GSS-Negotiate 	Yes
IDN 	Yes
IPv6 	Yes
Largefile 	Yes
NTLM 	Yes
SPNEGO 	No
SSL 	Yes
SSPI 	No
krb4 	No
libz 	Yes
CharConv 	No
Protocols 	dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, scp, sftp, smtp, smtps, telnet, tftp
Host 	x86_64-redhat-linux-gnu
SSL Version 	NSS/3.19.1 Basic ECC
ZLib Version 	1.2.7
libSSH Version 	libssh2/1.4.3

**Comment by MBoretto** [comment]
Hello, wich version of the libray are you using?

**Comment by Excody** [comment]
Update version php to 5.6 solve this problem.
