### ISSUE TITLE
/command@BotName not working

### ISSUE THREAD

**Issue by elvis-pereira** [akalongman/php-telegram-bot#67]
First of all thank you for this incredible library :+1: 
My problem is: In a channel with two other bots (ImageBot and PollBot) when I try to use the command /help@MyBot it does not work, using only /help the command is executed correctly but triggers the same command over the other two bots. Is there anything else that needs to be configured so the command /help@MyBot can be used? I'm using the latest release.

**Comment by MBoretto** [comment]
It should work, the code passed this test:
https://github.com/akalongman/php-telegram-bot/blob/master/tests/Unit/Entities/MessageTest.php#L87

Did you put the proper $botname in the telegram lib initialization?

**Comment by elvis-pereira** [comment]
The $botname was wrong, fixed it and is working like a charm now, thanks :)

**Comment by CrazyRedScorp** [comment]
Sorry. I have the same problem. But I understood!
I send @botfather command "/setcommands", choose @myname_bot and type "command1 - my description". Then I wrote in a chat (or click on the left "/"):
```
/command@myname_bot
```
But answer = empty. This is my error! My $BOT_NAME was wrong.

You need to add in your description of the variable $BOT_NAME:
$BOT_NAME = 'username_bot';
This is username of bot with "_bot"!!! That you have specified in the @botfather in a message: "Now let's choose a username for your bot. It must end in `bot`".

Not "namebot" (example: "firstcats"), only "username_bot" (example: "mycats_bot").

Thanks.
