### ISSUE TITLE
reply_markup

### ISSUE THREAD

**Issue by hippieua** [akalongman/php-telegram-bot#68]
Im trying to send reply_markup on /start command to add virtual keyboard

like this example: https://core.telegram.org/bots/samples/hellobot

$reply_markup = array(
        'keyboard' => array(array('Hello', 'Hi')),
        'one_time_keyboard' => true,
        'resize_keyboard' => true);
$data['reply_markup'] = $reply_markup;
$result = Request::sendMessage($data);

but nothing happens

**Comment by MBoretto** [comment]
reply markup must be json encoded.
Use the class included in the library as explained here:
https://github.com/akalongman/php-telegram-bot/blob/master/examples/Commands/KeyboardCommand.php

**Comment by hippieua** [comment]
Thank you! That helps a lot!
