### ISSUE TITLE
Create Inline Entities 

### ISSUE THREAD

**Issue by MBoretto** [akalongman/php-telegram-bot#70]
InlineQueryResultArticle (Done)
InlineQueryResultPhoto
InlineQueryResultGif
InlineQueryResultMpeg4Gif
InlineQueryResultVideo

**Comment by liz7124** [comment]
in your code in update.php start from line 43, where did you get the value of $data ?

        $this->inline_query = isset($data['inline_query']) ? $data['inline_query'] : null;
        if (!empty($this->inline_query)) {
            $this->inline_query = new InlineQuery($this->inline_query);
            $this->update_type = 'inline_query';
        }
        $this->chosen_inline_result = isset($data['chosen_inline_result']) ? $data['chosen_inline_result'] : null;
        if (!empty($this->chosen_inline_result)) {
            $this->chosen_inline_result = new ChosenInlineResult($this->chosen_inline_result);
            $this->update_type = 'chosen_inline_result';
        }
    }

**Comment by ericxxp** [comment]
Well done !

**Comment by liz7124** [comment]
Hi.
I want to ask, did you get an error like 'MEDIA_CAPTION_TOO_LONG' when send InlineQueryResultArticle? Is "message_text" have a character limit?
I was search on telegram official web, but didn't find the answer yet.
thank you..

**Comment by MBoretto** [comment]
Hello, did you get this error by curl?
How long is your caption?
I didn't notice this error, i performed very few test on this feature!

**Comment by liz7124** [comment]
Yes, I got this error by curl.
I think almost 3000 character long.
Actually I put this value on "message_text" variable, not in caption. On Telegram bot api manual there is no information about max character of message_text  for InlineQueryResultArticle

**Comment by Saly121** [comment]
there is a limit "Text of the message to be sent, 1-4096 characters" https://core.telegram.org/bots/api#inputtextmessagecontent.
