### ISSUE TITLE
How to send a message to channel without user interaction?

### ISSUE THREAD

**Issue by frenzis** [akalongman/php-telegram-bot#71]
Hi, and thank you for your work. I'm trying to send a message to a channel without user interaction. My Bot is admin of the channel. Did you have a simple working example using the `sendMessage` method?

**Comment by MBoretto** [comment]
Hello did you seen the command send to channel in the admin dir? This provide what you're looking for, to use this command you should enabled the admin interface of the bot (not the channel) as explained in the readme. Let me know if the  documentation is enough clear ask if you have further questions

**Comment by frenzis** [comment]
Thank you Marco. The example is clear, but I would like to send a message to a channel without interacting with the bot in the Telegram app (ie: without sending a `/sendtochannel` command). For example: I would like to read a rss feed and send a message to the channel (via the bot) every time a new items is published. I know I can use a simple script (like [this one](http://stackoverflow.com/a/32875341/1760030)), but I like your classe and I would like to use it without any other code.

**Comment by MBoretto** [comment]
use Longman\TelegramBot\Request;
            $data = [];
            $data['chat_id'] = '@your_channel';
            $data['text'] = 'Hello';
            $result = Request::sendMessage($data);
            if ($result->isOk()) {
                echo 'Message sent succesfully to: '.$data['chat_id'] ;
            } else {
                echo 'Sorry message not sent to: '.$data['chat_id'] ;
            }


Thats all you need to use the class without the bot interface, notice that you should set a cron to  read the  RSS.

**Comment by frenzis** [comment]
Perfect! Thank you.

**Comment by ariefbayu** [comment]
here's my code for broadcast message to particular chat: https://gist.github.com/ariefbayu/e3ffe27f9c50cb674edd

**Comment by noplanman** [comment]
Thanks for sharing your CLI-friendly version :smiley: 

A few notes about your code if I may:
- Telegram constructor already handles the `Request::initialize()` method, so you don't need to do that separately.
- Also, you probably want to use `&&` instead of `||` here:

`if ($message !== '' && $telegramId !== '') {...}`

**Comment by ariefbayu** [comment]
Awesome, thank you for the suggestion!

**Comment by MBoretto** [comment]
@ariefbayu great! This can help other users! Feel free to open a wiki page with your example that point to your code!

**Comment by ariefbayu** [comment]
@MBoretto I wrote it here: https://github.com/akalongman/php-telegram-bot/wiki/How-to-send-message-to-channel-user-without-user-interaction

Feel free to enhance it.

**Comment by noplanman** [comment]
Thanks @ariefbayu!

I've [forked your gist](https://gist.github.com/noplanman/5f81bf74a8defccb4509) and made the code PSR2 friendly, then updated the wiki page.
Feel free to update your gist and add a link to it on the wiki page if you like :smiley: 

Also, it would make sense to add at least a bit of error handling, like some output if no chat id or message is passed. Just a simple `Usage: ...` message so the user can see it.
And if the API key and bot name haven't been changed, the request shouldn't even be sent to Telegram, as it will definitely fail.

And I was playing with the idea of setting the `$API_KEY` and `$BOT_NAME ` variables from environment variables ([`getenv`](https://secure.php.net/manual/en/function.getenv.php)), that way the script wouldn't even need to be modified by hand.
What do you think?

**Comment by ebrahimporiyan** [comment]
@noplanman @frenzis @MBoretto @ariefbayu @boukeversteegh 

Hi. Is there a script that I can add more members to my grammar channel. 
For example, members are forced to enter the channel . 
For example, some telegraph channels do this.
Please, if anyone knows, help me
my gmail (azadmard0641@gmail.com)
my telegram number 00989366043698

**Comment by noplanman** [comment]
@ebrahimporiyan No, that is not supported
