### ISSUE TITLE
curlfile not found

### ISSUE THREAD

**Issue by tuytoosh** [akalongman/php-telegram-bot#77]
[Fri Jan 29 01:04:59.725805 2016] [:error] [pid 7415:tid 140503525742336] [client 65.49.68.205:63718] PHP Fatal error:  Class 'CURLFile' not found in /home/upload/domains/hozoorema.com/public_html/vendor/longman/telegram-bot/src/Request.php on line 225

**Comment by MBoretto** [comment]
I think that could be due to your php version?  Which is?

**Comment by akokarev** [comment]
I have the same problem when trying to do sethook with sending the certificate.
PHP Version 5.4.16.

**Comment by MBoretto** [comment]
This issue regards the same problems, seems reletated to the php version.
https://github.com/akalongman/php-telegram-bot/issues/66

I should check at which version Curlfile has been introduced.

**Comment by akokarev** [comment]
Thank you @MBoretto! This helped. Also had a problem with incorrect installation of the certificate.

**Comment by noplanman** [comment]
@tuytoosh @akokarev 
[CURLFile](https://secure.php.net/manual/en/class.curlfile.php) was introduced in PHP 5.5.0.
So minimum PHP version is 5.5.0 :wink:
