### ISSUE TITLE
Use custom path

### ISSUE THREAD

**Issue by ruslanmedia** [akalongman/php-telegram-bot#8]
Hi! I want use multiple bots.
I added this to file hook.php
$telegram->addCommandsPath(BASE_PATH.'/Commands/MuzUzBot');
I created file to folder /vendor/longmang/telegram-bot/src/Commands/MuzUzBot and file HelpCommand.php

This command not working :( How to use it?

**Comment by sabas** [comment]
I simply made two directories with telegram-bot code in it, changing the code of the webhook to point at  the subdirectory instead of the root..
