### ISSUE TITLE
improve /slap command

### ISSUE THREAD

**Issue by MBoretto** [akalongman/php-telegram-bot#85]
https://github.com/akalongman/php-telegram-bot/pull/83/files#diff-84cb555187fe87184b35292babc9e956R70

Can be rewritten with the new methods tryMention in the user class 
https://github.com/akalongman/php-telegram-bot/blob/master/src/Entities/User.php#L63

@sabas wuold you do that?

**Comment by sabas** [comment]
What is the $data array ? How User needs to be instanced?

**Comment by noplanman** [comment]
So basically to display the user's real name if there is no `@username` available?

The `/slap` command is similar to the `/echo` command, in that it gives you back a predefined string with the text you've added as a parameter. Right?

**Comment by sabas** [comment]
Yes!

**Comment by noplanman** [comment]
Ok, so @MBoretto I think your idea is great, because the way it is now, if there is no `@username` available, the output would be something like this:
`@ slaps @somebodyelse around a bit with a large trout`

Also, we would be reusing code and not have duplicate code :blush: :+1:

**Comment by MBoretto** [comment]
Sorry as @noplanman said is not available..
