### ISSUE TITLE
Configure Exception storage

### ISSUE THREAD

**Issue by MBoretto** [akalongman/php-telegram-bot#88]
It would be fine to add a method to enable and disable exception log and also to configure the path of the file.

**Comment by noplanman** [comment]
Functionality for this is already outlined in the [README](https://github.com/akalongman/php-telegram-bot/blob/develop/README.md#logging), we just need to implement it properly.

@akalongman Was this code already in the project at some point and then removed?

**Comment by noplanman** [comment]
Should the exceptions be saved in the same file as the normal logs?

I was thinking that it might make sense to leave the exception logging as it is, so that we can simply ask somebody who is having issues, to post the file `TelegramException.log` from the root directory.

What do you think?

**Comment by christianromeni** [comment]
Exceptions should not be logged to the same file..

**Comment by MBoretto** [comment]
Thank for the suggestion @christianromeni ! We plan to implement this in the next release 0.30

**Comment by ivanbaldo** [comment]
I don't understand why exception logging is required.
Shouldn't users just do a try catch block and log themselves?

**Comment by MBoretto** [comment]
@ivanbaldo can you show me an example?

**Comment by ivanbaldo** [comment]
In https://github.com/akalongman/php-telegram-bot/blob/master/examples/hook.php there is a catch block and it suggests people to log them there.
We are using that example and what we get is duplicated logs of the same exceptions (but we use SysLog instead, so in production we just comment out the file_put_contents() call).

**Comment by MBoretto** [comment]
@ivanbaldo  Thanks for point this out, you  are right. Feel free to open a pull request to fix it!

**Comment by ivanbaldo** [comment]
I was going to work into this but found this commit https://github.com/akalongman/php-telegram-bot/commit/b1184d862d17fb8e300d57944658a9608742f904 that I think deals with this issue.
So, should I delete all that code or someone just closes this issue as solved?
I am confused heh :-).

**Comment by MBoretto** [comment]
Yes that commit deals with it, you pointed out that the exception file is not the proper place where you have to put the log, so you can move the code in the try catch

**Comment by ivanbaldo** [comment]
So, this issue should be closed then, commit b1184d8 makes the exception storage optional and configurable.
Maybe I am missing something?
Thanks a lot!!!

**Comment by MBoretto** [comment]
closing thanks
