### ISSUE TITLE
Can't send message use hook

### ISSUE THREAD

**Issue by HalimZamal** [akalongman/php-telegram-bot#91]
Hello...

I have a problem with Request.php when I use sendMessage method and other function in request class .. I got this
Fatal error: Call to a member function getApiKey() on a non-object in D:....\vendor\longman\telegram-bot\src\Request.php on line 126

How to solved this? please help

**Comment by noplanman** [comment]
Could you please share with us which file you are opening in your browser and what it looks like?
**Remember to remove any private info like bot name and API key!!**

Also, did you follow [this guide](https://github.com/akalongman/php-telegram-bot#webhook-installation)?

**Comment by HalimZamal** [comment]
Yes I followed that [guide](https://github.com/akalongman/php-telegram-bot#webhook-installation) ,,,
for the first I run set.php of course I have uploaded hook.php in https (ssl),, 

but when I tried to implement send message method like this [guide ](https://github.com/akalongman/php-telegram-bot#send-message) I got a error like above..

I just modified set.php to use the method 

$request = new Longman\TelegramBot\Request($API_KEY, $BOT_NAME);
$result = $request::sendMessage(['chat_id' => $chat_id, 'text' => 'sample message']);

when i used getUpdateCli everthing is fine, but whe I tried use webhook I got the error..

**Comment by noplanman** [comment]
So I can assume you got a "success" response when you set the webhook, yes?

As for the Request, the code you're using won't work, where did you find it like that?

The correct code is exactly how it is in the readme:
`$result = Request::sendMessage(['chat_id' => $chat_id, 'text' => 'sample message']);`

or if you haven't added `use \Longman\TelegramBot\Request;` at the top of your file, use this:

`$result = Longman\TelegramBot\Request::sendMessage(['chat_id' => $chat_id, 'text' => 'sample message']);`

Do you have MySQL activated? Can you view the database table `chat`?
After starting the conversation with your bot in Telegram, you should have a new item in that table, where you can find the chat ID that you want to send the message to.

Does this now work for you? It may seem a bit complex to start, but just ask if you need to know more :smiley:

**Comment by HalimZamal** [comment]
Yeah... it's work now,, that's what I looking for... thanks a lot @noplanman :)

**Comment by noplanman** [comment]
With this library you can easily implement your own commands! :+1: 

Have a look [here](https://github.com/akalongman/php-telegram-bot#commands) to get started.

I suggest you create a new folder and put your own command files in it.
Your command folder can then be included using:
`$telegram->addCommandsPath('path/to/your/commands/');`

I'll close this issue here, if you have a specific question regarding the usage of creating own commands, just open a new one :blush: 

Enjoy!

**Comment by HalimZamal** [comment]
Ok.. thanks again :+1:
