### ISSUE TITLE
How to use Commands 

### ISSUE THREAD

**Issue by HalimZamal** [akalongman/php-telegram-bot#92]
I tried to use Commands..
first I created folder called "cmd" in root and then in webhook I enabled

$COMMANDS_FOLDER = __DIR__.'/cmd/';
$telegram->addCommandsPath($COMMANDS_FOLDER);

for example I want to try to use ForcereplyCommand.php in cmd folder. But I confused how to register the class and how to use that in another file.

please give me an idea to solved this..?

**Comment by noplanman** [comment]
I'm not sure how experienced you are with PHP, so I'll try to make it as simple as possible :blush: 

Right, the path you're looking for is `$COMMANDS_FOLDER = __DIR__ . '/cmd/'`.
`__DIR__` represents the current directory of the file being executed. To see which path is being set, just add this line directly after it: `die($COMMANDS_FOLDER);` When you visit the page now, you should see just a line of text that should be the path to your `cmd` folder. Make any changes if necessary and when the path is the correct one, remove the `die(...);` line.

**Now for the fun part, the command.**

For your example, the easiest would be to copy the file `/php-telegram-bot/src/Commands/EchoCommand.php` into your `cmd` folder. Rename it to `ForcereplyCommand.php`.

Now you can open it to edit the code.
Start off by renaming the class to `ForcereplyCommand` and by changing the values of the class variables (`$name`, `$description`, etc.). Your `$name` would be `forcereply`.

The `execute` method is what gets called when someone sends the command to your bot.
Here you can set the `$text` variable to whatever should be sent back to the user.

Now, when you send `/forcereply` to your bot, the text you've saved in `$text` will be sent back to you.

Let me know how it's going so far :smiley:

**Comment by HalimZamal** [comment]
I understand until that part, I only confused how to call that class (ForcereplyCommand or etc) ? 
how I must register the class  and where ?

I tried to create new file in root called autoreply.php and then register that class to there.. but I got error message 


$cmd = new Longman\TelegramBot\Commands\ForceReplyCommand();
$result = $cmd->execute($cmd);

but I got 
Class 'Longman\TelegramBot\Commands\ForceReplyCommand' not found..

then what should I do ?

**Comment by noplanman** [comment]
No, that looks correct.

Does your bot respond with any answer at all when you send `/forcereply`?

**Comment by HalimZamal** [comment]
I've tried to use getUpdateCLI not hook.. and everything is working the bot replied.. but when I used webhook.. nothing happened..

what's wrong?

**Comment by noplanman** [comment]
Are you by any chance using a self signed SSL certificate?

**Comment by HalimZamal** [comment]
No i'm not,,, I used heroku for deploying in https environment...

**Comment by noplanman** [comment]
You set the webhook correctly using your modified `set.php`, yes?

**Comment by HalimZamal** [comment]
yes..

**Comment by noplanman** [comment]
Have you checked the `TelegramException.log` and the `your-bot-name.log` in the root directory?
You can rename/delete them first, then try the command again.
If they get regenerated, could you please share their contents so we can see what's happening, thanks.

**Comment by HalimZamal** [comment]
my-bot-name.log is empty .. but in TelegramException.log I found 

#1 {main}
2016-02-07 04:25:48 exception 'Longman\TelegramBot\Exception\TelegramException' with message 'Input is empty!' in D:\xampp\htdocs\telegram5\vendor\longman\telegram-bot\src\Telegram.php:383
Stack trace:
#0 D:\xampp\htdocs\telegram5\webhook.php(29): Longman\TelegramBot\Telegram->handle()
#1 {main}

**Comment by noplanman** [comment]
There might be an issue with your `webhook.php` file. It looks like the input that is provided by the Telegram API isn't getting through to your hook properly.

Could you please share your `webhook.php` file (removing any private info).

**Comment by HalimZamal** [comment]
This is my webhook.php 

$loader = require __DIR__.'/vendor/autoload.php';
$API_KEY = 'Bot Token here';
$BOT_NAME = 'namebot';
$COMMANDS_FOLDER = __DIR__.'/cmd/';

/*$credentials = [
    'host'=>'localhost',
    'user'=>'username',
    'password'=>'',
    'database'=>''
];
*/

try {
// create Telegram API object
$telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);

//$telegram->enableMySQL($credentials);

// Log Telegram messages
$telegram->setLogRequests(true);
$telegram->setLogPath($BOT_NAME.'.log');
$telegram->setLogVerbosity(1);
// Custom commands folder
$telegram->addCommandsPath($COMMANDS_FOLDER);
die($COMMANDS_FOLDER);
// handle telegram webhook request
$telegram->handle();
} catch (Longman\TelegramBot\Exception\TelegramException $e) {
// log telegram errors
echo $e->getMessage();
}

**Comment by noplanman** [comment]
Remove the line `die($COMMANDS_FOLDER);` and try again please.

The rest looks fine to me.

**Comment by HalimZamal** [comment]
still same the bot doesn't replied the command..

**Comment by noplanman** [comment]
In you `set.php` you've entered the correct URL to the `webhook.php` file, right?
And it's publicly accessible, yes?

**Comment by HalimZamal** [comment]
yes..

**Comment by noplanman** [comment]
In that case I really don't know where the problem may be :confused: 
The last thing I can think of, is to call `unset.php` and then `set.php` again, in case there was some problem when setting the webhook.

@MBoretto @akalongman You mind having a look at this please?

**Comment by HalimZamal** [comment]
ok @noplanman .. thanks for your help,,,

**Comment by HalimZamal** [comment]
@noplanman ... I tried to use self signed SSL certificate.. but stiil same...

perhaps you even meet the problem like this with self signed cert?

**Comment by MBoretto** [comment]
Hello, there is a wiki guide to create your first command. Telegram need https to reach your webhook check if you have it. You should write the address with https://.  If the address is wrong or without https will fail silently without log. Log with input is empty can be due to browser that attemp to reach the webhook.

**Comment by MBoretto** [comment]
I forgot, I never mix webhook and get updates, I've read on the documentation that can't work together.  So maybe telegram is non happy when you swicth between so fast

**Comment by HalimZamal** [comment]
hello @MBoretto  I've used https and get result "Webhook was set" ... 
I always run unset.php before I changed the method from webhook to getupdates, and yes of course webhook and getupdates can't work together..

**Comment by noplanman** [comment]
When using a self signed certificate, you need to pass it in `set.php` as described [here](https://github.com/akalongman/php-telegram-bot#self-signed-certificate).

I've used a self signed certificate and a Let's Encrypt certificate with no problems at all.

Maybe to make sure that this isn't the problem, you can try using a [Let's Encrypt](https://letsencrypt.readthedocs.org/en/latest/using.html#installation) certificate.

**Comment by HalimZamal** [comment]
I've used a self signed certificate and pass  the path in `set.php` but still not work.. I can't use let's encrypt because I deployed in shared hosting now.. 

I wrote this code..
$certificate = realpath('cert.pem');
$result = $telegram->setWebHook($url, $certificate);

Am I wrong?

**Comment by noplanman** [comment]
If `cert.pem` is the correct server certificate it should be correct.
Have you made sure that `$certificate` has the correct path saved?

**Comment by HalimZamal** [comment]
yes,, I've made sure about the certificate path.. and still not work..

Currently I will use getUpdate method,, 
Thanks for all of you help..

**Comment by IronLady** [comment]
I know that this issue is almost a year old. 
I get the same issue and able to solve it. 

I am not sure why **mb_convert_case** function is undefined in Heroku. 
We can fix this by add **"ext-mbstring": "*"** dependency in your composer and update.

**Comment by noplanman** [comment]
@IronLady Thanks for that!
