### ISSUE TITLE
$enabled and $public not working properly

### ISSUE THREAD

**Issue by noplanman** [akalongman/php-telegram-bot#94]
**Regarding the Commands**

**`$enabled`**:
If set to `false`, calling the command simply doesn't return anything, yet when calling an invalid command (like `/thisdoesntexist`) an error message is returned: `Command: thisdoesntexist not found.. :(`

In my opinion, disabled commands should return something and not just fail silently.

**`$public`**:
This settings seems to only influence the `/help` command. Even if set to `false`, anybody can execute the command. It's as if setting `$public = false;` actually means something like `$hidden = true;`, simply not showing the command in the list, but still being available for everybody to use.

Is this how `$public` is supposed to work?

**Comment by MBoretto** [comment]
In my opinion, public true mean that can be called by user public false instead can be call only by system.
I agree  that disable commands should return something at least command not found. This problems can be overcome with the new command system.

**Comment by noplanman** [comment]
With the new command structure, this partly becomes invalid.

What stays though, is the `$enabled` member variable, which we need to find a good solution for, because at the moment there is no way to disable a command without modifying the code of the commands in the library itself.

Since the command objects are instantiated just when they are being used, we would need to have a separate array of command names, which remembers the ones that should be disabled. This could mean that we can remove the member variable from the command objects themselves.

Open for suggestions!

**Comment by MBoretto** [comment]
We can define a command blacklist.
We can also add some methods to diasable completly Admin, User or System.

**Comment by noplanman** [comment]
Yes, I think when we start working on the `Commander` class, we'll find a good solution to manage which commands are active or not, then we can remove this functionality from the `Command` classes.

I was thinking of a blacklist as you call it, which could be a callback function that passes an array of the current commands, allowing the user to modify the array, something like this:
```php
$commander->enabledCommands(function($commands) {
    // $commands contains a list of all commands.
    foreach(['whoami', 'slap', 'anyothercommand'] as $command) {
        unset($commands[$command]);
    }
    return $commands;
});
```
Then, when fetching the list of commands, we take this array into account and see which ones are enabled and which ones aren't.
We just need to find a smart way to handle the custom commands as well, as those would fall into the same category.

We can also add a method which allows users to remove a commands folder:
```php
$commander->removeCommandsPath(...);
```
This could also be done with a callback function like above, to add any custom folders in one command. Maybe...

Just brainstorming... :wink:

**Comment by MBoretto** [comment]
I'm not sure about the remove the command folder. 
Why I should remove them? Do you intend it for the command provided by the library? 
For this we can add a flag like 
```
$commander->unloadAllLibCommand();
```

**Comment by MBoretto** [comment]
This has been overcome with the new command structure 0.29
